### ISSUE TITLE
AWS 'eu-south-1' (Milan) region not supported

### ISSUE THREAD

**Issue by mimmus** [kubecost/cost-model#1030]
Lot of:
`I0112 15:39:41.110895 1 costmodel.go:946] Error getting node pricing. Error: Invalid Pricing Key "eu-south-1,m5.2xlarge,linux"`
in cost-analyzer logs.

gz#1270

gz#1403

**Comment by kbrwn** [comment]
@mimmus Thanks for reporting this. We would be happy to investigate further. Could you capture a full [bug report](https://guide.kubecost.com/hc/en-us/articles/4407601805975-Capture-a-bug-report) from settings.html and e-mail it to support@kubecost.com?

**Comment by mimmus** [comment]
I use kubecost as included in D2iq Konvoy distro.
I opened a support case with D2iq and they will check with you.

**Comment by keithhand** [comment]
@mimmus That sounds great. In the meantime, to get you running ASAP, we could look through the configuration of your environment via a [bug report](https://guide.kubecost.com/hc/en-us/articles/4407601805975-Capture-a-bug-report) sent to support@kubecost.com. If that's something that you're interested in, of course.

**Comment by ivankube** [comment]
"eu-south-1" is missing from https://github.com/kubecost/cost-model/blob/master/pkg/cloud/awsprovider.go#L100-L124

We are also missing:

"af-south-1"
"ap-southeast-3"
