### ISSUE TITLE
Window has default values in some API's, don't in others

### ISSUE THREAD

**Issue by souenzzo** [kubecost/cost-model#1039]
Some API's, like `api-request-right-sizing` has a default value for the `window` parameter.
Other API's throws an error when `window` parameter is not present: `window is a required parameter`

Would be nice if they have a homogeneous behavior. 

Also is not clear which is the default value for the window in `api-request-right-sizing`

Refs:
- https://docs.kubecost.com/api-request-right-sizing.html
- https://docs.kubecost.com/allocation.html

gz#1283

**Comment by keithhand** [comment]
Hi @souenzzo, I can answer your question about the default window for `api-request-right-sizing`; it is `2d` by default. Adding this information to the documentation would be very helpful, so thank you for pointing it out!

Homogenous behavior between the `allocation` and `api-request-right-sizing` sounds like an excellent goal to have. A couple of questions that come to mind that could might be helpful if we were to think about adding it would be:
1. What would we set as the default window for the `allocation` API?
2. Is there an issue with that default being different from the `api-request-right-sizing` if the end goal is parity between how the APIs function (7d allocation, 2h api-request-right-sizing)?
3.

**Comment by kaelanspatel** [comment]
Just a guess, but I would assume the difference is because `request-right-sizing` generates a total savings number which can be more-or-less independent from the window, whereas `allocation` explicitly describes cost allocations over a window. 

To put it another way,  `request-right-sizing` generates an insight based on the window's data, while `allocation` describes the window itself (and it would therefore be less useful to put an arbitrary default on it).

**Comment by keithhand** [comment]
@souenzzo, were Kaelan and my answers enough to clear things up about this? If there is still some confusion, I'm happy to answer any additional questions you might have.

**Comment by keithhand** [comment]
@souenzzo, I just wanted to check in to see if I can mark this issue as resolved. Do you still have any clarifying questions? If you do, I'll work to answer them right away. If not, great! Just let me know, and I'll close this out.

**Comment by souenzzo** [comment]
@keithhand yes, i think that we can close this issue.
