### ISSUE TITLE
Support different OfferDurableId in cost model directly

### ISSUE THREAD

**Issue by juanjoselopezroldan** [kubecost/cost-model#1053]
We need change the OfferDurableId for cases that is need use other different to defined "MS-AZR-0003p".
Is possible change this value ? or You have already defined in your roadmap?

The possibility that we desired is we can change the differents types of Microsoft Azure Offer from settings of kubecost through text camp customized (https://azure.microsoft.com/en-us/support/legal/offer-details/)

gz#1347

**Comment by kbrwn** [comment]
@juanjoselopezroldan Can you provide little bit more information about your use case? For example do you need multiple different OfferDurableIds or do you have a different one that you would like to use in all cases? 

cc @Sean-Holcomb

**Comment by juanjoselopezroldan** [comment]
In my use case will be ideal that exist a text camp that permit me the possibility of indicate in this camp the differents types of Microsoft Azure Offer for that the request that do to azure is flexible and dynamic.

For example, we indicate the offerdurableid MS-AZR-0017G in the text camp and that in the backend do the request in the next URL:
"https://management.azure.com/subscriptions/SUBSCRIPTION-ID/providers/Microsoft.Commerce/RateCard?%24filter=OfferDurableId+eq+%27**MS-AZR-0017G**%27+and+Currency+eq+%27USD%27+and+Locale+eq+%27en-US%27+and+RegionInfo+eq+%27US%27&api-version=2015-06-01-preview"

Because in the actual case only is possible use the part of billing with Azure with the Offer Durable Id MS-AZR-0003p and is not possible change for other type of OfferDurableId.

**Comment by Sean-Holcomb** [comment]
The issue is here is that the pricing data gathered from that api informs our metric emission. The answer I am trying to get from you is whether or not you would want to switch back and forth between `MS-AZR-0017G` and `MS-AZR-0003p` or if you would switch to `MS-AZR-0017G` and leave it there.

**Comment by juanjoselopezroldan** [comment]
In my case would want to switch back and forth between both of them as i need it.

**Comment by Sean-Holcomb** [comment]
Unfortunately this request will not be possible as the results of the of this api are exclusively used for our metric emission loop. Changing the value of the durableId will not retroactively change the historic pricing data but only the node costs moving forward. 

That being said there are ways to make Kubecost more closely match your billing costs, have you tried using [this](https://guide.kubecost.com/hc/en-us/articles/4407595936023-Adding-Azure-Out-of-Cluster-Cluster-Costs-into-Kubecost)?

**Comment by juanjoselopezroldan** [comment]
Ok thanks for the info.
