### ISSUE TITLE
Add EKS service costs to cost model

### ISSUE THREAD

**Issue by mda590** [kubecost/cost-model#108]
AWS has an hourly cost for the EKS service itself - Azure and GCP do not.

If the provider=AWS and platform=EKS, then we should add this to the overall cluster costs. Seems like provider can be determined by the K8s version (for example: `v1.12.6-eks-...`).

**Comment by dwbrown2** [comment]
Completely agree. This brings up an interesting allocation question that is somewhat similar to #103. Namely, who pays for this cost...

I also like the idea of supporting both provider and platform. I'm not sure the best way to capture the latter, but on the surface your suggestion looks like a good one!

**Comment by dwbrown2** [comment]
@AjayTripathy and I discussed last week. He's actively working on part 1 of this, which is exposing the host "platform". We expect this to be in the next release. Thanks again for suggesting this!

**Comment by AjayTripathy** [comment]
#122 provides "management platform" information in the cost model

**Comment by dwbrown2** [comment]
This is now supported with an external key, but we are considering also adding it to the new `shared costs` field. Matt, let me know if you have any suggestions/preferences. Also, hope you are doing well :)

**Comment by AjayTripathy** [comment]
We have a custom field now called "shared overhead" that can be used to allocate management  costs.
