### ISSUE TITLE
prometheus-node-exporter daemon set not running 

### ISSUE THREAD

**Issue by sreekanth-ragi** [kubecost/cost-model#110]
Hi,

I just installed it using the steps at 
https://kubecost.com/install?ref=home

but I see that the node-exporter daemonset is not having any running pods, also my grafana also gives a message stating that 

If you're seeing this Grafana has failed to load its application files 

1. This could be caused by your reverse proxy settings.
2. If you host grafana under subpath make sure your grafana.ini root_path setting includes subpath
3. If you have a local dev build make sure you build frontend using: npm run dev, npm run watch, or npm run build
4. Sometimes restarting grafana-server can help

I can see the cost-analyzer ui but without node metrics it not fetching information related to CPU and memory. Could you provide pointers on where to start looking at.

Thanks,
Sreekanth

**Comment by dwbrown2** [comment]
Hi @sreekanth-ragi, a couple follow up questions to help get this solved:

1) What cloud provider and version of k8s are you running?

2) Are there any kubecost-prometheus-node-exporter pods deployed in your target namespace? Or are they deployed but do not have Running status? If they are not deployed then something went wrong with the helm install. Can you run the helm install command again with `--debug` to see if there are any errors?

3) What is the status of the kubecost-grafana pod? Can you share any logs available?

**Comment by sreekanth-ragi** [comment]
@dwbrown2 
Answers for your questions
1. Cloud provider is GCP and K8s version is v1.11
2. Nopes no node -exporter pods were deployed, I'm trying the debug step as we speak
3. Grafana is running but I deleted the project before I could grab the logs.

Will update on how the debug install goes and update back.

Thanks for your continued support

**Comment by sreekanth-ragi** [comment]
@dwbrown2 

I tired with debug and attaching the log file here. I still do not see node-exporter metrics.
[kubecostinstall.txt](https://github.com/kubecost/cost-model/files/3296757/kubecostinstall.txt)

**Comment by AjayTripathy** [comment]
Hi @sreekanth-ragi , a couple thoughts

* We've seen this behavior before if you have the node exporter pods installed by something else, or something else using the port that the node exported is configured to use. The default is 9100
* Can you perform an install and provide the kubernetes event log for the kubecost namespace?
* Can you provide the grafana pod logs?

**Comment by sreekanth-ragi** [comment]
@AjayTripathy 

I do have node exporter running as part of the default openshift-monitoring project. Is there a way I could use the same installation with Kubecost or modify kubecost in a way not to clash with default installation?

Sreekanth

**Comment by AjayTripathy** [comment]
Hi @sreekanth-ragi , you'll need to set up the Prometheus installation to scrape your existing node-exporter. If you're installing our prometheus, scrape configs can be added here:

https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/values.yaml#L65

Here's a sample:
- job_name: 'node'
  static_configs:
  - targets: ['localhost:9100']

It may already be running on this port for openshift-- I'm not sure. If it is, you won't need to add any additional scrape configs, and it's okay for the node-exporter pods to not be installed in the kubecost namespace. You can simply disable their installation entirely from our values.yaml by setting prometheus.nodeExporter.enabled: false in our values.yaml

**Comment by AjayTripathy** [comment]
If you've already got your own prometheus that you're trying to connect to kubecost, you can follow these instructions to use it instead: http://docs.kubecost.com/custom-prom.html

**Comment by sreekanth-ragi** [comment]
I'm trying with my custom prometheus, but I'm back to square one with my prometheus running on SSL but there seems to be no provision to provide TLS config or do we have one?

**Comment by dwbrown2** [comment]
@sreekanth-ragi my apologies, I thought I responded to this last week. We still have an [open issue](https://github.com/kubecost/cost-analyzer-helm-chart/issues/62) to create a sample TLS config. 

Is [this discussion](https://github.com/kubecost/cost-model/issues/77) helpful in the meantime? Let me know if we can get you anything else that might help.

**Comment by dwbrown2** [comment]
Hi @sreekanth-ragi, are you still struggling with this? Let me know if there are any updates.

**Comment by sreekanth-ragi** [comment]
@dwbrown2 

I was looking for the sample TLS config, I reviewed the other links but was not able to find it, am I missing something?

**Comment by AjayTripathy** [comment]
Hi @sreekanth-ragi we have a number of OpenShift users now and this seems to work. We’re also now offering support for OpenShift users in our paid product. Are you still dealing with this issue?

**Comment by dwbrown2** [comment]
Hi @sreekanth-ragi we not have lots of users running on OpenShift. I'm going to make this as closed unless there is an open issue with prometheus-node-exporter daemon set not running. Let me know if you have any questions.
