### ISSUE TITLE
Feature: replace single value label settings by list

### ISSUE THREAD

**Issue by sebastien-prudhomme** [kubecost/cost-model#114]
Hi,

As labels as not always standardized when using third parties manifests, using single value for labels in settings can be a limitation.

I suggest two things:

- convert single value to list of values, for instance `app` and`"app.kubernetes.io/name` for application labels

- to go further, allow type of labels to be fully dynamic, that is if i don't want to have `Team Label`, i can delete the setting, and if i want to have a `Location Label`, i can add it.

**Comment by AjayTripathy** [comment]
This sounds good to me.

**Comment by dwbrown2** [comment]
It sounds useful to me too!

**Comment by dwbrown2** [comment]
@nikovacevic would this be supported by default in the new aggregation API?

**Comment by nikovacevic** [comment]
@dwbrown2 Regarding the first point: no, I don't believe so, but it would be a relatively simple feature to add. Regarding the second point, that's agnostic to the aggregation API (unless I'm missing something) but I like the idea.

**Comment by dwbrown2** [comment]
@nikovacevic knocking out part one on the backend sounds like a great start! Will discuss part 2 with Ajay. 

@sebastien-prudhomme anything else that you suggest thinking about here?

**Comment by sebastien-prudhomme** [comment]
@dwbrown2 no new suggestion

**Comment by dwbrown2** [comment]
Part one of this is now done. I propose we open a new issue for part 2, which is just a frontend presentation question. @sebastien-prudhomme let me know if we can get you anything else.

**Comment by dwbrown2** [comment]
Both of these are now supported in our APIs + our business tier product! Thanks again for this feature suggestion. Let me know if we can get you anything else here, or if you have other requests. 

Marking as closed for now, but please feel free to reopen at any time.
