### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by thueske** [kubecost/cost-model#119]
Hey buddies!

We are currently testing KubeCost for our applications.

It would be essential for us to be able to export the individual costs of the namespaces as CSV.

Is such a function planned?

Many greetings

**Comment by dwbrown2** [comment]
Hey Tobias, we are discussing this! We've centered most of the discussion around our commercial product so far, i.e. exporting from our UI. 

Can you share more about how you would want to use this? Would other formats be useful, i.e. email or pdf?

**Comment by thueske** [comment]
We would like to use the CSV export for evaluations and import the data e.g. into Excel. I would also have to get the data via Prometheus, correct? Otherwise a REST-API would be exciting! But most important for us would be the CSV export for the time being.

**Comment by dwbrown2** [comment]
Thanks for sharing! The data table in our commercial product currently makes it easy to copy/paste directly into Excel. Does this not meet your needs though?

**Comment by dwbrown2** [comment]
This is now in progress and expected to be part of our next release!

**Comment by dwbrown2** [comment]
This is now released in [v1.32](https://github.com/kubecost/cost-analyzer-helm-chart/releases) and is available on the Cost Allocation page. @thueske let me know if you have any feedback or additional requests!

**Comment by thueske** [comment]
Cool, thanks! Will have a look.

**Comment by thueske** [comment]
Works as expected, thanks for that! @dwbrown2

A small but helpful optimization might be the correct output of the currency. Excel does not recognize the format "$1.16", even if it is formatted as currency. In order to recognize it correctly, the output as a number (e.g. 1.16), i.e. without the currency sign and with a comma, would be very helpful, because otherwise complex formulas have to be used.

**Comment by dwbrown2** [comment]
Thanks for this feedback! Removing the currency is straightforward, however it sounds like you want these cost figures localized too. We should open a bigger tracking issue for that because it likely has broader scope.

**Comment by dwbrown2** [comment]
@thueske currency symbols were removed in our build last week! Let me know if this is helpful.

**Comment by dwbrown2** [comment]
@thueske, let me know if you have any additional needs here. Feel free reopen at any time.

We also now have a JSON endpoint that provides all of this data: https://github.com/kubecost/docs/blob/master/allocation-api.md#aggregated-cost-model-api
