### ISSUE TITLE
Cleanup JSON parsing

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-model#13]
Because of the mixed data types in Prometheus vectors, the json parsing is hard to read. It also panics when unexpected results are returned from prometheus. See todos on line 655 https://github.com/kubecost/cost-model/blob/master/costmodel/costmodel.go#L655 and line 662
https://github.com/kubecost/cost-model/blob/master/costmodel/costmodel.go#L662

Also investigate other JSON parsers like https://github.com/tidwall/gjson to clean this up. Note that any JSON parser used cannot read the whole billing data result into memory, because it gets quite large.

**Comment by luisdavim** [comment]
I've been using gjson and it's pretty fast and easy to use. I'm pretty sure it can handle large sets of data without loading everything into memory. Take a look here https://github.com/tidwall/gjson/blob/master/README.md#performance

**Comment by AjayTripathy** [comment]
Took a closer look at gjson and I didn't see an obvious way to capture data from a buffered reader. Have you used gjson to stream data before?

**Comment by AjayTripathy** [comment]
We've done a decent chunk of refactoring of our query libraries and should now have better error handling here.
