### ISSUE TITLE
Memory usage  metrics

### ISSUE THREAD

**Issue by leonlau** [kubecost/cost-model#133]
Hi, 
Why does memory use take container_memory_working_set_bytes instead of container_memory_usage_bytes ?

Cadvisor metrics on pod memory usage.

container_memory_usage_bytes  : Current memory usage in bytes,including all memory regardless ofwhen it was accessed. 
container_memory_working_set_bytes :  Current working set in bytes.

**Comment by dwbrown2** [comment]
Hi @leonlau, thanks for the question. The `container_memory_usage_bytes` metric includes cached data that can be evicted in memory pressure scenarios. We use `container_memory_working_set_bytes` because this exclude cached data and is what Kubernetes uses for OOM/scheduling decisions.

I think this is a good [post](https://medium.com/faun/how-much-is-too-much-the-linux-oomkiller-and-used-memory-d32186f29c9d) on the subject.

**Comment by dwbrown2** [comment]
@leonlau did this answer help? Let me know if I can share more info.

**Comment by leonlau** [comment]
Thanks for your help, 
I used `container_memory_working_set_bytes` to calculate my memory usage.

Sorry, I didn’t reply you in time.

**Comment by dwbrown2** [comment]
Cool, let me know if we can help with anything else!

**Comment by qhh0205** [comment]
@dwbrown2 Hello, i hava a question about this issue. I found that Pod behind the Kubernetes service, the container_memory_working_set_bytes value of each pod is not balanced, there is a big difference between the values. So i want to know why that is not balanced and how to balanced, thx!

**Comment by dwbrown2** [comment]
Hi @qhh0205, thanks for the question. Can you provide a bit more context? What do you mean by balanced? Also, which exact pod are you referring to?

**Comment by qhh0205** [comment]
@dwbrown2  Thx for your reply,
For instance, this is the screenshot of prometheus which shows the Pod's container_memory_working_set_bytes of same kubernetes deployment. As screenshot below, the value of each Pod is not balanced. **So why the difference between the values is very large?** I checked the cpu usage, however the cpu usage is balanced, but memory is not balanced. So i am confused!
![image](https://user-images.githubusercontent.com/12775142/71610336-fc081e00-2bca-11ea-9137-fea1b4008b09.png)

**Comment by dwbrown2** [comment]
When you say "not balanced", do you mean why do different pods in the same deployment have different memory consumption?

**Comment by qhh0205** [comment]
@dwbrown2 Yes, why do different pods in the same deployment have different memory consumption.

**Comment by qhh0205** [comment]
@dwbrown2 Why do different pods in the same deployment have different memory consumption?

**Comment by dwbrown2** [comment]
This is going to heavily depend on the architecture of your deployment/application + how the OS allocates memory for you. It's not uncommon for applications that store some type of state to have wildly different memory consumption patterns. This particular metric is collected by [cadvisor](https://github.com/google/cadvisor) if you think there is an inaccuracy. Hope this helps!

**Comment by qhh0205** [comment]
@dwbrown2 thanks

**Comment by dwbrown2** [comment]
No problem, let me know if we can help in other ways!

**Comment by dwbrown2** [comment]
Closing because this should now be addressed! Please feel free to reopen if you have questions.
