### ISSUE TITLE
Should we be billing on completed jobs?

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-model#136]
Right now we still charge an allocation to completed jobs if they have resource requests. This was originally intended to encourage teams to clean up old jobs. Should we be doing this? 

Some questions to consider:

Do they block downscaling on some cluster autoscalers?
Does the k8s scheduler have to schedule around them?

**Comment by dwbrown2** [comment]
I agree that we should not be billing for these. PR in flight.
