### ISSUE TITLE
Prometheus gauge metrics being cached 

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-model#140]
There are certain cases where Kubecost Prometheus gauge metrics (e.g. container_cpu_allocation) are being cached after a pod is deleted. 

It's worth noting that this does not impact the Kubecost commercial product and only applies to the open source metrics.

**Comment by dwbrown2** [comment]
Testing this PR now: https://github.com/kubecost/cost-model/pull/141

**Comment by PetzJohannes** [comment]
I have tested the PR and there is still one metric cached.
`container_uptime_seconds` is still in the cache.
Is that the correct behavior?

**Comment by AjayTripathy** [comment]
Fixed by #141 and #142
