### ISSUE TITLE
Allocating shared resources

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-model#151]
Much like idle costs today, we want to distribute the cost of shared resources, e.g. kube-system pods, across all tenants. Essentially we will assign zero costs to these resources and then distribute the cost of all idle resources. Here are open design questions:

- Should this be enabled by default?
- How should we define/track these resources, e.g. by namespace? Should this be configurable? 
- Should these costs be distributed proportionately or by some weighted metric?

**Comment by dwbrown2** [comment]
We've discussed within the team and with a number of users. Initial proposal is that this will be disabled by default, allocation will be done by a user-supplied namespace list, and that shared resource cost will be distributed evenly across all tenants.

**Comment by soumeng09** [comment]
From our perspective, we'd like to - 
1. Have namespaces included in idle cost by labels (e.g. - all namespaces with label project=system)
2. It would be better if there is provision to allocate shared resource cost proportionately, i.e. based on total usage cost ratios

**Comment by dwbrown2** [comment]
Handling #2 should be straight forward. 

How big of a priority is #1? Would this just save you from having to type several more namespaces or is there other impact? I ask because most teams we are working with will want to use namespaces directly.

**Comment by AjayTripathy** [comment]
This is now done, and will be in our next release.
