### ISSUE TITLE
Support AWS EFS for PV Cost Tracking

### ISSUE THREAD

**Issue by dcherman** [kubecost/cost-model#159]
Hi,

Unlike EBS volumes where you're charged for the amount of space that you've provisioned, EFS has essentially unlimited space and you're charged for the volume of data that you're actually storing (the storage size request in a PV is essentially ignored).

At least for those volumes provisioned by the EFS provisioner, it has a reference to the EFS server and the path that the PV is bound to.  Can we consider detecting when the `storageClassName` is efs and inspecting the actual size of the folder in EFS to determine usage costs?

Since the server name contains the region in which the EFS volume is created, we should be able to look up the current pricing information for that region and do some simple math to come up with an accurate number.

**Comment by dwbrown2** [comment]
Very cool. Thanks for this proposal. We have not tested against EFS directly yet, or at least that I'm aware of. Do you know if k8s directly knows the size of data stored? Trying to understand if this would need a service key to get this data from AWS or if something in your cluster could be used to determine directly.

**Comment by dcherman** [comment]
As far as I know, k8s doesn't know the size of the data that's stored in an EFS PVC; it's also a non-trivial problem to solve since each PVC would need to be inspected independently, and that can be a very slow process.  I don't know if this is the most optimal way to do it, but using `du -sh` on a moderately sized folder (527MB, 23986 total files) yielded the following times on an EFS PVC:

```
real	0m54.411s
user	0m0.180s
sys	0m1.331s
```

With a large number of PVCs, the only reasonable way that I could imagine doing this is on a less frequent schedule (daily?) and by using a queue with an elastic number of workers to actually get stats on the PVC.

In addition to using a service key, we should also make sure that using either kiam/kube2iam or the new IAM Roles for Service Accounts features work to avoid needing to create access keys/secrets if possible.

**Comment by dwbrown2** [comment]
Interesting -- I would need to investigate but this definitely sounds like one solution. We need to start by provisioning an EFS disk for testing/exploration. 

Just curious, do you know what the `kubelet_volume_stats_used_bytes` Prometheus metric reports for these volumes? Is it non-sensical? 

Another option is to just get the cost directly from AWS billing data. That has the downside of coming with a time delay.

**Comment by AjayTripathy** [comment]
> Another option is to just get the cost directly from AWS billing data. That has the downside of coming with a time delay.

Just following up here. This is the option we went with :)

**Comment by relaxdiego** [comment]
> > Another option is to just get the cost directly from AWS billing data. That has the downside of coming with a time delay.
> 
> Just following up here. This is the option we went with :)

@AjayTripathy were you able to drill down the cost per Access Point (therefore by PV) or did you just use the aggregate cost of the entire filesystem?

**Comment by AjayTripathy** [comment]
each pv should have a resourceID that maps to a corresponding resourceID in the AWS cost and usage report.

**Comment by wolffberg** [comment]
By default the AWS Cost and Usage Reports do not contain information about per AP usage and will only contain the full EFS ARN.

It might be possible to infer the cost per AP using Cost Allocation Tags, but I haven’t tested this.
