### ISSUE TITLE
Labels not applied correctly 

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-model#163]
This API request `model/aggregatedCostModel?window=1d&aggregation=label&aggregationSubField=app` should return data but instead returns 

```
{"code":200,"status":"success","data":{}}
```

**Comment by AjayTripathy** [comment]
Appears to me that model/aggregatedCostModel?window=1d&aggregation=label&aggregationSub**f**ield=app returns data (emphasis mine). That being said, the API is inconsistent in that the json object returns aggregationSubField-- that is a quick fix.

**Comment by dwbrown2** [comment]
You're correct -- this was actually just a documentation error. We were showing `aggregationSubField` instead of `aggregationSubfield`.
