### ISSUE TITLE
Support different currencies in cost model directly

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-model#172]
The commercial product allows users to configure their "currency". Let's expose this functionality directly in the back-end.  This is a high priority requirement for one of our new users on Azure.

**Comment by mlushpenko** [comment]
https://github.com/kubecost/cost-model/blob/1de966aec9da22d2ce95f6467fb2275253b801ed/cloud/azureprovider.go#L329 this piece of code for Azure, probably has to be provider-specific logic, not sure if you can generalize it somehow.

In our case, this query gave us the right prices `OfferDurableId+eq+'MS-AZR-0036p'+and+Currency+eq+'EUR'+and+Locale+eq+'en-US'+and+RegionInfo+eq+'NL'`

Although [`0036p`](https://azure.microsoft.com/en-us/offers/ms-azr-0036p/) offer is the same as pay-as-you-go 

I wonder if you can get location/currency combo via some API or they have to be hardcoded data structures (or scraped from the webpage) 
![image](https://user-images.githubusercontent.com/2006610/66307672-54e65400-e905-11e9-81db-c7f9cf206d08.png)

**Comment by dwbrown2** [comment]
Thanks @mlushpenko! Ajay is beginning implementation today, will reach out if we have any questions

**Comment by dwbrown2** [comment]
The initial implementation of this feature was released in v1.45 earlier this week!
