### ISSUE TITLE
Cost model caching

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-model#173]
Let's start caching data so that backend response times are faster. My proposal is to start this with the aggregation api with the following goals:

* [P0] let's try to be really careful about not causing regressions. My suggestion is to keep v1 of this implementation simple and err heavily on the side of missing a cache hit vs returning wrong data
* Make cache short-lived, i.e. 2-5 minutes, but this is ideally configurable later
* Can keep a single cache when parameters match (e.g. byNamespace, timeWindow, offset) or cache for multiple aggregations (e.g. namespace, label, etc.)
* I think just starting with namespace caching could be easiest

**Comment by AjayTripathy** [comment]
We can start with a simple cache that just uses the url parameters on the [aggregateCostModel](https://github.com/kubecost/cost-model/blob/master/main.go#L205) endpoint as keys 
and invalidates based on a TTL. [go-cache](https://github.com/patrickmn/go-cache) seems to support something like this out of the box

I'd also suggest a parameter to disable the cache and a parameter to clear the cache for debugging.

Once that's working, as a later step we can think about what timeWindows we might want to precompute/how to warm up the cache.

**Comment by dwbrown2** [comment]
Marking this as closed, lots of great work here :)
