### ISSUE TITLE
Set default spot label for AWS

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-model#2]
It would be nice to not have to configure this for every cluster. I believe the node label for EKS is *lifecycle=EC2Spot* but worth verifying. If so, this seems like a sensible default to me.

**Comment by AjayTripathy** [comment]
https://github.com/kubecost/cost-model/blob/master/cloud/awsprovider.go#L139 should resolve this.

**Comment by AjayTripathy** [comment]
Fixed
