### ISSUE TITLE
$NaN prices after updating Spot Feed Configuration

### ISSUE THREAD

**Issue by K-DOT** [kubecost/cost-model#205]
I installed Kubecost v1.46.0 with Helm and after updating Spot Feed Configuration I get $NaN as Monthly Cost:
![Capture1](https://user-images.githubusercontent.com/7099354/67382279-44d5a200-f59e-11e9-8ffa-246bbabe9050.PNG)

In logs I can see:
```
1 router.go:117] Error returned to client: MissingRegion: could not find region configuration
```

Here's the configuration:
![Capture](https://user-images.githubusercontent.com/7099354/67382842-31770680-f59f-11e9-8422-57ab62382266.PNG)

Am I missing something?

**Comment by K-DOT** [comment]
Re-deploy helped

**Comment by dwbrown2** [comment]
@K-DOT, just wanted to confirm that you are good now? This data is actually delayed by ~1 hour from AWS so there's a chance it was time-based. We'll investigate further though. Thanks for reporting.

**Comment by K-DOT** [comment]
I waited a day. Before that I set custom price with empty value. Maybe it's related. I changed them to correct values afterwards, but it didn't help. Now everything is great, thank you.

**Comment by dwbrown2** [comment]
Glad to hear! I'll leave this open so we can investigate to make sure there's not a latent bug. Let me know if we can help with anything else.

**Comment by dwbrown2** [comment]
This has highlighted an issue. Specifically when an empty string is passed for a custom price, it gets stored as NaN. Thanks again for reporting.

**Comment by K-DOT** [comment]
Glad to help

**Comment by dwbrown2** [comment]
Marking as fixed because this should be addressed in v.148. Please feel free to reopen if we can get you anything else. Thanks again for reporting!
