### ISSUE TITLE
Disable Prometheus

### ISSUE THREAD

**Issue by IuryAlves** [kubecost/cost-model#213]
Is there a way to run kubecost without prometheus?

I am not talking about having my own prometheus instance, I would like to run kubecost without prometheus at all.

Is this a possibility or is prometheus required in order for kubecost to work?

**Comment by dwbrown2** [comment]
Hi Iury, what are you hoping to use for your historical pricing & utilization data store?

**Comment by IuryAlves** [comment]
Hello!

I was hoping to use Datadog. Not sure if it is possible.

We had prometheus in the past, but we have decommissioned it and moved everything to Datadogl

**Comment by dwbrown2** [comment]
Just curious, why is this important? Is there something specific you want to do with the data? And do you want to just write data to datadog, or both read and write? 

Our product today does support different data stores like this, but depending on your exact use case there may be integration support needed on our end.

**Comment by IuryAlves** [comment]
I appreciate that you are trying to understand my problem =)

We are trying to avoid using Prometheus. We already use Datadog for all metrics in our system and it seems too much to have prometheus only for cost related metrics.

**Comment by dwbrown2** [comment]
Got it! Thanks for sharing. Would you be looking to just write cost metrics into Datadog, or use Kubecost to both write to & read from Datadog?

**Comment by IuryAlves** [comment]
Both read and write.

Another example: We have Datadog agents forwarding metrics (cpu, memory) from hosts. After installing kubecost I noticed that there are prometheus node exporters doing a similar job.

**Comment by dwbrown2** [comment]
@IuryAlves, we support this use case on our enterprise plan today. Happy to discuss in more detail if you're interested!

**Comment by IuryAlves** [comment]
Hi @dwbrown2, glad to hear that.

Next week I will present to my team what kubecost can do, after that we can discuss the enterpise plan.
I will close this ticket for now. I think I can contact you by email to discuss the enterpise plan.

Thanks for your help.

**Comment by bharathiram** [comment]
@dwbrown2 I don't understand the dependency here. Why does the cost model software need a tight coupling with a monitoring system? It kills the point of this open-source project being vendor-neutral.

**Comment by dwbrown2** [comment]
@bharathiram the project has changed a lot since 2019. Running OpenCost (which didn't exist in 2019) today has a PromQL requirement to build the entire cost model. Most teams use Prometheus, another open source project, but there are many options. I don't see why having another open source dependency wouldn't make OpenCost vendor neutral but let me know if you think there are other approaches/solutions you think would be worth exploring.
