### ISSUE TITLE
Debugging AWS out-of-cluster configuration

### ISSUE THREAD

**Issue by J-Swift** [kubecost/cost-model#228]
Hi there, I'm really enjoying the project so far, thank you for having a reasonable public offering!

I'm trying to integrate AWS out-of-cluster pricing. I have gone through the steps outlined in http://docs.kubecost.com/aws-out-of-cluster.html, but it isn't being picked up (gave it a week to be sure) and I have no idea where the breakdown is. This ticket is twofold, a question and suggestion:

1) question - what should I be looking at to see why the costs aren't being picked up? I've gone through the steps in the link above, and I've filled in the AWS account ID, service key name, and service key secret in the "out of cluster configuration" section of the settings. I assume the other fields are default overrides (but was confused about this so it could use some explanation).
2) suggestion - it would help greatly if there was something similar to the "prometheus status" that gives feedback on what I am not doing / have not configured correctly.

Thanks in advance for any help you can provide!

**Comment by dwbrown2** [comment]
Thanks for reporting this, James! Greatly appreciate the feedback. 

When you load the Allocation page, you should see cost data available for External Costs when this integration is completed successfully. When it's not, you should see a Developer Console log like the example below.

```
Out of cluster cost not loaded: bigquery: dialing: google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: open /var/configs/key.json: no such file or directory
```
Another helpful step is to confirm that your S3 bucket is correctly receiving data. 

I completely agree that more insights/tests would be beneficial here. We'll start scoping out this work. 

Let me know if you have any immediate questions around logs. Anecdotally, we've seen a number of users leave off the S3 protocol, e.g. `s3://aws-athena-query-results...` from their bucket name. Hope this helps.

**Comment by J-Swift** [comment]
Appreciate the quick response @dwbrown2. That got me closer (the config I left off the settings page was indeed needed), but its now silently failing. It logs nothing but External Costs still show as 0. I purposely messed up the credentials and it is the same situation. No worries, I'm going to hold off for a bit on this piece until there is maybe a more robust solution in place for setting it up. 

Again, I appreciate the current offering, so please just take this as a +1 when deciding what to work next amongst your team. If you have any ideas/pointers on giving a PR for this, I'd be open to looking at it as time permits.

**Comment by dwbrown2** [comment]
Of course, we'll start investigating diagnostic/reporting improvements now. 

As a favor, would you be able to share output from your `outOfClusterCosts` API request on the Allocation page? The api request would look something like this:

```http://<you-service-address>/model/outOfClusterCosts?start=2019-11-3&end=2019-11-4&aggregator=namespace```

**Comment by dwbrown2** [comment]
Also, this data is cached for up to 5m so your bad configuration may not actually be failing silently.

**Comment by J-Swift** [comment]
Good point, I just came to the same conclusion : )

Got this working! Had to debug manually through AWS athena dashboard to read each failed query message (turns out AWS creds were right all along) and address issues as they came up. The ultimate issue ended up being that I had the wrong Athena table name and had to create an additional bucket (the csv output bucket, aka `aws-athena-query-results-*`), which its not clear to me when I would have done so when following the instructions.

So a couple takeaways:

1) Out of config updates should bust the cache and/or reload (from top right of UI) should ignore cache
2) Being able to surface the errors shown when viewing the Athena query history in the kubecost UI would be immensely helpful. I'm not sure if this is possible or not with the AWS api.
3) I think the out-of-cluster instructions or the code are missing something regarding creating the s3 bucket aws-athena-query-results. The IAM role definition says it can create the bucket (so I assume it would "just work" without manual bucket creation), but looking through the code it doesn't appear to try to do so, so I manually created it. Should the end user create it or should the go service do so?
4) As already stated, something similar to the really useful prometheus status would go a long way to narrowing down what remains to be fixed when setting this up.

Hope this helps your team / anyone else going through the process.

**Comment by dwbrown2** [comment]
James, this is incredibly helpful. Thanks so much for sharing. 

1. Completely agree -- work to change this is underway
2. Also agree -- we're investigating what's possible now
3. We'll clarify that manual bucket creation is needed
4. Great idea -- we'll see what we can get from 2) and look to create something here. 

All this feedback feels spot on to me -- thanks again! Anything else we can get you while we start making progress on this?

**Comment by J-Swift** [comment]
Haha, no you've been more than helpful. My out-of-cluster is all set now so I'm good, just hope to alleviate issues for future users / future me. Appreciate the responsiveness!

**Comment by AjayTripathy** [comment]
Many of these issues have been addressed on GCP but we're working on support for AWS. @J-Swift 
Anything else we can get you here?

**Comment by natefear** [comment]
When using the kubecost cost-model pod, I am able to perform AWS out of cluster cost queries via the http API but they do not run automatically? should the pod not run the AWS out of cluster queries automatically on startup (like it does for RI's) and then export them as prom metrics? Cheers, apologies if this is the wrong place to ask

**Comment by dwbrown2** [comment]
@natefear I know this occurs in the free version of available http://docs.kubecost.com/install, but I'm not sure about open source. Want to email team@kubecost.com and we can help find the right solution?

**Comment by natefear** [comment]
cheers @dwbrown2 I've contacted the kubecost support slack channel :)

**Comment by AjayTripathy** [comment]
Visiting "/diagnostics.html" should give a good idea about AWS configuration now.
