### ISSUE TITLE
Inaccurate network cost estimation on AWS

### ISSUE THREAD

**Issue by omerlh** [kubecost/cost-model#260]
Just looking at the costs on one of our namespaces, according to the cost model all the network costs is 308$, while when looking at AWS billing portal the number is a lot lower - for the entire account it's less than 100$. How can we help investigate it?

**Comment by dwbrown2** [comment]
@omerlh, it sounds like understanding #257 will help answer this... once you can look at network data, we can determine what pods/jobs are driving egress costs. You can also see their top IP addresses, from here you can whitelist an IP/CIDR if these are internal to your VPC.

**Comment by omerlh** [comment]
Now that #257 is resolved, we can get back to this issue. I compared two metrics for the same pod:
```
sum(rate(kubecost_pod_network_egress_bytes_total{pod_name="<>"}[5m]))
```
And
```
sum(rate(container_network_transmit_bytes_total{pod_name="<>"}[5m]))
```
For the same pod in the same time. While the first return 10223.36842105263, the seoncd one (which is reported by cadvisor) return a lot smaller value 905.1541006114268. I guess this is the reason for the difference...

**Comment by dwbrown2** [comment]
I would need to learn more about this particular pod to give an answer. This delta could be caused by 1) the fact that daemonsets share IP addresses or 2) sample rate differences or 3) something else. Do you see differences across all pods or just this one? 

Our data comes directly from the [conntrack](https://serverfault.com/questions/540760/what-does-nf-conntrack-acct-really-do) kernel module so it seems unlikely that it would be outright wrong but it's possible. Let me know if you can share more information. Looking at dest IP addresses could also be a good way to understand what is accounting for most of the traffic.

**Comment by omerlh** [comment]
Here is another example:
Kubecost - 28942058.33333333

CAdvisor - 10296.636032957646

It's not only one specific pod... something is weird...

**Comment by dwbrown2** [comment]
We have a number of integration tests / simulations but can't seem to recreate this issue... is there any more contextual information you can share? For example, how do these two metrics change with respect to each other over time? Are all pods impacted? If not, is this limited to a certain namespace or type of pods (e.g. jobs, deployments, or daemonsets)? 

While `container_network_transmit_bytes_total` uses a different method to track network traffic, we do not expect these metrics to be this different.

**Comment by omerlh** [comment]
This looks very weird when looking at the entire cluster:

![image](https://user-images.githubusercontent.com/6730584/71818110-b77bf700-3090-11ea-9711-94017b0c5590.png)

I guess there is something I'm missing here...

**Comment by dwbrown2** [comment]
We found a scenario where the configuration of conntrack expiration may be impacting data collection. Investigating and also working on a fix now. We will follow up shortly. Thank you again for much for reporting all of this detail.

**Comment by dwbrown2** [comment]
@omerlh, we just pushed v10 of `kubecost-network-costs`. It's available now in our helm repo. This release now handles this different conntrack expiration configuration. We expect you will see declines in Kubecost network bytes. Can you let us know if this update resolves your problem? 

Note: there are several areas where cadvisor, i.e. container_network_transmit_bytes_total, may still differ. The biggest area being that their data from netstat can overcount daemonset traffic.

**Comment by omerlh** [comment]
Yes, it looks a lot better now, thank you!

How do you decide if a request is cross-region (but still in AWS) or going outside to the internet? I can see requests that should be cross-region marked as internet

**Comment by dwbrown2** [comment]
Glad to hear! Thanks for helping us catch this. Here's a brief description on classifications:

https://github.com/kubecost/docs/blob/master/network-allocation.md#kubernetes-network-traffic-metrics

Happy to investigate a particular issue if you feel there is one, or you can use whitelisting (as described in that doc) for IPs that you know are not internet egress.

**Comment by AjayTripathy** [comment]
Looks like this is addressed. Let us know if you have other questions.

**Comment by omerlh** [comment]
Hey, looking again into this today - notice this in one of our pods:
![image (7)](https://user-images.githubusercontent.com/6730584/74835965-1aff7280-5327-11ea-81fe-2cdf7a4f1a12.png)

All the IPs here are pod IPs in the same cluster, but some are recognized as "In Zone", and some as N/A. Why is that?

**Comment by dwbrown2** [comment]
Hi @omerlh is this happening on our latest release or an older version? I don't clearly see how it would be occurring on latest: v1.52.2. If you're on an older version, do you mind upgrading and confirming?

**Comment by omerlh** [comment]
We just updated last night, now things looks a bit better:
![image](https://user-images.githubusercontent.com/6730584/74909889-ea204b80-53c1-11ea-99d0-a27b36065727.png)

But this time the first 3 IPs (marked as Internet) are internal IPs: the first one is on Azure (cluster running on AWS, peered to Azure, so I guess this is right) and the other 2 are IPs on the other cluster (in another AWS region) - so it should be marked as "cross-region".

**Comment by dwbrown2** [comment]
Just to clarify, are the latter two IPs that you mention on an AWS cluster that is different from the one you have Kubecost deployed on? If so, you can whitelist them in order to no longer classify as internet egress: 

https://github.com/kubecost/docs/blob/master/network-allocation.md#whitelisting-internal-addresses

**Comment by omerlh** [comment]
But they should be marked as cross region traffic - is that possible?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dwbrown2** [comment]
I like this idea, but based on what I'm hearing it would be a feature request! Let me discuss with the team next week...

Just to clarify: the idea would be that when you whitelist an IP/CIDR you could also classify that whitelisted item. Today everything defaults to same region / same zone. 

Does that meet your needs? Or would something else be better?

**Comment by omerlh** [comment]
Yeah, exactly. How do you recognize cross-zone traffic today?

**Comment by dwbrown2** [comment]
Our network service builds a map of all endpoints/IP within your cluster. When bytes are sent to a destination region/zone combination that do not match the source, then they are considered cross-zone/region.

We will discuss this feature request for handling out of cluster/whitelisted traffic this week!

**Comment by omerlh** [comment]
But if internal IPs does not consider as cross-region, what do consider so? Will that work only if the cluster is spread cross-region?

Thanks! Looking forward to see it :)

**Comment by dwbrown2** [comment]
How would we know if a random IP outside of the cluster is cross-region or internal without you giving us this information or getting it from k8s/cloud provider?

**Comment by omerlh** [comment]
That’s what I’m asking :) how the feature support to work without this config

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dwbrown2** [comment]
It's used today with cross-region / Federated clusters.
