### ISSUE TITLE
EKS: Erroneous warning about replicated masters

### ISSUE THREAD

**Issue by geekdave** [kubecost/cost-model#262]
Per the EKS docs: https://aws.amazon.com/eks/features/

> Amazon EKS runs the Kubernetes control plane across three Availability Zones in order to ensure high availability, and it automatically detects and replaces unhealthy masters.

However when running Kubecost on an EKS cluster, I get the health warning: `Cluster does not have replicated masters`.

Is it possible to suppress this warning on managed control planes like EKS?

**Comment by dwbrown2** [comment]
Thanks for reporting, Dave. This should be correctly picked up in an EKS environment. It may be a versioning issue. Is there any chance you can provide the output to this command and we'll get it resolved? Thanks again for your help.

```
kubectl get nodes -o json | grep -E 'providerID|kubeletVersion'
```

**Comment by geekdave** [comment]
Thanks @dwbrown2 !  Here's the output:

```
➜  ~ kubectl get nodes -o json | grep -E 'providerID|kubeletVersion'
                "providerID": "aws:///us-west-2d/i-0bcb84ce6cdba745f"
                    "kubeletVersion": "v1.14.7-eks-1861c5",
                "providerID": "aws:///us-west-2b/i-0332713d9389bc83a"
                    "kubeletVersion": "v1.14.7-eks-1861c5",
                "providerID": "aws:///us-west-2c/i-0016b9b97950b746d"
                    "kubeletVersion": "v1.14.7-eks-1861c5",
```

**Comment by dwbrown2** [comment]
Great, thank you! We will look to reproduce now.

**Comment by dwbrown2** [comment]
Found the issue and working on a fix now! Expected to be resolved in our next release. I'll follow up on this thread for verification.

**Comment by dwbrown2** [comment]
Dave, this should be addressed in our 1.50.1 release yesterday! Let me know if everything looks good for you and/or if we can get you anything else.

**Comment by geekdave** [comment]
@dwbrown2 Confirmed, the check is passing now.  Thanks for the quick turnaround!  Really enjoying using kubecost so far!

**Comment by dwbrown2** [comment]
Of course and glad to hear! Feel free to send us any feature requests or anything else we can help with.
