### ISSUE TITLE
missing namespaces

### ISSUE THREAD

**Issue by omerlh** [kubecost/cost-model#265]
I deployed KubeCost with my own Prometheus setup. I pretty sure I configured everything correctly, but still - when looking at the UI (for example, at the allocation view), it seems that KubeCost is seeing only 2 namespaces and not all of them. What can I check? Maybe something with Prometheus labels is misconfigured?

**Comment by omerlh** [comment]
This happened because of labels collision on Prometheus - the scrape `namespace` label override the exported `namespace` label from the job. Setting `honor_labels: true` solved the issue.

**Comment by dwbrown2** [comment]
That's what I suspected! Glad to hear you got it resolved.
