### ISSUE TITLE
Multi-cluster prometheus support

### ISSUE THREAD

**Issue by omerlh** [kubecost/cost-model#268]
When monitoring multiple clusters with the same prometheus (with Thanos, Cortex or Federation), there is usually a label that can be used to select metrics for a given cluster. It seems that cost-model does not support such a configuration, so we can't connect it to such a Prometheus - which also usually handles long term storage of metrics data. 

Proposed solution - either provide the label and let cost-model discover clusters dynamically (best), or let to specify the cluster label and value per cost-model deployment.

**Comment by dwbrown2** [comment]
Hi Omer, this exact functionality, with support for Thanos and other options, is part of our enterprise product. I can follow up with more information in our email thread if that would be helpful.

**Comment by omerlh** [comment]
I’ve sent you an email, let’s take it offline :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dwbrown2** [comment]
Marking as close due to our email thread. Feel free to reopen at any time with questions though!
