### ISSUE TITLE
Add more data to /metrics endpoint

### ISSUE THREAD

**Issue by luisdavim** [kubecost/cost-model#27]
Is this by design? I was expecting to get all the cost metrics from the `/metrics` endpoint.

**Comment by dwbrown2** [comment]
We started with just `total_node_cost`, `cpu_cost`, and and `ram_cost` as the initial set of metrics available to Prometheus. We're absolutely open to expanding this set. Are there specific metrics you would want to see?

**Comment by luisdavim** [comment]
Nothing specific, all of them ;)

**Comment by luisdavim** [comment]
By the way,  these node costs, are they relative to the node running the cost-model pod or is it an aggregate of all nodes?

**Comment by dwbrown2** [comment]
And we must get all of the metrics! :) How about are there any metrics that are more valuable than others to you? As context, we have been actively debating if we should write the entire model (w/ pod resource calculations included) or just resource cost data to the `/metrics` endpoint.

**Comment by dwbrown2** [comment]
Node costs in the open source product are based on the price of the current node. Most teams we have worked with use deployments so isn't common for the same pod to have run on multiple nodes. That being said, the data being written to `/metrics` allows you to track pods across different nodes over time. I think we should have this default available in this project. Let me know what you think.

**Comment by luisdavim** [comment]
Actually, I'd be happy with just higher level metrics for the metrics endpoint. Things like node costs, cluster cost and workload cost. And maybe a namespace break down.

**Comment by dwbrown2** [comment]
That's helpful. It sounds like there is a lot more we can expose here. We can start investigating the best way to do this with flexibility.

Are there specific queries or analysis that you want to complete with these metrics? I just want to make sure that as we start exposing more information it will support what you want to do.

**Comment by luisdavim** [comment]
Yes, I'd be interested mostly in cost per namespace and per service. And there are some labels that we assign to namespaces that I'd like to use to aggregate costs.

**Comment by luisdavim** [comment]
The higher level metrics I've mentioned before would be useful for capacity planning, with node cost, workload cost and total cluster cost we could make adjustments to the instance types and cluster seizes.

**Comment by dwbrown2** [comment]
Got it! We've started discussing the right approach. Is it fair to say that this feature would be nice to have before #28 ? It might even be a prerequisite based on what you've shared.

Let me know if you want to be involved in design and/or implementation! :)

**Comment by dwbrown2** [comment]
Also, is it ok if we rename this issue to something like "Add more data to /metrics endpoint"

**Comment by luisdavim** [comment]
Sure. Regarding the priority in relation to #28, it's totally up to you. 

Thanks for being so helpful

**Comment by dwbrown2** [comment]
I gave this some thought over the weekend, and I believe we can give Luis a lot of what he wants with two additional metrics. My initial proposal is below. This would allow relatively simple Prometheus queries to calculate total node costs, namespace cost, workload cost, etc. I vote we look at getting these added quickly and then see what other metrics/labels we can provide.

**RAM Allocation Metric**
container_memory_allocation_bytes {container,pod,namespace,node}

**CPU Allocation Metric**
This feels trickier. I really worry about using a rate() metric because of losing time window flexibility, but maybe we could do this with timeWindow == scrapeInterval. Alternatively, I think should just increment a seconds_total counter that a rate() can be applied to.

**Comment by luisdavim** [comment]
Sounds good.  I've been thinking, and started experimenting. What if we had a prometeus exporter that gets the data from the cost model api?

**Comment by AjayTripathy** [comment]
@luisdavim the `/metrics` endpoint with the new data that @dwbrown2 proposed would act as a Prometheus Exporter with the cost model data. You would just need to give Prometheus the scrape configs for this. We could provide an example on how to do this if it would be helpful. Does that help or is there something else you would be looking for?

**Comment by luisdavim** [comment]
That helps. What I was talking about was decoupling these into separate components. But if generating the extra metrics for prometeus comes without extra cost it probably makes sense to keep them together.

**Comment by AjayTripathy** [comment]
#38 starts adding cost allocation data to the metrics.

**Comment by dwbrown2** [comment]
I've also created a first version of documentation for these new metrics:

https://github.com/kubecost/cost-model/blob/master/PROMETHEUS.md

**Comment by dwbrown2** [comment]
Let us know if there are other immediate needs that you have here. 

The only potential addition that I might propose at this point would be creating some type of `container_cpu_cost` and `container_memory_cost` metrics, which would be the product of `allocation` and `price` metrics as they stand today.

**Comment by luisdavim** [comment]
yes, that would be useful.

**Comment by dwbrown2** [comment]
Cool, let's let these initial metrics soak while I give this some thought. We could potentially just provide a `container_total_houly_cost` instead of individual ram and cpu metrics, depending on target use cases.

**Comment by dwbrown2** [comment]
Naming feels tricky here. Other options are `container_cost_hourly` and `container_cost_irate_hourly`.  

Specifically this would be the hourly run rate based on the recently measured allocation and price.

**Comment by dwbrown2** [comment]
Let's go ahead and add `node_gpu_hourly_cost` as well now that teams are using this information.

**Comment by dwbrown2** [comment]
We've added all the basic metrics from the kubecost model. Any other requests?

If there are no immediate needs, then I would propose we close this in favor of specific requests/issues going forward.
