### ISSUE TITLE
Use annotations for teams

### ISSUE THREAD

**Issue by acarsercan** [kubecost/cost-model#271]
Hi,

We make use a lot of helm charts and most of them only allow to set Annotations and not Labels for the deployments. 

In kubecost we would like to make use of Team Label setting to split the cost between teams however it only seems to accept Labels as per name.

Regards

**Comment by dwbrown2** [comment]
Thanks for reporting! We used to support exactly this but found that most weren't relying on annotations for allocation. @AjayTripathy for his input.

@acarsercan, what's the impact/priority of this for you? 

Also, a potential work around in the meantime is to give the namespace a Team label and it will be applied to all workloads/Helm resources in that namespace. Is this a potential solution for you?

**Comment by acarsercan** [comment]
Thank you for the reply.

I'm making great use of team labels, however it seems some of the popular public helm charts do know understand labels at the moment but do provide values to set annotations (ie fluentd). Obviously I should contribute to improve the chart in question, but for now I was trying to work around it.

I will close it for now

**Comment by dwbrown2** [comment]
Sounds good, please feel free to re-open if we can get you anything!
