### ISSUE TITLE
Suggestion: Merge NameSpace labels into the labels list

### ISSUE THREAD

**Issue by luisdavim** [kubecost/cost-model#28]
In multitenant clusters it's common to have namespaces per tenant and to use labels in the namespaces to identify the tenants.

**Comment by luisdavim** [comment]
We label our namespaces with stuff like team, owner, cost centre, etc... Some times a team or a cost centre has multiple namespaces and it would be nice to have a aggregated view on those.

**Comment by dwbrown2** [comment]
This is helpful. Agreed this would be helpful to include. To clarify, you use kubernetes labels and not annotations for this?

There would be a possibility of a label conflict, e.g. owner label applied to namespace with a different owner applied at the pod-level. Maybe we should respect the most granular option (e.g. pod in this case). Any thoughts?

**Comment by luisdavim** [comment]
I think that in the case of a conflict, the pod label should prevail as it is more specific.

**Comment by dwbrown2** [comment]
I vote we make progress on #27 and then address this. Let me know if anyone feels differently.

**Comment by AjayTripathy** [comment]
I agree that this would be useful. Let's send it back on the cost model API as a separate field so we don't lose the provenance of the label on the frontend. Merging/conflicts can be handled by the user of the API (and in the Kubecost product).

**Comment by dwbrown2** [comment]
@luisdavim this data should now be available in latest as namespaceLabels! Does this support what you're looking to do?!
