### ISSUE TITLE
Network data missing on certain time windows

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-model#298]
It appears that when step window (e.g. 1 day on 30 day queries) is greater than the length of time  network cost metrics have been collected within this window we can drop all record of costs.

**Comment by nikovacevic** [comment]
Should be fixed by https://github.com/kubecost/kubecost-cost-model/commit/80d0bb0edb21ec4dbd7ac6e702e0e55fd1c47d40#diff-3629ed8bf50cd8d09094600b495cb570R1053
