### ISSUE TITLE
Helm chart - include option to install RBAC permissions

### ISSUE THREAD

**Issue by botzill** [kubecost/cost-model#32]
Hi.

I see that RBAC options are installed separately. Why not add them into the helm chart and add an option to enable disable it? A similar example can be found here: https://github.com/helm/charts/blob/master/stable/kubernetes-dashboard/values.yaml#L124. 

Let me know if you plan to add this or there is a way to add a PR for it. 

Thx.

**Comment by dwbrown2** [comment]
@AjayTripathy knows this piece much better, but I believe this is included in the Helm template below:

https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/templates/cost-analyzer-cluser-role-template.yaml

I think only the bootstrapping RBAC roles live outside of the Helm chart today. I do see the appeal to giving users the ability to configurable the chart's permissions (i.e. disable). 

*The ClusterRole that I referenced applies to only the kubecost.com project today, and not this open source project.

**Comment by AjayTripathy** [comment]
@botzill  can you clarify what you mean by RBAC installed separately? Do you mean the bootstrapping permissions listed at kubecost.com/install, ie providing a switch for the chart to do 
` kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=<your-userid>`

`kubectl create clusterrolebinding cluster-self-admin-binding --clusterrole=cluster-admin --serviceaccount=kube-system:default`
 
on your behalf?

 Like @dwbrown2 mentioned, once you've bootstrapped, all app privileges should be bundled with chart and default enabled.

**Comment by botzill** [comment]
@AjayTripathy yes. But now I see https://github.com/kubecost/cost-analyzer-helm-chart/tree/master/cost-analyzer/templates and it seems that already are included roles, 
 and clusterrolebinding, So, I didn't saw this part and now that I see seems that all is good, sorry for the confusion.

**Comment by dwbrown2** [comment]
No worries at all @botzill! Let us know if there is anything else we can get you related to RBAC or otherwise.

I'm going to close this for now, but please feel free to reopen for further discussion.
