### ISSUE TITLE
Add instance-type to Kubecost node metrics 

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-model#330]
The new e2 and other partial nodes incorrectly report having a full CPU in GKE. To address this, we propose adding the instance-type label to our Prometheus metrics. 

GCP:
beta.kubernetes.io/instance-type: n1-standard-2
AWS:
beta.kubernetes.io/instance-type: t2.micro
Azure:
beta.kubernetes.io/instance-type: Standard_B2s

Alternatively, we could get this information in a join.

**Comment by dwbrown2** [comment]
@AjayTripathy this is just on `node_total_hourly_cost`?

**Comment by dwbrown2** [comment]
Bolt, let's discuss a potential part 2 of this.

**Comment by mbolt35** [comment]
Fixed in https://github.com/kubecost/cost-model/pull/333
