### ISSUE TITLE
hostNetwork pods inaccurate network cost

### ISSUE THREAD

**Issue by shaikatz** [kubecost/cost-model#335]
Hi,

When having multiple `hostNetwork: true` pods in the cluster the network cost is inaccurate.
When viewing one of those pods like `kube-proxy` I can see network traffic related to other `hostNetwork` pods.

Looking at the logs I can see that:
```
I0219 13:37:55.786811       1 networktrafficlogger.go:77] [some-pod-9d7d6dc9b-2lbhr]
I0219 13:37:55.786814       1 networktrafficlogger.go:80]   -> Dest: SOME-IP, [RZ] Total Bytes: 8500570, Total GB: 0.01
I0219 13:37:55.786817       1 networktrafficlogger.go:81]      [kube-proxy-2k7lx,kubecost-network-costs-84shh,fluentd-ds72z]
```
You can see that it sees multiple pods on the same IP, and this is probably why they all being calculated together.

**Comment by dwbrown2** [comment]
Hi @shaikatz, Kubecost today evenly splits traffic from any shared IP pods. It's a known issue referenced here: https://github.com/kubecost/docs/blob/master/network-allocation.md#feature-limitations

Is that what you mean by inaccurate or are you referencing something else?

**Comment by dwbrown2** [comment]
@shaikatz just wanted to follow up on this to see if I can provide additional info. Anything I can get you here?

**Comment by shaikatz** [comment]
That answers my question, thanks.

**Comment by gautamabhishek46** [comment]
Are we planning to fix this limitation ?

**Comment by AjayTripathy** [comment]
This is a bit beyond the scope of opencost, but a lot of this has been fixed by the reconciliation of network costs available in Kubecost
