### ISSUE TITLE
Errors with sample Prometheus queries

### ISSUE THREAD

**Issue by infa-ddeore** [kubecost/cost-model#342]
I am following https://github.com/kubecost/cost-model/blob/master/PROMETHEUS.md
prometheus is scraping the cost-model metrics but 2 queries from this link give error:

Query 1:
```
topk( 5, 
  container_memory_allocation_bytes* on(instance) group_left() node_ram_hourly_cost  / 1024 / 1024 / 1024 * 730
  + 
  container_cpu_allocation * on(instance) group_left() node_cpu_hourly_cost * 730
)
```

error:
```
Error executing query: found duplicate series for the match group {instance="10.14.8.124:9003"} on the right hand-side of the operation: [{__name__="node_ram_hourly_cost", endpoint="cost-model", exported_instance="ip-10-14-10-49.us-west-2.compute.internal", instance="10.14.8.124:9003", job="cost-model", namespace="cost-model", node="ip-10-14-10-49.us-west-2.compute.internal", pod="cost-model-6565bcd685-cgpv5", service="cost-model"}, {__name__="node_ram_hourly_cost", endpoint="cost-model", exported_instance="ip-10-14-10-107.us-west-2.compute.internal", instance="10.14.8.124:9003", job="cost-model", namespace="cost-model", node="ip-10-14-10-107.us-west-2.compute.internal", pod="cost-model-6565bcd685-cgpv5", service="cost-model"}];many-to-many matching not allowed: matching labels must be unique on one side
```

Query 2:
```
sum(
  container_memory_allocation_bytes{namespace="default"} 
  * 
  on(instance) group_left() node_ram_hourly_cost  / 1024 / 1024 / 1024
) by (namespace)
```

error:
```
Error executing query: found duplicate series for the match group {instance="10.14.8.124:9003"} on the right hand-side of the operation: [{__name__="node_ram_hourly_cost", endpoint="cost-model", exported_instance="ip-10-14-10-49.us-west-2.compute.internal", instance="10.14.8.124:9003", job="cost-model", namespace="cost-model", node="ip-10-14-10-49.us-west-2.compute.internal", pod="cost-model-6565bcd685-cgpv5", service="cost-model"}, {__name__="node_ram_hourly_cost", endpoint="cost-model", exported_instance="ip-10-14-10-107.us-west-2.compute.internal", instance="10.14.8.124:9003", job="cost-model", namespace="cost-model", node="ip-10-14-10-107.us-west-2.compute.internal", pod="cost-model-6565bcd685-cgpv5", service="cost-model"}];many-to-many matching not allowed: matching labels must be unique on one side
```

is there any change needed in the query?

**Comment by dwbrown2** [comment]
@infa-ddeore this appears to be caused by an internal AWS node name change. You can handle with the following change:

```
sum(
  avg(container_memory_allocation_bytes{namespace="default"}) by (instance)
  * 
  on(instance) group_left() avg(node_ram_hourly_cost) by (instance)  / 1024 / 1024 / 1024
) by (namespace)
```

Let me know if this works for you!

**Comment by dwbrown2** [comment]
Hi @infa-ddeore, was that example query helpful?

**Comment by infa-ddeore** [comment]
I tried the trial version so I am good with it now but to answer your question the query results no data, it seems to be wrong, you are getting `container_memory_allocation_bytes` only from `default` namespace and only by `instance` so all other labels are removed, and the result is then list by `namespace`, nothing comes because there is no `namespace` label.

did you try this query in your env?

![image](https://user-images.githubusercontent.com/39782583/76278760-69fb5080-62b2-11ea-9c38-277314290858.png)

**Comment by dwbrown2** [comment]
Glad to hear you are good! 

This query works in one of our test environments. It is just meant to be a reference. You would need to change namespace from `default` if you do not have workloads in that namespace.

**Comment by infa-ddeore** [comment]
I don't think removing or changing namespace from `default` to something else will work.

I really wonder how the query is running in your env, query is clearly saying `by (instance)` means the the result is coming only with `instance` label and then how doing `by namespace` will work

but anyways, i am closing this bug, there isnt a working solution yet but i dont need that now.
