### ISSUE TITLE
Network analyzer - high CPU usage

### ISSUE THREAD

**Issue by omerlh** [kubecost/cost-model#343]
Is there expected CPU usage for the network analyzer pods? I noticed very high usage:

![image](https://user-images.githubusercontent.com/6730584/75179143-20532780-5742-11ea-8b7c-53ec7631cf4a.png)

I noticed some of the pods use almost 200% of the requests, which is high (150 mcore). Is this expected?

**Comment by dwbrown2** [comment]
@mbolt35 

@omerlh CPU usage is a function rows in your conntrack file (i.e. unique src/dest combinations) so it's hard for us to comment without learning more. 

That being said, I would not consider these figures to be abnormally large if you are on a pretty active cluster. You can always consider lowering the CPU limit if this is causing capacity issues for you.

**Comment by omerlh** [comment]
No, the pod just throttled because it needs more CPU than what it requested. I would like to know if it's safe to ignore it or I should increase the CPU request/limit.

**Comment by dwbrown2** [comment]
@omerlh to answer your question with a high degree of accuracy we would need to learn more about your infrastructure. resource usage will scale with the number of dest IP/port combinations.

That being said, it should not be a problem for the pod to be throttled like this.

**Comment by omerlh** [comment]
Great, I’ll remove the alert ☺

**Comment by dwbrown2** [comment]
Sg, I'll mark this as closed but follow up if we can help with anything else!
