### ISSUE TITLE
PV cost unexpectedly high for OpenEBS volumes

### ISSUE THREAD

**Issue by immusk** [kubecost/cost-model#363]
https://github.com/kubecost/cost-model/issues/263#issuecomment-592294025

@dwbrown2 as mentioned in the above 
I have updated my kubecost to latest version 1.53.1 which you has specified, but still I am getting the same costs.

I have tested on both aws and azure , I am seeing same higher costs being displayed.

**Comment by dwbrown2** [comment]
Hi @immusk thanks for reporting this. We addressed an Azure PV issue in v1.53.1. 

On AWS+Azure, can you please take a picture of the `/audit.html` page (example below). This will help us understand if you are hitting an issue. Also, can you confirm what region your disks are in?

![image](https://user-images.githubusercontent.com/298359/75570959-144eba80-5a0d-11ea-890f-ccbe66b98b35.png)

**Comment by dwbrown2** [comment]
@mbolt35 @AjayTripathy

**Comment by immusk** [comment]
@dwbrown2 @mbolt35 @AjayTripathy 
Please find the below screen shots of audit pages for azure and aws.
And I see that cost here look good, but on main page it is showing different costs.
azure
=====
<img width="1259" alt="Screenshot 2020-03-01 at 11 11 34 AM" src="https://user-images.githubusercontent.com/8833971/75620355-07b59800-5bae-11ea-8c85-3e2f0d90eced.png">

aws
====
<img width="1100" alt="Screenshot 2020-03-01 at 11 17 29 AM" src="https://user-images.githubusercontent.com/8833971/75620414-ae9a3400-5bae-11ea-833e-2dc07ccafea2.png">

**Comment by dwbrown2** [comment]
Hi @immusk we pushed another minor release for you over the weekend. This should resolve any discrepancies with Azure pricing. Note that the fix by default will only adjust prices going forward. 

re: AWS, we actually added additional data to the audit for you... would you be able to send a screenshot with the totals included at the bottom?  

![image](https://user-images.githubusercontent.com/298359/75709951-8a0a8e80-5c78-11ea-94ae-0cc4d2b1a260.png)

**Comment by immusk** [comment]
@dwbrown2 I have updated with version 15.3.2, on both aws and azure, but still the pvc cost is showing huge as earlier, I dont see any difference in it.
please find the below screen shots which you have asked for.
aws
====
<img width="1234" alt="Screenshot 2020-03-03 at 6 37 55 PM" src="https://user-images.githubusercontent.com/8833971/75779179-2b7c0800-5d7f-11ea-8b7d-248ab13ac6e6.png">

azure
=====
<img width="1005" alt="Screenshot 2020-03-03 at 6 41 57 PM" src="https://user-images.githubusercontent.com/8833971/75779207-36cf3380-5d7f-11ea-9043-10e64f53301f.png">

can you please fix this.

**Comment by dwbrown2** [comment]
How/what are you actually paying for these openebs volumes? Given that this is not standard storage we may need to make further changes to support.

**Comment by immusk** [comment]
these openebs volumes are aws EBS disks which are attached to EC2 instances.

**Comment by dwbrown2** [comment]
Ok, I believe that this storage class may be getting classified as premium/ssd. Would you be able to email or share this respective image? Looking at 1d cumulative spend by namespace. I'm trying to determine if this is limited to small set of disks/namespaces or all are higher than expected. Once we determine this it should hopefully be a quick fix.

![image](https://user-images.githubusercontent.com/298359/75847206-638d4600-5d93-11ea-889c-5c51379d87a0.png)

**Comment by immusk** [comment]
@dwbrown2 I have sent you the screenshots over email.

**Comment by dwbrown2** [comment]
Thanks, @immusk. It does appear that you are being billed at standard EBS gp2 pricing, which is the default. https://aws.amazon.com/ebs/pricing/

What is being used as the underlying storage class for these openebs volumes? Maybe you can share an example storage class to help us understand how you are managing this mapping? Output from `kubectl get storageclasses -o yaml` would give us this.

**Comment by dwbrown2** [comment]
@immusk thanks for sending your storageclass definitions. The reason we are falling back to default/gp2 in the model is because you do not have a storage class `type` or `storageaccounttype` defined on Azure. Are you able to set these values?

Reference doc: https://kubernetes.io/docs/concepts/storage/storage-classes/

**Comment by immusk** [comment]
@dwbrown2  we dont have this `storageaccounttype` type defined for our storage classes.
we are using the azure vm's/ aws ec2 instances with ebs volumes and using them as open ebs data storage disks in our k8s setup

**Comment by dwbrown2** [comment]
@immusk I don't see how we would actually know the underlying storage type from k8s without this information. do you? there are different storage types for EBS, e.g. gp2, io1, etc, and we need a way to determine which one you are using.

**Comment by dwbrown2** [comment]
@immusk just wanted to follow up here. Were you able to get this data attached? Let me know how we can help.

**Comment by AjayTripathy** [comment]
>  I don't see how we would actually know the underlying storage type from k8s without this information

We now directly match PV id with AWS billing data, so will eventually have accurate pricing for all types/iops/etc albeit slightly delayed.
