### ISSUE TITLE
Getting [Error] Failed to create costmodel.db: open costmodel.db: permission denied

### ISSUE THREAD

**Issue by Soma123** [kubecost/cost-model#376]
I am trying to install the cost-model on my monitoring namespace and it has admin proviledes, yet i keep getting the following error 
[Error] Failed to create costmodel.db: open costmodel.db: permission denied

I am using the latest image not sure if that is the stable image.
I deployed the cost-model as a pod inside my EKS cluster.  We have kube2iam configured on our cluster and I am using the correct role annotations for cost-model. 

Any help would be highly appreciated.

**Comment by dwbrown2** [comment]
Hi @Soma123, we will gladly take a look with you! Can you share a bit more about how your admin privileges are implemented? Is this using kubernetes RBAC auth?

**Comment by Soma123** [comment]
So we have our EKS cluster and we have psp implemented. The monitoring namespace on which i am trying to install cost-model has the same admin rights as namespace kube-system. We also have RBAC enabled for our cluster, hence created a service account, clusterrole and clusterrolebinding. To authenticate with AWS and to ensure that cost-model has the required permissions  i used role annotation in the deployment file. This had to be done since we have kube2iam configured for our cluster.
iam.amazonaws.com/role: arn:aws:iam::XXXXXXXXXXX:role/<Role-Name>

Please let me know if you would need any further information

**Comment by dwbrown2** [comment]
Ok, thank you! So this is a file system permission issue. Here's a code reference:
https://github.com/kubecost/cost-model/blob/master/pkg/costmodel/router.go#L849

Any ideas on what would cause this? 

It's also not clear that this would cause major errors. What's the current state of the application? Are you able to send us a [bug report](http://docs.kubecost.com/bug-report)?

**Comment by Soma123** [comment]
> Ok, thank you! So this is a file system permission issue. Here's a code reference:
> https://github.com/kubecost/cost-model/blob/master/pkg/costmodel/router.go#L849
> 
> Any ideas on what would cause this?
> 
> It's also not clear that this would cause major errors. What's the current state of the application? Are you able to send us a [bug report](http://docs.kubecost.com/bug-report)?

I could resolve the above error by adding volume and volumemounts to the deployment yaml file .. but still getting "404 Page not found" error. Any inputs would really be valuable

**Comment by dwbrown2** [comment]
Where are you getting a 404? Any logs or screenshots would help us diagnose. Are you connecting via the command below or are you using an ingress? 

```
kubectl port-forward --namespace kubecost deployment/kubecost-cost-analyzer 9090
```

**Comment by Soma123** [comment]
I have used this folder to deploy the cost-model stack "https://github.com/kubecost/cost-model/tree/develop/kubernetes" and used LoadBalancer as a service type. Then when i click on <loadbalancer:9003> i get the 404 error .. the logs show no errors.

kind: Service
apiVersion: v1
metadata:
  name: cost-model
  namespace: monitoring
spec:
  selector:
    app: cost-model
  type: LoadBalancer
  ports:
    - name: cost-model
      port: 9003
      targetPort: 9003

**Comment by dwbrown2** [comment]
That install path doesn't have any UI. Here are install options with more information: http://docs.kubecost.com/install

**Comment by Soma123** [comment]
I do not want to use port-forward, how do i add a loadbalancer ?

**Comment by dwbrown2** [comment]
Here are ingress examples: https://github.com/kubecost/docs/blob/master/getting-started.md#basic-auth

Here's an example service (note: this will on some providers expose an external IP): https://github.com/kubecost/docs/blob/b456efc70099068ed8f37720b9a7734cf924386c/kubecost-lb.yaml

**Comment by dwbrown2** [comment]
Hi @Soma123, any other questions here?

**Comment by dwbrown2** [comment]
I'll close this for now because I believe it's addressed. Please reopen at any time if I'm incorrect or if you have follow up questions.
