### ISSUE TITLE
Certain Azure nodes can be registered to the k8s api but not billed.

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-model#382]
Nodes can be in unready status on Azure, in which case we will emit cost data for them, but the user is not billed. The following query should correctly account for these, but we need to make sure it doesn't interfere with other cloud providers billing mechanisms, or stub this out specifically for Azure.

`sum_over_time((kube_node_status_condition{condition="Ready", status=~"(true|false)"} == 1 )[<window>:<resolution>])
`

reported by @mlushpenko

**Comment by mlushpenko** [comment]
Thanks, @AjayTripathy, hope it's not too much trouble

**Comment by AjayTripathy** [comment]
We now have the ability to integrate directly with the Azure Billing CSV to read costs and assign them to nodes.
