### ISSUE TITLE
Authenticating access to kubecost Dashboard

### ISSUE THREAD

**Issue by ademidun** [kubecost/cost-model#383]
- Picture this: We deploy our kubecost dashboard to a publically accessible URL.
- We want a way to grant certain people on our team and only those people read-only access to the Kubecost and grafana graphs and charts.
- Preferably we would like some sort of "Log in With Google" authentication flow before they have access to the dashboard
- Is there a way to password protect (or similar authentication mechanism) that grants certain users access to the dashboard
- Ideally, we are imagining sort of OAuth or OpenID protocol 

[dex](https://github.com/dexidp/dex) and this blog post on [Kubernetes authentication via GitHub OAuth and Dex](https://medium.com/preply-engineering/k8s-auth-a81f59d4dff6) might hopefully give some context on what we are trying to accomplish.

**Comment by dwbrown2** [comment]
Hi @ademidun! Thanks for this detailed request. This is supported with our enterprise product today. Overview is available [here](http://docs.kubecost.com/user-management). 

Want to discuss next week how we can best support your case? Feel free to reach out to us at team@kubecost.com if so.

**Comment by dwbrown2** [comment]
Hi @ademidun, want to discuss further?

**Comment by dwbrown2** [comment]
@ademidun let me know if you want to discuss how get you access to this functionality at any time. 

I'm going to close this issue if there's no immediate interest, but please reopen whenever or email us directly at team@kubecost.com.

**Comment by ademidun** [comment]
Hey @dwbrown2 thanks for getting back to me and following up. Sorry for forgetting to respond.

If we have any more questions, I will be sure to let you know 🙂
