### ISSUE TITLE
no pricing data for Azure Standard_D4s_v3 

### ISSUE THREAD

**Issue by abelal83** [kubecost/cost-model#394]
Monthly cluster costs shown by Kubecost is almost 40% more than what we see in Azure cost analysis. I suspect it is down to missing pricing data for node type?

I0403 09:27:08.355963 1 azureprovider.go:586] [Warning] no pricing data found for northeurope,Standard_D4s_v3,ondemand: &{map[agentpool:linuxpool beta.kubernetes.io/arch:amd64 beta.kubernetes.io/instance-type:Standard_D4s_v3 beta.kubernetes.io/os:linux failure-domain.beta.kubernetes.io/region:northeurope failure-domain.beta.kubernetes.io/zone:0

**Comment by dwbrown2** [comment]
@abelal83 thanks for sharing. Would you be able to email us a [bug report](http://docs.kubecost.com/bug-report) and we can investigate closely? 

In advance of a review, I just wanted to confirm that you were able to configure Azure billing info in /settings.

**Comment by abelal83** [comment]
Hi @dwbrown2 

I've not configured Azure billing info yet but will do next week. If that resolves issue that will be great.

**Comment by dwbrown2** [comment]
Yes, adding billing info will very likely impact prices. Please follow up if you do not see the expected changes.

**Comment by abelal83** [comment]
I followed instructions from http://docs.kubecost.com/azure-config, granted a service principal role at subscription level then added billing info and finally restarted pod but still getting 
```
[Apr 6, 2020 1:19:04 PM GMT+1]
I0406 12:19:04.411471 1 azureprovider.go:586] [Warning] no pricing data found for northeurope,Standard_D4s_v3,ondemand:
```

is there any way to check if the billing info is being used?

**Comment by dwbrown2** [comment]
This appears to be a region/currency mismatch. Investigating with Abu now. 

```
Failed to download pricing data: commerce.RateCardClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="" Message="Invalid region info:nl and currency code:USD combination specified\r\nParameter name: Currency"
```

**Comment by abelal83** [comment]
That indeed is the case. Using NL region EUR currency resolved the issue. Thank you @dwbrown2!
