### ISSUE TITLE
Does this work with VPA?

### ISSUE THREAD

**Issue by yashbhutwala** [kubecost/cost-model#400]

**Comment by dwbrown2** [comment]
@yashbhutwala meaning does Kubecost correctly allocate costs for pods that are being vertically scaled? If so, then absolutely!

**Comment by yashbhutwala** [comment]
No, I mean how are the resource recommendations calculated?  Do they align with the upstream k8s VPA project?  https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler

**Comment by dwbrown2** [comment]
What resource recommendations? Do you mean the ones in the commercial Kubecost product UI (not currently part of this repo)? They are based on the approach outlined here: http://blog.kubecost.com/blog/requests-and-limits/

Apologies if I'm still misunderstanding your question.

**Comment by dwbrown2** [comment]
Hi @yashbhutwala, I just wanted to follow up here... did this answer your question?

**Comment by yashbhutwala** [comment]
I am asking about this screen 

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/5788514/81690575-7a05ec80-9429-11ea-8e80-07db9072dc52.png">

Can you document/outline the differences and tradeoffs between the recommendation algorithm used by kubecost vs the recommendation algorithm used by VPA?

If there is data to prove one is better than the other, can you generate and make public that data?

**Comment by dwbrown2** [comment]
The approach is outlined in the blog post that I shared: http://blog.kubecost.com/blog/requests-and-limits/

Please let me know what questions you have. Happy to discuss if that would be useful.

**Comment by dwbrown2** [comment]
@yashbhutwala, was this resource helpful?

**Comment by Adam-Stack-PM** [comment]
I am closing out the issue because of age. Please re-open if needed.

**Comment by dudicoco** [comment]
Hi @dwbrown2,

Like @yashbhutwala, I was also wondering about this exact question which is how I've found this issue.

The blog post detailing the Prometheus queries used for calculations is great, however, it's still hard to figure out if it's a more accurate solution than the [VPA recommender](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/README.md)
Therefor a direct comparison of the results between the two would be helpful.

**Comment by dwbrown2** [comment]
@dudicoco we haven't documented a direct comparison to date. Have you used the VPA recommender in any specific situation? I believe there are a number of differences, e.g. not being context aware.

**Comment by dudicoco** [comment]
@dwbrown2 I have now installed https://github.com/FairwindsOps/goldilocks which automatically sets up VPA resources in an attempt to compare the results to kubecost.

Can you please elaborate on what you mean by "not being context aware"?

**Comment by AjayTripathy** [comment]
"Context aware" meaning that production workloads may want more headroom vs a dev workload, for example.

Additionally, kubecost resizing is cost aware, vs just based on RAM or CPU, so it would be a bit hard to do a direct comparison, though we should arrive at similar results.

**Comment by dudicoco** [comment]
Thanks @AjayTripathy.

Does kubecost take into account OOM events like the VPA does when calculating recommended RAM?

By the way, is the right sizing code available for review in opencost or is it unique to kubecost?

**Comment by AjayTripathy** [comment]
The code is kubecost specific. Here's some documentation that should be helpful! https://docs.kubecost.com/apis/apis-overview/api-request-right-sizing-v2#recommendation-methodology
