### ISSUE TITLE
aggregatedCostModel API endpoint

### ISSUE THREAD

**Issue by omerlh** [kubecost/cost-model#405]
We are using this endpoint for generating reports, but look like at some point the relevant code was removed. Looking at the code on `router.go`, I couldn't find any other endpoint that can be used for getting cost data by various aggregation keys like namespace or a specific label.

**Comment by dwbrown2** [comment]
Hi Omer! This endpoint is now tightly integrated with our commercial product features (e.g. saml and cacheing layers) and therefore lives in that repo. It available on our free commercial product as well as other tiers. Anything we can do to share more?

**Comment by omerlh** [comment]
The documentation does not exist, so I had to read the code in order to understand what the endpoint does and the available parameters...

**Comment by dwbrown2** [comment]
What do you feel is missing from [this documentation](https://github.com/kubecost/docs/blob/master/allocation-api.md#aggregated-cost-model-api)?

**Comment by omerlh** [comment]
That it was hard to find it :) Maybe worth linking it on the main website?

**Comment by dwbrown2** [comment]
API docs link added to [docs.kubecost.com](http://docs.kubecost.com), thanks for the suggestion! Please let me know if you have any other recommendations here :)
