### ISSUE TITLE
Why PVC costs are per usage?

### ISSUE THREAD

**Issue by omerlh** [kubecost/cost-model#406]
Looking at [EBS pricing](https://aws.amazon.com/ebs/pricing/), look like we pay for what is provisioned - not for what that is actually used. But, looking at the code, it seems that the pricing of a PVC is calculated by the actual usage - why is that?

**Comment by dwbrown2** [comment]
Hi Omer! Kubecost uses the size of a persistent volume claim, which reflects that amount that has been provisioned. What made it appear we were pricing on usage?

**Comment by dwbrown2** [comment]
@omerlh just wanted to follow up here. Did that last message help clarify?

**Comment by dwbrown2** [comment]
@omerlh I'm going to close for now, but feel free to reopen for any reason.
