### ISSUE TITLE
ELB/ALB costs

### ISSUE THREAD

**Issue by omerlh** [kubecost/cost-model#407]
When service has a type of LoadBalancer, a matching cloud resource is created. It will be great to see the price of this service the same way I can see the price of a VPC.

**Comment by dwbrown2** [comment]
Agreed! This is currently on our roadmap. For most teams it's lower priority, because oftentimes it's a small percentage of total spend. Is it a meaningful percentage of your total costs?

**Comment by minac** [comment]
Hello @dwbrown2 @AjayTripathy, it's been a while!

I have this same request, but for the Google side of things. The issue is the same: a service is created in Kubernetes with the `type: LoadBalancer`. It goes out to GCP and creates a Load Balancer, Forwarding Rules, etc.

We need to have this cost show up in Kubecost somewhere in `detail.html#&agg=product`, either the `Network Cost` column or in the `External Cost` column. We already have values in both columns but they do not represent all cluster related network costs (ingress and egress) as well as the cost for the Load Balancer itself.

I looked into adding labels to the Google Cloud Load Balancers (https://console.cloud.google.com/net-services/loadbalancing/loadBalancers/list), but it seems that these resources are not "labelable" yet.

How can I make these network costs show up in Kubecost? They are a meaningful percentage of our costs so they need to be represented for the full picture.
I'd be happy for a shortcut until you have this implemented as well.

Thanks!
Miguel

**Comment by dwbrown2** [comment]
Hi Miguel! We're actively reviewing this now. What's the biggest part of this spend for you? Is it the cost of external IPs, forwarding rules, etc? We're trying to determine if providing the hourly cost via k8s API / Prometheus metrics is sufficient or if we need to do a GCP integration to get the number of forwarding rules, etc. The latter would take some more time.

**Comment by minac** [comment]
Hi Webb!

Here is an ordered list from top spend to lower spend:
```
Network Inter Zone Egress
Network Internet Egress from Americas to Americas
HTTP Load Balancing: Global Forwarding Rule Additional Service Charge
External IP Charge on a Standard VM
Network Internet Egress from Americas to EMEA
HTTP Load Balancing: Global Forwarding Rule Minimum Service Charge
Network Load Balancing: Forwarding Rule Minimum Service Charge in Americas
Network Load Balancing: Data Processing Charge in Americas
Network Internet Egress from Americas to Australia
External IP Charge on a Preemptible VM
Network Internet Egress from Americas to APAC
Network Internet Egress from Virginia to Americas
Network Internet Egress from Americas to China
```

Egress is a big one, followed by forwarding rules and external IPs. 

As I mentioned to Ajay yesterday, unfortunately, this is a slice of Google Cloud that does not have labeling yet, so I can't track down and label relevant resources to make them show up in Kubecost. :(

If we could surface the top 5 of the list above somewhere in Kubecost it would be great, as in our view the cost of the cluster is not complete without the networking side of things.

Just to clarify, the current "Network Costs" column covers exactly what?

Thank you,
Miguel

**Comment by minac** [comment]
Hey @dwbrown2.
I had forgotten about this issue https://github.com/kubecost/cost-analyzer-helm-chart/issues/299. 

If you can make the network costs into a link in the `product` view like you have for the `namespace` view, I think that most of the metrics above would be covered, right?
I'm looking at the `namespace` level and can already see `Internet Egress`, `Cross Zone`, and `Cross Region` per pod.

Please let me know (also feel free to reach out on slack if it's faster to discuss).
Thanks.

**Comment by dwbrown2** [comment]
@minac thanks for this context! We have https://github.com/kubecost/cost-analyzer-helm-chart/issues/299 completed but performance can be slow on medium and large cluster. We're investigating one architecture change this week that could address. Let me follow up soon.

**Comment by minac** [comment]
Thanks for the update @dwbrown2.

So, out of the following list, what does Kubecost already show in one of its views (including namespace)?
```
Network Inter Zone Egress
Network Internet Egress from Americas to Americas
HTTP Load Balancing: Global Forwarding Rule Additional Service Charge
External IP Charge on a Standard VM
Network Internet Egress from Americas to EMEA
HTTP Load Balancing: Global Forwarding Rule Minimum Service Charge
Network Load Balancing: Forwarding Rule Minimum Service Charge in Americas
Network Load Balancing: Data Processing Charge in Americas
Network Internet Egress from Americas to Australia
External IP Charge on a Preemptible VM
Network Internet Egress from Americas to APAC
Network Internet Egress from Virginia to Americas
Network Internet Egress from Americas to China
```
Is there a way to get the other items to show in Kubecost as well?

Thank you.

**Comment by minac** [comment]
Hey @dwbrown2. Any news on this? I'm trying to understand how much is not visible from Kubecost in terms of networking costs for the cluster. Thanks!

**Comment by dwbrown2** [comment]
Hey Miguel! Apologies for missing this one last week. We currently cover all of the Network Internet Egress line items, Network Inter Zone Egress, as well as Network Inter Region Egress costs. 

We are now looking at adding external IP charge, which would just leave additional load balancing charges, e.g. forwarding rules.

Let me know if I can share more of if you have any feedback.

**Comment by minac** [comment]
Thanks 🙏 
Those network costs you mentioned only show on the namespace view, right? Or is there a way to see all (ingress/egress) networking costs for a cluster?

**Comment by dwbrown2** [comment]
All of these egress costs should be visible by cluster in this view. Anything else you would want to see here?

![image](https://user-images.githubusercontent.com/298359/88594942-fcf51700-d016-11ea-9dee-99e7afb0129d.png)

**Comment by minac** [comment]
No, this is perfect @dwbrown2! 👏 

I have one last question, would you guys be able to provide a Bigquery query that shows the network costs which Kubecost doesn't (yet) cover? 
That way I could safely say that what Kubecost shows is the cluster networking costs and what Bigquery shows is the common GCP networking costs.

Thanks for this!

**Comment by dwbrown2** [comment]
@minac here's an example query. Let me know if this doesn't meet your needs or if we can help with anything else. 

```
SELECT
  service.description as service,
  sku.description as description,
  TO_JSON_STRING(labels) as labels,
  SUM(cost) as cost
FROM  billing_data.gcp_billing_export_v1_01AC9F_74CF1D_5565A2
WHERE usage_start_time >= "2020-8-24" AND usage_start_time < "2020-8-25" 
AND (sku.description like "%External IP Charge%" OR sku.description like "%Load Balancing%")
GROUP BY service, description, labels
ORDER BY 4 DESC
```

Apologies on the delay of this.

**Comment by dwbrown2** [comment]
@Sean-Holcomb this is now complete, correct?! If so, feel free to close!

**Comment by Sean-Holcomb** [comment]
Yes this is complete
