### ISSUE TITLE
cost-model memory consumption increased after upgrade

### ISSUE THREAD

**Issue by shaikatz** [kubecost/cost-model#427]
Hello,

I've been using helm chart version 1.55.1 for few months, and the memory consumption of the cost-model container was stable around 150MB.

Yesterday after the update to 1.58.1 the container gets OOM all the time, getting to 2GB consumption (which is the limit I've set).

Looks like the container has a memory leak because it increases until OOM no matter how much memory I'll give him.

Before:
![image](https://user-images.githubusercontent.com/10139826/82409371-3db03d00-9a76-11ea-84b5-a8028bb8a7ea.png)

After:
![image](https://user-images.githubusercontent.com/10139826/82409384-47d23b80-9a76-11ea-86c4-41243a02259d.png)

**Comment by shaikatz** [comment]
I've run some pprof tool and looks like this is the high consuming node
![image](https://user-images.githubusercontent.com/10139826/82411327-4440b380-9a7a-11ea-9a06-c61e9ca3f539.png)

**Comment by dwbrown2** [comment]
Hi @shaikatz we're actively investigating now. Thanks for the detailed report. Can you can share the full flamegraph of inuse memory from pprof?

**Comment by dwbrown2** [comment]
@shaikatz our v1.59.1 release should have had a meaningful impact on both Prom + cost-analyzer memory consumption. Can you let us know if you're still experiencing this behavior? 

If so, getting your pprof binary output or seeing the full flamegraph would be super helpful.

**Comment by shaikatz** [comment]
Looking at the metrics again now, 7 days after installing 1.58.1, the memory and CPU consumption went down over time, and now it's not consuming that much.
I don't know what's the reason for that. but I'm ok with closing the issue now.

**Comment by dwbrown2** [comment]
Great, we're going to re-enable a [new feature](https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/values.yaml#L87) that will provide major performance gains. Let us know if you experience any other issues here and if we can help with anything else.
