### ISSUE TITLE
Support for multi-team resources

### ISSUE THREAD

**Issue by robertgates55** [kubecost/cost-model#433]
Love kubecost, but wondered if you have any suggestions. Some of the resources in our clusters are shared by multiple teams - we have labels like `teams.company/team1=true` and `teams.company/team2=true` on such objects.

Are there any strategies for splitting the cost of these between the teams?

**Comment by dwbrown2** [comment]
The free Kubecost product has a number ways of supporting this concept of shared resources/costs. You can see two approaches for implementing here: 

https://github.com/kubecost/docs/blob/master/allocation-api.md#aggregated-cost-model-api

Specifically, you can implement a shared label or shared namespace with this endpoint.

**Comment by robertgates55** [comment]
Thanks for the response.

I've had a read, and a bit of a play, and I'm struggling to implement an approach.

Say I have a namespace that I wish to split the cost of between team `bob` and team `dave`, and it's currently labelled like this:
```
metadata:
  labels:
    teams.company/bob: true
    teams.company/dave: true
```
Is there any way to do so?

Or is there a better way to label things to support this?

**Comment by dwbrown2** [comment]
Is there any more context you can share about this example? For example, are you looking to distribute the cost of a monitoring namespace across just two of your N tenants?

**Comment by robertgates55** [comment]
Sure.

So yes - for the sake of argument, let’s say we have 2 monitoring namespaces in our cluster, used by different sets of teams.

`monitoring-ns-A` Is used by teams `a`, `b` & `c`
`monitoring-ns-B` Is used by teams `d` & `e`

Is there any way for me to get the costs of teams `a` - `e`, assuming the cost of each namespace is shared evenly by the teams?

**Comment by dwbrown2** [comment]
We do not support this exact case out of the box in our free product. You would have the ability to distribute these two namespaces 1) evenly across all teams or 2) proportionately based on resource usage of each team. 

This behavior is supported in Kubecost Enterprise where you can distribute shared costs based on a custom metric. Let me know if we can share more there.

**Comment by michaelmdresser** [comment]
Hi @robertgates55, I'm going to close this issue due to its age. If you're still using Kubecost and would like to talk further about this feature, feel free to reopen.
