### ISSUE TITLE
Many cost analyzer checks pods were created

### ISSUE THREAD

**Issue by mohanrao** [kubecost/cost-model#437]
Hi,

Installed the kubecost using helm 3 chart some days back. 

I noticed many pods are creating and eventually causing all nodes in a situation of max pods per node situation

Mohanas-MBP:test mohanarao$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                               READY   STATUS              RESTARTS   AGE
default       external-dns-856f68c998-qspw7                      0/1     Pending             0          14m
kube-system   alb-ingress-controller-5b766758d8-6k6zq            1/1     Running             0          26s
kube-system   aws-node-kxx7g                                     1/1     Running             0          18m
kube-system   aws-node-qsmfw                                     1/1     Running             0          18m
kube-system   coredns-56678dcf76-sp8lp                           0/1     Running             0          26s
kube-system   coredns-56678dcf76-z25wt                           0/1     ContainerCreating   0          26s
kube-system   kube-proxy-qvw2k                                   1/1     Running             0          18m
kube-system   kube-proxy-skk4j                                   1/1     Running             0          18m
kubecost      cost-analyzer-checks-1590121800-b4bxt              0/1     Pending             0          6d14h
kubecost      cost-analyzer-checks-1590126600-j4qrk              0/1     Pending             0          6d13h
kubecost      cost-analyzer-checks-1590135600-zlttl              0/1     Pending             0          6d10h
kubecost      cost-analyzer-checks-1590137400-rrprb              0/1     Pending             0          6d10h
kubecost      cost-analyzer-checks-1590144600-5kwgk              0/1     Pending             0          6d8h
kubecost      cost-analyzer-checks-1590145200-6rdt6              0/1     Pending             0          6d7h
kubecost      cost-analyzer-checks-1590151200-r7jrh              0/1     Pending             0          6d6h
kubecost      cost-analyzer-checks-1590156000-6h4w8              0/1     ContainerCreating   0          6d4h
kubecost      cost-analyzer-checks-1590156600-dlw79              0/1     Pending             0          6d4h
kubecost      cost-analyzer-checks-1590157800-pdvsg              0/1     Pending             0          6d4h
kubecost      cost-analyzer-checks-1590161400-9mm7p              0/1     Pending             0          6d3h
kubecost      cost-analyzer-checks-1590165600-gsr9x              0/1     Pending             0          6d2h
kubecost      cost-analyzer-checks-1590166800-z57lp              0/1     Pending             0          6d1h
kubecost      cost-analyzer-checks-1590167400-vf6xj              0/1     Pending             0          6d1h
kubecost      cost-analyzer-checks-1590173400-jhpfj              0/1     Pending             0          6d
kubecost      cost-analyzer-checks-1590185400-9khc5              0/1     Pending             0          5d20h
kubecost      cost-analyzer-checks-1590193200-lngfw              0/1     Pending             0          5d18h
kubecost      cost-analyzer-checks-1590194400-jfvg6              0/1     Pending             0          5d18h
kubecost      cost-analyzer-checks-1590195000-nqmxp              0/1     ContainerCreating   0          5d18h
kubecost      cost-analyzer-checks-1590197400-6xgdp              0/1     Pending             0          5d17h
kubecost      cost-analyzer-checks-1590199800-k476c              0/1     Pending             0          5d16h
kubecost      cost-analyzer-checks-1590200400-8656v              0/1     Pending             0          5d16h
kubecost      cost-analyzer-checks-1590201000-ghxw2              0/1     Pending             0          5d16h
kubecost      cost-analyzer-checks-1590213600-9blc8              0/1     Pending             0          5d12h
kubecost      cost-analyzer-checks-1590214200-b9pzw              0/1     Pending             0          5d12h
kubecost      cost-analyzer-checks-1590216000-cfjtx              0/1     Pending             0          5d12h
kubecost      cost-analyzer-checks-1590231600-c52m4              0/1     Pending             0          5d7h
kubecost      cost-analyzer-checks-1590232200-hp75v              0/1     Pending             0          5d7h
kubecost      cost-analyzer-checks-1590232800-8j2s2              0/1     Pending             0          5d7h
kubecost      cost-analyzer-checks-1590241800-czcnn              0/1     Pending             0          5d5h
kubecost      cost-analyzer-checks-1590255600-98rlc              0/1     Pending             0          5d1h
kubecost      cost-analyzer-checks-1590256800-k8mkg              0/1     Pending             0          5d
kubecost      cost-analyzer-checks-1590267600-4m5mc              0/1     Pending             0          4d21h
kubecost      cost-analyzer-checks-1590274800-7fnbg              0/1     Pending             0          4d19h
kubecost      cost-analyzer-checks-1590278400-vdfn5              0/1     Pending             0          14m
kubecost      cost-analyzer-checks-1590279000-fndsx              0/1     Pending             0          26s
kubecost      cost-analyzer-checks-1590282600-kdjwb              0/1     Pending             0          4d17h
kubecost      cost-analyzer-checks-1590296400-dc2ps              0/1     Pending             0          4d13h
kubecost      cost-analyzer-checks-1590302400-5qkxn              0/1     Pending             0          4d12h
kubecost      cost-analyzer-checks-1590307800-vwft8              0/1     Pending             0          4d10h
kubecost      cost-analyzer-checks-1590310800-7b6rb              0/1     Pending             0          4d9h
kubecost      cost-analyzer-checks-1590313200-kjpcw              0/1     Pending             0          26s
kubecost      cost-analyzer-checks-1590313800-bj4mv              0/1     Pending             0          4d9h
kubecost      cost-analyzer-checks-1590314400-sj6kl              0/1     Pending             0          4d8h
kubecost      cost-analyzer-checks-1590316800-jj5b8              0/1     Pending             0          4d8h
kubecost      cost-analyzer-checks-1590317400-6tflf              0/1     Pending             0          4d8h
kubecost      cost-analyzer-checks-1590321600-2z9km              0/1     Pending             0          4d6h
kubecost      cost-analyzer-checks-1590325200-hs9gm              0/1     Pending             0          4d5h
kubecost      cost-analyzer-checks-1590330000-xc4xl              0/1     Pending             0          26s
kubecost      cost-analyzer-checks-1590369000-xdpgb              0/1     Pending             0          3d17h
kubecost      cost-analyzer-checks-1590373800-q4plh              0/1     Pending             0          3d16h
kubecost      cost-analyzer-checks-1590387000-rmrd6              0/1     Pending             0          3d12h
kubecost      cost-analyzer-checks-1590391800-9hhch              0/1     Pending             0          3d11h
kubecost      cost-analyzer-checks-1590392400-ldck2              0/1     Pending             0          3d11h
kubecost      cost-analyzer-checks-1590396000-wjl6g              0/1     ContainerCreating   0          3d10h
kubecost      cost-analyzer-checks-1590397200-xtj4r              0/1     Pending             0          25s
kubecost      cost-analyzer-checks-1590398400-rnl7s              0/1     Pending             0          25s
kubecost      cost-analyzer-checks-1590403800-8rn2g              0/1     Pending             0          3d8h
kubecost      cost-analyzer-checks-1590410400-k9hds              0/1     Pending             0          3d6h
kubecost      cost-analyzer-checks-1590432600-wnwv2              0/1     Pending             0          3d
kubecost      cost-analyzer-checks-1590438000-6qdc8              0/1     Pending             0          2d22h
kubecost      cost-analyzer-checks-1590443400-mtgq7              0/1     ContainerCreating   0          2d21h
kubecost      cost-analyzer-checks-1590450600-h5ppz              0/1     ContainerCreating   0          2d19h
kubecost      cost-analyzer-checks-1590456000-pn27j              0/1     ContainerCreating   0          25s
kubecost      cost-analyzer-checks-1590459000-5cmf9              0/1     Pending             0          2d16h
kubecost      cost-analyzer-checks-1590460800-w69q5              0/1     Pending             0          6m57s
kubecost      cost-analyzer-checks-1590468600-c4csr              0/1     Pending             0          2d14h
kubecost      cost-analyzer-checks-1590495000-dtntg              0/1     Pending             0          6m57s
kubecost      cost-analyzer-checks-1590498600-xz7g2              0/1     Pending             0          2d5h
kubecost      cost-analyzer-checks-1590502200-5w5nz              0/1     Pending             0          2d4h
kubecost      cost-analyzer-checks-1590505200-jcvt7              0/1     Pending             0          2d3h
kubecost      cost-analyzer-checks-1590507000-rp8rl              0/1     Pending             0          2d3h
kubecost      cost-analyzer-checks-1590515400-5dk66              0/1     Pending             0          2d1h
kubecost      cost-analyzer-checks-1590519000-6dzqg              0/1     Pending             0          2d
kubecost      cost-analyzer-checks-1590520200-hcl26              0/1     Pending             0          47h
kubecost      cost-analyzer-checks-1590534600-d82bm              0/1     Pending             0          43h
kubecost      cost-analyzer-checks-1590542400-2l7xb              0/1     Pending             0          6m57s
kubecost      cost-analyzer-checks-1590555600-svj2b              0/1     Pending             0          37h
kubecost      cost-analyzer-checks-1590573000-g6rd7              0/1     Pending             0          33h
kubecost      cost-analyzer-checks-1590574200-lm7pd              0/1     Pending             0          32h
kubecost      cost-analyzer-checks-1590582000-vr55w              0/1     Pending             0          10m
kubecost      cost-analyzer-checks-1590583800-6jql8              0/1     Pending             0          30h
kubecost      cost-analyzer-checks-1590584400-rn52d              0/1     Pending             0          29h
kubecost      cost-analyzer-checks-1590594000-22h24              0/1     Pending             0          27h
kubecost      cost-analyzer-checks-1590603000-qzxwl              0/1     Pending             0          24h
kubecost      cost-analyzer-checks-1590605400-79n67              0/1     Pending             0          24h
kubecost      cost-analyzer-checks-1590610200-hbpfq              0/1     ContainerCreating   0          22h
kubecost      cost-analyzer-checks-1590612600-mb7sl              0/1     Pending             0          6m56s
kubecost      cost-analyzer-checks-1590613800-4zq7q              0/1     Pending             0          21h
kubecost      cost-analyzer-checks-1590621600-j5m7z              0/1     Pending             0          19h
kubecost      cost-analyzer-checks-1590627000-ql2m2              0/1     Pending             0          18h
kubecost      cost-analyzer-checks-1590630000-9m7wb              0/1     Pending             0          17h
kubecost      cost-analyzer-checks-1590631200-n8sgj              0/1     Pending             0          16h
kubecost      cost-analyzer-checks-1590637200-n4bq8              0/1     Pending             0          15h
kubecost      cost-analyzer-checks-1590642600-fv9st              0/1     Pending             0          13h
kubecost      cost-analyzer-checks-1590659400-xpdr5              0/1     Pending             0          9h
kubecost      cost-analyzer-checks-1590660000-nnf65              0/1     Pending             0          8h
kubecost      cost-analyzer-checks-1590673800-t44d4              0/1     Pending             0          5h3m
kubecost      cost-analyzer-checks-1590676200-k6gqv              0/1     Pending             0          25s
kubecost      cost-analyzer-checks-1590679200-gk9ts              0/1     Pending             0          3h33m
kubecost      kubecost-cost-analyzer-6f87d895dd-csxnl            0/3     Init:1/2            0          14m
kubecost      kubecost-grafana-6468d464d-qznj9                   0/3     Pending             0          24s
kubecost      kubecost-grafana-6468d464d-scs8m                   3/3     Terminating         0          14m
kubecost      kubecost-kube-state-metrics-57f8864f5b-n8bvp       1/1     Running             0          14m
kubecost      kubecost-prometheus-alertmanager-7cdff76d5-6znkx   1/2     Running             0          14m
kubecost      kubecost-prometheus-node-exporter-5l79j            0/1     Pending             0          18m
kubecost      kubecost-prometheus-node-exporter-9jnrn            1/1     Running             0          18m
kubecost      kubecost-prometheus-pushgateway-74b4bbb744-lz4jr   0/1     Pending             0          14m
kubecost      kubecost-prometheus-server-68fd684cbf-vfmhv        0/2     Pending             0          14m

Had to remove the entire namespace.

**Comment by dwbrown2** [comment]
@mohanrao were you able to get this resolved? Can we help with anything?

**Comment by michaelmdresser** [comment]
The cost analyzer checks pod has been deprecated for a while, so this should no longer be an issue. Let us know if you're still experiencing problems.
