### ISSUE TITLE
Out of cluster costs - Azure

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-model#450]
Support Out of Cluster Costs on Azure. This covers the ability to allocate externally managed serves, e.g. Azure Storage, back to Kubernetes clusters and Kubernetes tenants.

**Comment by pierluigilenoci** [comment]
Any news about this?

**Comment by dwbrown2** [comment]
This just launched in Beta in our v1.74 release! Reach out to team@kubecost.com or anyone else if you want to learn more.

**Comment by pierluigilenoci** [comment]
Thanks @dwbrown2, I'll test it ASAP.

**Comment by pierluigilenoci** [comment]
With the v1.75 release, data from Azure seems to be "digested" correctly.

**Comment by dwbrown2** [comment]
Great, reach out if we can provide more here!
