### ISSUE TITLE
Issues with the model when running on GKE

### ISSUE THREAD

**Issue by omerlh** [kubecost/cost-model#459]
Getting this error when trying to view cost allocations:

Unexpected model response: Error: error computing aggregate cost model: Prometheus communication error: error computing normalization max(count_over_time(kube_pod_container_resource_requests_memory_bytes{}[1h] )) for start=2020-06-29 09:48:51.141 +0000 UTC, end=2020-06-30 08:48:51.141 +0000 UTC, window=1h0m0s, res=3600.000000: nil queryResult

Running the same query on Prometheus return results. 

![image](https://user-images.githubusercontent.com/6730584/86122789-102cc980-bae1-11ea-8668-bd6bee938cef.png)

![image](https://user-images.githubusercontent.com/6730584/86122820-1b7ff500-bae1-11ea-8926-73ad522989e2.png)

**Comment by omerlh** [comment]
It happened because thanos was not explicitly disabled (See kubecost/cost-analyzer-helm-chart#526) - I had to disable it manually:
```
  thanos: 
    query: 
```

**Comment by AjayTripathy** [comment]
Closing this issue for now then. Thanks for the note!
