### ISSUE TITLE
Support Reserved Instances with Azure

### ISSUE THREAD

**Issue by sylus** [kubecost/cost-model#500]
Hi amazing kubecost team,

Am loving kubecost and definitely is catching a few things for us. However, we just got reserved instances pricing for one of our node pools and noticed that it isn't reflected in KubeCost. I think for AWS and GCP this works by default but logic is still missing for Azure?

https://github.com/kubecost/cost-model/blob/develop/pkg/cloud/azureprovider.go#L758-L761

**Comment by AjayTripathy** [comment]
Hi @sylus that's correct, this is on our to-do list. The azure API is fairly difficult to parse and map to the k8s api here, but there are improvements planned on the azure side that should make this easier in the future.

**Comment by AjayTripathy** [comment]
@sylus we've got this into beta-- you can check it out in our latest version

**Comment by mo-saeed** [comment]
@AjayTripathy Question please, is this included in opencost or only in kubecost ? I am abit confused. I just installed opencost and it doesn't work with the reserved instances.
