### ISSUE TITLE
kubecost Prometheus high memory usage

### ISSUE THREAD

**Issue by jeanholidu** [kubecost/cost-model#523]
Hi! We have kubecost deployed with helm is our EKS cluster of around 50 nodes (c5.2xlarge). I'm giving 11Gi memory to prometheus-kubecost, 1vcpu, storing only 2h of data and still it's being killed by OOM. Any suggestion / tweak we can do?

**Comment by dwbrown2** [comment]
Hi @jeanholidu, there are many different config changes available to reduce/manage Prometheus memory usage. Are you using your own Prometheus with the open source cost-model or something else? What version of Prometheus are you using?

**Comment by jeanholidu** [comment]
We are using the one provided in the helm chart, in the opensource version of kubecost, with the following:
`prometheus:
  nodeExporter:
    enabled: false
  serviceAccounts:
    nodeExporter:
      create: false

  server:
    retention: 2h

    resources:
      requests:
        cpu: "1000m"
        memory: "11000Mi"
      limits:
        cpu: "1000m"
        memory: "11500Mi"`

**Comment by dwbrown2** [comment]
Thanks! Would you be able to share a [bug report](http://docs.kubecost.com/bug-report) with team@kubecost.com? That should give us full context.

**Comment by jeanholidu** [comment]
I will, thanks for the prompt help.
