### ISSUE TITLE
Clarification: further details about "__idle__" costs/usage

### ISSUE THREAD

**Issue by yashvardhan-kukreja** [kubecost/cost-model#525]
Please provide some further clarification regarding the `__idle__` costs in the kubecost dashboards.
I went over to the documentation but unfortunately, the explanations did not seem comprehensive enough.
If my doubts can be clarified here itself, then it's gonna be fantastic.

**Doubts**

- Do the `__idle__` costs/usage represent the resources which are free of any workloads despite being spun up in the cloud?
- Is there a chance or probability for the `__idle__` costs/usage to be significantly inaccurate?

**Comment by dwbrown2** [comment]
@yashvardhan-kukreja thanks for the questions! Is this [description](https://github.com/kubecost/docs/blob/master/cost-allocation.md#5-allocate-idle-cost) helpful for answering your first question?

Secondly, this calculation should accurately reflect your cloud bill once your cloud integration has been provided. Let me know if you have a specific situation in mind! Happy to discuss further too.

**Comment by yashvardhan-kukreja** [comment]
> @yashvardhan-kukreja thanks for the questions! Is this [description](https://github.com/kubecost/docs/blob/master/cost-allocation.md#5-allocate-idle-cost) helpful for answering your first question?
> 
> Secondly, this calculation should accurately reflect your cloud bill once your cloud integration has been provided. Let me know if you have a specific situation in mind! Happy to discuss further too.

Thanks a lot for the quick reply! And that link to the description was great. It cleared a lot of things.

So, a small thing to ask. Do the estimated costs depend on the underlying EC2 instance type.
For example, say, I have a pod requesting 200MB memory deployed on a t2.micro instance and I have the same identical pod requesting 200MB memory on a c4.xlarge instance. Now, in reality, although, the workload (200MB pod) is same on both but still the costs will be different because c4.xlarge is more expensive than t2.micro.

So, my question is, will kubecost identify the underlying ec2 instance type and predict the right costs, or will it predict same costs for both of the situations because of the fact, that the pod on both of them requests 200MB memory without caring about underlying EC2 instance type?

**Comment by dwbrown2** [comment]
That's exactly right! 

The cost of a workload depends on this equation:

```
avg resources being consumed * amount of time consumed * price of the resource
``` 

where the price of the resource is a function of instance type, region, usage type (e.g. spot RI), etc. Not only will the measured cost of the workload itself account for this, the measured cluster assets will as well.

Just let me know if I can share more.

**Comment by yashvardhan-kukreja** [comment]
Fantastic, that clears it up! Thanks for the quick reply. It was really helpful :)

**Comment by dwbrown2** [comment]
Of course, let me know if we can share more any time!
