### ISSUE TITLE
Document how to turn off verbose logging for the network pods

### ISSUE THREAD

**Issue by omerlh** [kubecost/cost-model#541]
The network pods is spamming with a lot of info logs, after digging I find I might be able to pass in default klog arg `-v 1` to turn them off - but the chart does not support passing args right now. Can you please help?

Example spamming logs:
```
kubecost-network-costs-lqrqg kubecost-network-costs I0913 06:29:53.108331       1 networktrafficlogger.go:77] [<pod>]
kubecost-network-costs-lqrqg I0913 03:29:50.968032       1 networktrafficlogger.go:77] [<>]
kubecost-network-costs I0913 06:29:53.108336       1 networktrafficlogger.go:80]   -> Dest: <>, [RZ] Total Bytes: 238359876, Total GB: 0.22
```

**Comment by mbolt35** [comment]
We can absolutely add a flag to disable logging here. 

For what it's worth, the logging is on a 30m interval, and only includes the top 5 destinations for each source.

**Comment by mbolt35** [comment]
This PR is in and should be good for next release: https://github.com/kubecost/cost-analyzer-helm-chart/pull/609

**Comment by omerlh** [comment]
Thanks! This helped, but now I noticed that also the cost-model itself write logs that by default are on Info:

```
I0923 05:42:35.436089       1 reflector.go:160] Listing and watching *v1.ConfigMap from pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98
--
```

**Comment by AjayTripathy** [comment]
We do collect a lot of data in logs, but this should be done for network pods so closing for now. If there are specific logs that are too verbose on the cost-model, please feel free to open another ticket for those.
