### ISSUE TITLE
cost-model does not work in Kubernetes 1.16 or later

### ISSUE THREAD

**Issue by aiharak** [kubecost/cost-model#542]
Hi,
Thank you for this great work.

[Metrics Overhaul](https://github.com/kubernetes/enhancements/issues/1206) in Kubernetes 1.16 removes labels such as `pod_name`, `container_name` from cadvisor.
As a result, these queries no longer work.
https://github.com/kubecost/cost-model/blob/4d5c7715e1bde8285e4af05c4263f9ba53922a49/pkg/costmodel/costmodel.go#L155

The new labels `pod`, `container` have been around since Kubernetes 1.14.
https://github.com/kubernetes/kubernetes/pull/69099
Dropping support Kubernetes 1.13 or earlier will make it work, do you have any plans?

**Comment by dwbrown2** [comment]
Hi @aiharak, here's our guidance for this situation: https://github.com/kubecost/docs/blob/master/custom-prom.md#cadvisor-metric-labels

Let me know if this works for you and if there are concerns.

**Comment by aiharak** [comment]
Oh sorry, I missed it.
Thank you.

**Comment by dwbrown2** [comment]
No worries -- please feel free to reopen if you think we can do more here!
