### ISSUE TITLE
Cost aggergation per gcp-project

### ISSUE THREAD

**Issue by michal-harish** [kubecost/cost-model#565]
We have multiple gcp projects acting as "zones" inside each of which we are running a separate kubecost installation. However we have only one central billing dataset residing in our main gcp account.

When viewing / querying external costs within each zone , we're seeing costs aggregated from all the projects because there is no way to configure cost-model to filter on individual gcp projects.

**Comment by dwbrown2** [comment]
Our new [Assets API](https://github.com/kubecost/docs/blob/master/assets.md) now has a projectID property. You can filter this data by this field to only see costs for a specific project.

**Comment by michaelmdresser** [comment]
This issue looks like its been addressed. If you'd still like to discuss this functionality, feel free to reopen this issue!
