### ISSUE TITLE
using kubecost from a GKE private cluster

### ISSUE THREAD

**Issue by carlobongiovanni** [kubecost/cost-model#569]
Hi, I'm evaluating  kubecost and I've installed the latest opensource version. Our k8s clusters are running in GKE private clusters, and I've noticed that slack messages are not sent, and probably some other resources are not working correctly because they cannot reach internet. In my environment there is a squid proxy that we use to reach the internet, can Kubecost be configured with it? couldn't find any information related to it.

Thanks
C.

**Comment by dwbrown2** [comment]
Hi @Carlo! Thanks for sharing. A couple contextual questions:

* How did you install Kubecost? e.g. via helm chart?
* Can you share any more info on your proxy setup? How do you currently reach external endpoints, e.g. slack?

We have a number of teams running our product in airgapped/private clusters, and you should be able to pass a custom webhook for sending Slack messages.

**Comment by carlobongiovanni** [comment]
Hi, yes I installed it with the chart. I have noticed there is a cronjob named `checks-xxx` Which verifies if any notification needs to be sent. When it runs out it just prints that he sent the notification to slack, but I don't receive anything at that point. 
To reach internet we have setup an egress proxy, generally setting http_proxy and no_proxy environment variables make the trick, but here I'm still orienting myself and couldn't find where to set them.

Thanks, C.

**Comment by dwbrown2** [comment]
Thanks you! Here's where you can set the Slack endpoint. @AjayTripathy can know if there's more needed giving your proxy setup. 

https://github.com/kubecost/cost-analyzer-helm-chart/blob/acac9db12a9743769809566dd239883e85b9f4c6/cost-analyzer/values.yaml#L25-L27

**Comment by AjayTripathy** [comment]
Hi @carlobongiovanni wanted to let you know that setting the proxy variables is now supported! Let us know if we can get you anything else!

https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L149
