### ISSUE TITLE
Cost Model Container throws panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by CookieMonster70** [kubecost/cost-model#577]
Container Crashes after running a few hours, since then the container crash immediately after restart and therefore the readiness probes are failing:
Readiness probe failed: Get http://100.65.0.187:9003/healthz: dial tcp 100.65.0.187:9003: connect: connection refused
Does anybody know how I can get more information to isolate the problem. 
Thanks,
Daniele

Exception:
1020 06:41:36.727463       1 log.go:53] [Info] Allocation ETL: loading
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1ad60f6]

goroutine 637 [running]:
github.com/kubecost/kubecost-cost-model/pkg/kubecost.(*AllocationSet).End(...)
	/app/kubecost-cost-model/pkg/kubecost/allocation.go:1038
github.com/kubecost/kubecost-cost-model/pkg/allocation.(*MemoryStore).Load.func1(0x2, 0xc0010a4280)
	/app/kubecost-cost-model/pkg/allocation/store.go:268 +0x96
github.com/kubecost/kubecost-cost-model/pkg/kubecost.(*AllocationSetRange).Each(0xc0013de4e0, 0xc000418e48)
	/app/kubecost-cost-model/pkg/kubecost/allocation.go:1347 +0x5c
github.com/kubecost/kubecost-cost-model/pkg/allocation.(*MemoryStore).Load(0xc000692c60, 0x17, 0x0)
	/app/kubecost-cost-model/pkg/allocation/store.go:265 +0x2cb
github.com/kubecost/kubecost-cost-model/pkg/allocation.(*MemoryStore).Run(0xc000692c60, 0xc002049890, 0xc000ae8540, 0xc00053d680, 0xc000554fd0)
	/app/kubecost-cost-model/pkg/allocation/store.go:319 +0x443
main.(*Accesses).RunAllocationPipeline.func1(0x36fd620, 0xc000ae8540, 0xc00053d680)
	/app/kubecost-cost-model/main.go:2365 +0x62
created by main.(*Accesses).RunAllocationPipeline
	/app/kubecost-cost-model/main.go:2364 +0xf9

**Comment by dwbrown2** [comment]
Thank you for reporting, Daniele. Do you know what cost-model version you are experiencing this behavior on?

**Comment by nikovacevic** [comment]
Thanks again for reporting @CookieMonster70. We've identified the problem and hope to have a release to fix it soon.

**Comment by CookieMonster70** [comment]
Hi, we are using version: cost-model:prod-1.67.3

Cheers,
Daniele

**Comment by nikovacevic** [comment]
@CookieMonster70 Thanks again for the report, and for your patience. We expect this issue should be resolved in 1.68.0, so please upgrade and let us know if you have any remaining issues.

**Comment by CookieMonster70** [comment]
I have installed the new version 1.68.0 with Grafana 7.2.2, it seems to work now.

**Comment by dwbrown2** [comment]
Glad to hear! I'll close for now, but please reopen at any point if you have further issues.
