### ISSUE TITLE
Grafana Datasource is not working

### ISSUE THREAD

**Issue by CookieMonster70** [kubecost/cost-model#582]
If I configure a Grafana Datasource in values.yaml, the file datasources.yaml will be created at the container grafana-sc-datasources, with the correct setting and also on the container grafana the grafana.ini itselft contains the correct setting.
But I have to configure the settings manually after a deployment or a restart of the container, it seems that configuration made in the values.yaml are not working.
May I configured something wrong, if not is this bug related to kubecost or to grafana? If to kubecost, how can I fix it?

Cheers,
Daniele

**Comment by dwbrown2** [comment]
@CookieMonster70 any chance you can share the values thats you are passing? We'll look to reproduce based on that.

**Comment by CookieMonster70** [comment]
Hi,
I configured the grafana stuff like this:
`grafana:
  # namespace_datasources: kubecost # override the default namespace here
  # namespace_dashboards: kubecost # override the default namespace here
  sidecar:
    dashboards:
      enabled: true
      # label that the configmaps with dashboards are marked with
      label: grafana_dashboard
    datasources:
      enabled: true
      defaultDatasourceEnabled: false
      dataSourceName: default-kubecost
      # label that the configmaps with datasources are marked with
      label: kubecost_grafana_datasource`

But after the startup of the Grafana Container it looks like this:
- On Cluster Metrics I can't see any data
- On Configuration --> Datasources the datasources are empty. I have to add the data sources manually.  
  At least I expect that a datasource is registred with the default-kubecost.
- But the manually added datasources are gone after the restart of the container, but this is a expected behavior.
- But after the restart it loads a default configuration, which is not working at all. --> http://localhost:9090
  because we have an other url (service) http://prometheus-authenticator:9090. But I don't know where I can set it.

Thanks
Daniele

**Comment by AjayTripathy** [comment]
Hi @CookieMonster70 -- we'd expect any manual configuration to get blown away on pod restart. Datasources are configured by configmap, then read by their label. If the datasource isn't available on grafana, it means grafana wasn't able to find a configmap with the labels that it is searching for.

Are you using a custom grafana that you're trying to add the kubecost datasources to, or the bundled kubecost grafana?

**Comment by CookieMonster70** [comment]
Hi @AjayTripathy -- I checked all config maps. Right now I don't see any error. May you see something, where I did the mistake.


grafana.ini:
```
[analytics]
check_for_updates = true
[auth.anonymous]
enabled = true
org_name = Main Org.
org_role = Admin
[grafana_net]
url = https://grafana.net
[log]
mode = console
[paths]
data = /var/lib/grafana/data
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
[server]
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
- access: direct
  isDefault: true
  name: default-kubecost
  type: prometheus
  url: http://prometheus-authenticator:9090
```
Grafana Datasource: datasource.yaml

```
apiVersion: 1
datasources:
- access: proxy
  name: "default-kubecost"
  isDefault: true
  type: prometheus
  url: http://prometheus-authenticator:9090

```

**Comment by AjayTripathy** [comment]
Hi @CookieMonster70 -- that configmap looks fine but it maybe helpful to see the full configmap including labels. Also to clarify, are you using the grafana bundled with kubecost or something else?
 
Are you saying that after restart, grafana is reverting to a datasource not set in the configmap? Did you manually edit that configmap to say http://prometheus-authenticator:9090 or was that set by setting the Prometheus url when you deployed kubecost? If it was set manually after kubecost was deployed, you may need to restart grafana.

It would be helpful to see what values in values.yaml you installed kubecost with.

It would also be helpful to see the logs of the datasource sidecar. Something like

kubectl logs <your grafana pod> -n kubecost -c grafana-sc-datasources

**Comment by michaelmdresser** [comment]
We've made recent changes to Grafana configuration management in our Helm chart repo https://github.com/kubecost/cost-analyzer-helm-chart that addressed some outstanding issues, so I'm going to close this.

@CookieMonster70 if you're still having troubles, please feel free to reopen this issue!
