### ISSUE TITLE
Cost-model container runtime error

### ISSUE THREAD

**Issue by cleberwarmling** [kubecost/cost-model#586]
I'm seeing a couple of restarts on the cost-model container and for what I've seen it's a `panic: runtime error` in a specific function. See the logs below:

```
I1028 00:37:49.753800       1 log.go:47] [Info] savings: request sizing cached: RequestSizing:Production
I1028 00:37:49.753837       1 log.go:62] [Profiler] 10.933023ms: RecommendRequestSizes::Processing
I1028 00:37:49.753847       1 log.go:62] [Profiler] 1m50.615207228s: RecommendRequestSizes()
I1028 00:37:49.753854       1 log.go:62] [Profiler] 1m51.639040849s: Savings: requestSizing
I1028 00:37:49.753882       1 log.go:47] [Info] savings: warmed cache
E1028 00:38:01.166892       1 log.go:17] [Error] Asset ETL: error: 'expanding series: context deadline exceeded' parsing query 'sum(rate(node_cpu_seconds_total[875m:1m] offset 180m)) by (kubernetes_node, cluster_id, mode)'
panic: runtime error: invalid memory address or nil pointer dereference

goroutine 35 [running]:
github.com/kubecost/cost-model/pkg/errors.SetPanicHandler.func1(0x22ce890)
	/app/cost-model/pkg/errors/panic.go:63 +0xc6
created by github.com/kubecost/cost-model/pkg/errors.SetPanicHandler
	/app/cost-model/pkg/errors/panic.go:57 +0x9b
```

The version that I'm using is `1.68.0.`

Could you guys have a check? If more info is needed let me know.

**Comment by mbolt35** [comment]
Thanks for reporting @cleberwarmling 

CC @nikovacevic 

Doing some guess work here, but this looks like the reported stack trace: 
```
Panic: runtime error: invalid memory address or nil pointer dereference
StackTrace: goroutine 261 [running]:
github.com/kubecost/cost-model/pkg/errors.dispatch(0x1e7ea00, 0x36eba90, 0x0)
	/app/cost-model/pkg/errors/panic.go:115 +0x6d
github.com/kubecost/cost-model/pkg/errors.HandlePanic()
	/app/cost-model/pkg/errors/panic.go:91 +0x64
panic(0x1e7ea00, 0x36eba90)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/kubecost/kubecost-cost-model/pkg/kubecost.(*AssetSet).Start(...)
	/app/kubecost-cost-model/pkg/kubecost/asset.go:2232
github.com/kubecost/kubecost-cost-model/pkg/asset.(*MemoryStore).Insert(0xc000e5b100, 0xc001724000, 0xc000365060, 0xc001724000)
	/app/kubecost-cost-model/pkg/asset/store.go:156 +0x47
github.com/kubecost/kubecost-cost-model/pkg/asset.(*MemoryStore).build(0xc000e5b100, 0x37816102, 0xed72b8c98, 0xc000e26960, 0xbfb6a1e63787aadd, 0xffdadbd6f9b25b40, 0x370ede0, 0x300000000000000, 0xc000bb1860, 0xc000bb17a0, ...)
	/app/kubecost-cost-model/pkg/asset/store.go:692 +0xdaf
created by github.com/kubecost/kubecost-cost-model/pkg/asset.(*MemoryStore).Run.func1
	/app/kubecost-cost-model/pkg/asset/store.go:277 +0x148
```

**Comment by mbolt35** [comment]
@cleberwarmling Just to clarify, are you seeing this consistently, or is it intermittent?

**Comment by cleberwarmling** [comment]
> @cleberwarmling Just to clarify, are you seeing this consistently, or is it intermittent?

@mbolt35 I'm seeing this 2 or 3 times a day for a couple of days.

**Comment by dwbrown2** [comment]
The root cause of this appears to be Prometheus timing out and returning an error. Any known downtime? 

Sharing a screenshot of this Grafana dashboard that we provide can help us investigate. Happy to take a look if that would be useful. 

![image](https://user-images.githubusercontent.com/298359/97480831-33417b80-1911-11eb-957d-03ee92a5ee52.png)

@AjayTripathy there may be an opportunity to add a simple chaos test to the new simulator... this could return random Prometheus errors.

**Comment by cleberwarmling** [comment]
> The root cause of this appears to be Prometheus timing out and returning an error. Any known downtime?
> 
> Sharing a screenshot of this Grafana dashboard that we provide can help us investigate. Happy to take a look if that would be useful.
> 
> ![image](https://user-images.githubusercontent.com/298359/97480831-33417b80-1911-11eb-957d-03ee92a5ee52.png)
> 
> @AjayTripathy there may be an opportunity to add a simple chaos test to the new simulator... this could return random Prometheus errors.

Not sure about that, will check. Thank you!

**Comment by cleberwarmling** [comment]
@dwbrown2 Seems that it is ended a Prometheus instability. Thanks for your attention and sorry for not checking that first.

**Comment by dwbrown2** [comment]
No worries, @cleberwarmling! We still want to address this in our application so please do let us know if you experience the issue again. Also, reach out if we can help with anything else!

**Comment by acarsercan** [comment]
I hit the same error. I had to scale prometheus deployment to 0, kill the analyzer pod and then scale back prometheus
