### ISSUE TITLE
Costs for custom e2 node types

### ISSUE THREAD

**Issue by jervine-gogo** [kubecost/cost-model#613]
We run a GKE cluster that uses custom e2 (pre-emptible) node types for multiple node pools. The cost analysis from kubecost on a daily basis always seems to be too high (compared to the GCP billing report). As an example from 20 November:
 - kubecost: 83.37 USD
 - GCP billing: 48.57 USD (for the entire project)
Attached images showing kubecost and GCP billing data. Also attached the kubecost bug report. I am guessing that the kubecost costs for the custom e2 pre-emptible instances is not right ...
![gcp-billing](https://user-images.githubusercontent.com/57888439/100404831-4fb20e80-309d-11eb-9399-eedc5bd1fa36.png)
![kubecost](https://user-images.githubusercontent.com/57888439/100404840-53de2c00-309d-11eb-8859-d2cbd553772e.png)
[kubecost-bug-report-1606440596139.txt](https://github.com/kubecost/cost-model/files/5605720/kubecost-bug-report-1606440596139.txt)

**Comment by dwbrown2** [comment]
@AjayTripathy to investigate. I know there was a GKE bug where these certain e2 nodes were reporting inaccurate data to Kubernetes.

**Comment by AjayTripathy** [comment]
It's interesting that custom nodes appear to use the same SKU as regular e2 nodes:

<img width="1792" alt="Screen Shot 2020-12-06 at 6 57 33 PM" src="https://user-images.githubusercontent.com/453512/101735392-b0b2ec80-3a76-11eb-9df7-cc6f7fcb8cee.png">

Therefore I believe the only change needed is #623

**Comment by AjayTripathy** [comment]
@jervine-gogo just wanted to follow up here-- #623 has been merged. Let us know/feel free to reopen if there's anything else
