### ISSUE TITLE
Fix panic on failed load balancer key parsing

### ISSUE THREAD

**Issue by nikovacevic** [kubecost/cost-model#621]
## Problem
In [metrics.go on line 519](https://github.com/kubecost/cost-model/blob/master/pkg/costmodel/metrics.go#L519) we do not check the length of the slice before accessing by index, causing panics in some cases.

## Proposed solution
Check the length of the slice before accessing

**Comment by AjayTripathy** [comment]
https://github.com/kubecost/cost-model/pull/579/files fixes, but I'm not sure this was ever a real issue, given that we should be doing the nil check somewhere else? Better to be safe though so we can merge #579
