### ISSUE TITLE
Pricing Sources show warning when no reserved instances

### ISSUE THREAD

**Issue by bentatham** [kubecost/cost-model#629]
Our AWS account has never has Reserved Instances (but does have a Savings Plan).
On the diagnostics page, `Savings Plan, Reserved Instance, and Out-Of-Cluster` shows as a warning.

```
No results available for SELECT line_item_usage_start_date, reservation_reservation_a_r_n, line_item_resource_id, reservation_effective_cost FROM kubecost_nmx_prod as cost_data WHERE line_item_usage_start_date BETWEEN date '2020-12-14' AND date '2020-12-15' AND reservation_reservation_a_r_n <> '' ORDER BY line_item_usage_start_date DESC
```

On another cluster that does have RIs, everything works fine, so I think this is caused by the CUR not having any info about RIs because it has never had them.

![image](https://user-images.githubusercontent.com/588580/102238887-452cad00-3ec4-11eb-816a-154ac70f7d1c.png)

**Comment by AjayTripathy** [comment]
Hi @bentatham thanks for this report. 

The correct behavior is probably to split this diagnostic into CUR loading and then a count of RIs and savings plans nodes.

**Comment by AjayTripathy** [comment]
FIxed in https://github.com/kubecost/cost-model/pull/744 and available in our nightly!
