### ISSUE TITLE
Support same instance type matching in custom CSV

### ISSUE THREAD

**Issue by rcallphin** [kubecost/cost-model#637]
When a node instanceID does not match in the custom CSV, having support for the process to infer a match based on other instanceID's in the csv that share the same instance type and region or vmss in azure.

**Comment by dwbrown2** [comment]
Following up after our discussion on Thursday, the current plan is to use existing data points in the CSV pipeline to infer new node prices. Initial algorithm will follow this logic:

* First search for an exact match in CSV pipeline
* If exact match not available, search for an existing CSV data point that matches region, instanceType, and AssetClass 
* If neither available, fallback to pricing estimates

**Comment by dwbrown2** [comment]
Initial implementation PR now out: https://github.com/kubecost/cost-model/pull/641

**Comment by AjayTripathy** [comment]
merged and released  in v1.71.1!
