### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by appunni-dishq** [kubecost/cost-model#645]
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1ad5fc6]
goroutine 635 [running]:
github.com/kubecost/kubecost-cost-model/pkg/kubecost.(*AllocationSet).End(...)
	/app/kubecost-cost-model/pkg/kubecost/allocation.go:1038
github.com/kubecost/kubecost-cost-model/pkg/allocation.(*MemoryStore).Load.func1(0x7d, 0xc0084e28c0)
	/app/kubecost-cost-model/pkg/allocation/store.go:266 +0x96
github.com/kubecost/kubecost-cost-model/pkg/kubecost.(*AllocationSetRange).Each(0xc008b38840, 0xc0030ebe48)
	/app/kubecost-cost-model/pkg/kubecost/allocation.go:1347 +0x5c
github.com/kubecost/kubecost-cost-model/pkg/allocation.(*MemoryStore).Load(0xc002e5a480, 0x17, 0x0)
	/app/kubecost-cost-model/pkg/allocation/store.go:263 +0x2c8
github.com/kubecost/kubecost-cost-model/pkg/allocation.(*MemoryStore).Run(0xc002e5a480, 0xc0087df9ec, 0xc004c696e0, 0xc003d8bf80, 0xc0005d8fd0)
	/app/kubecost-cost-model/pkg/allocation/store.go:317 +0x443
main.(*Accesses).RunAllocationPipeline.func1(0x36fc5e0, 0xc004c696e0, 0xc003d8bf80)
	/app/kubecost-cost-model/main.go:2365 +0x62
created by main.(*Accesses).RunAllocationPipeline
	/app/kubecost-cost-model/main.go:2364 +0xf9

```

Increasing memory from 1200MB to 4000MB did not resolve the issue. Our metric servers are not reporting such high usage either. But it stopped working 15 days before or so. Started crashback looping

**Comment by dwbrown2** [comment]
Thanks for reporting, @appunni-dishq. Can you share what version of Kubecost you are running? It's available in Settings UI or via `helm ls`.

**Comment by appunni-dishq** [comment]
I am using Kubecost model Docker image: `gcr.io/kubecost1/cost-model:prod-1.67.2`

```
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
kubecost        kubecost        11              2021-01-05 10:11:02.302459385 +0530 IST deployed        cost-analyzer-1.67.2    1.67.2
```

**Comment by dwbrown2** [comment]
@appunni-dishq I would need to do a bit of investigation but this should be resolved in v1.71.0

**Comment by appunni-dishq** [comment]
okay I will check the version out and let you know if it persists

**Comment by dwbrown2** [comment]
@appunni-dishq I just double checked, and this should be resolved in the latest build I mentioned.

**Comment by appunni-dishq** [comment]
I haven't faced this issue since the upgrade, but I doubt it happens after 3-4 months of data accumulation. I did lose all the data on upgrade, which could point to data corruption as well?

**Comment by AjayTripathy** [comment]
HI @appunni-dishq , today we only build data back to the retention window of the prometheus you're running on upgrade, so it's unlikely corruption is the cause of losing the accumulated data.

**Comment by dwbrown2** [comment]
@appunni-dishq anything else we can help with here? was Ajay's description helpful?

**Comment by appunni-dishq** [comment]
@dwbrown2 Currently seems to be working fine. I will open a new issue if I face it again. Thank you @AjayTripathy
