### ISSUE TITLE
Timeout received from costrange query

### ISSUE THREAD

**Issue by daganida88** [kubecost/cost-model#652]
E0111 07:22:23.634127       1 log.go:17] [Error] CostDataRange: Request Error: 503 (Service Unavailable) Headers: { Content-Type: [ application/json ], Date: [ Mon, 11 Jan 2021 07:20:57 GMT ] }, Body: {"status":"error","errorType":"timeout","error":"query timed out in query queue"} Query: avg(avg(kube_persistentvolumeclaim_info) by (persistentvolumeclaim, storageclass, namespace, volumename, cluster_id)

**Comment by daganida88** [comment]
E0111 07:54:08.150597       1 log.go:17] [Error] CostDataRange: Request Error: 503 (Service Unavailable) Headers: { Content-Type: [ application/json ], Date: [ Mon, 11 Jan 2021 07:51:15 GMT ] }, Body: {"status":"error","errorType":"timeout","error":"query timed out in expression evaluation"} Query: avg(
		label_replace(
			label_replace(
				avg(
					count_over_time(kube_pod_container_resource_requests_memory_bytes{container!="",container!="POD", node!=""}[2h] )
					*
					avg_over_time(kube_pod_container_resource_requests_memory_bytes{container!="",container!="POD", node!=""}[2h] )
				) by (namespace,container,pod,node,cluster_id) , "container_name","$1","container","(.+)"
			), "pod_name","$1","pod","(.+)"
		)
	) by (namespace,container_name,pod_name,node,cluster_id)
E0111 07:54:08.150608       1 log.go:17] [Error] CostDataRange: Parsing Error: Prometheus communication error: avg(
		label_replace(
			label_replace(
				avg(
					count_over_time(kube_pod_container_resource_requests_memory_bytes{container!="",container!="POD", node!=""}[2h] )
					*
					avg_over_time(kube_pod_container_resource_requests_memory_bytes{container!="",container!="POD", node!=""}[2h] )
				) by (namespace,container,pod,node,cluster_id) , "container_name","$1","container","(.+)"
			), "pod_name","$1","pod","(.+)"
		)
	) by (namespace,container_name,pod_name,node,cluster_id)

**Comment by AjayTripathy** [comment]
Hi @daganida88 can you provide some additional information about the scale at which you're running kubecost and what resources you've provided prometheus? Are you using our prometheus or your bringing your own?

 If you've installed via helm, you can grab a bug report from /settings.html and send it to us on slack or to ajay@kubecost.com

**Comment by dwbrown2** [comment]
@daganida88 this does look scale related. In general, aggregatedCostModel + Allocation APIs are built for medium or large clusters. More info [here](https://github.com/kubecost/docs/blob/master/apis.md) on APIS.

**Comment by michaelmdresser** [comment]
Closing this issue due to age. @daganida88 if you're still experiencing scale problems with Kubecost's APIs in the latest version of Kubecost, please feel free to reach out to us or reopen this issue!
