### ISSUE TITLE
Unable to recognize instance type when key name contains dot characters

### ISSUE THREAD

**Issue by scottkarnold** [kubecost/cost-model#655]
I am using the CSV feature of kubecost to specify custom pricing data based on the EC2 instance type.  When the key name for the instance type in the node spec contains dot characters, kubecost can not match the key value with instance type specified in the CSV file.

For example, in my cluster node specs the m5.xlarge instance types are identified as follows:

apiVersion: v1
kind: Node
metadata:
  labels:
    node.kubernetes.io/instance-type: m5.xlarge

My CSV file has entries that resemble the following:

EndTimestamp,InstanceID,Region,AssetClass,InstanceIDField,InstanceType,MarketPriceHourly,Version
,i-xxxxxxxxxxxxxxxxx,us-west-1,node,metadata.labels.node.kubernetes.io/instance-type,0.192,

Because the InstanceIDField (which is set to metadata.labels.node.kubernetes.io/instance-type) includes '.' characters, it appears to be parsed incorrectly.

**Comment by AjayTripathy** [comment]
Hi @scottkarnold , it looks like your CSV may be improperly formatted? Here's a sample of what it should look like.

https://github.com/kubecost/cost-model/blob/develop/configs/pricing_schema_region.csv
 It looks like the EndTimeStamp field is missing. Any chance you could add that and send us a bug report if it still isn't working?

**Comment by scottkarnold** [comment]
The reason why that schema won't work for us is that our EC2 are continually being terminated and relaunched, so the instance IDs are always changing.  Thus, the CSV file would continually have to be regenerated.  We were hoping that the InstanceID and InstanceIDField parameters in the CSV file could be set so that we would can specify an hourly rate for each instance type in our cluster, not for each instance ID.

**Comment by scottkarnold** [comment]
Inadvertently closed issue.  Reopening again awaiting response.

**Comment by dwbrown2** [comment]
@scottkarnold it might be helpful to learn a bit more about your specific use case, but we have two relevant features for this general situation:

1) our pricing inference feature applies historical prices based on matching instance type. for example, once we see one `m5.xlarge` the pipeline will apply that price to future nodes of that type until it sees a price update or a more specific price for that instanceID

2) you should be able to directly pass `instance-type` as the pricing key but I would need to test to determine the exact metadata value that is required.

**Comment by scottkarnold** [comment]
I added a new annotation called `instance-type` (no '.' characters in the key name field) and this worked.

One more quick question:  Can we tell Kubecost to only indicate cost for nodes that are tagged with a specific value?  For example, I would like to be able to view costs only for those nodes that have been assigned the `Project` tag with a value of `shared`.

**Comment by dwbrown2** [comment]
@scottkarnold can you share a bit more? How would you like to treat nodes without `project=shared`? Are you aiming to exclude them entirely from our Kubecost UI, APIs, etc. Any more detail you can share on the scenario?

**Comment by scottkarnold** [comment]
After thinking about it some, the ability to treat nodes differently without or without `project=shared` is not needed by us.  Thank you for all your previous responses.  I now have a good understand as to how Kubecost can work for us.

This issue can be closed.

**Comment by dwbrown2** [comment]
Sounds good, Scott! Lots more features related to this pipeline and throughout the product, so please feel free to reopen or reach out if we can help with anything else.
