### ISSUE TITLE
Skipping Node "" due to missing Node Data costs

### ISSUE THREAD

**Issue by mdaniel** [kubecost/cost-model#66]
> I0430 21:18:16.906798       1 main.go:169] Skipping Node "" due to missing Node Data costs

Appears every scrape, but because almost every log message is "info" it's hard to know if that's an expected outcome or what

Sometimes it appears twice:
> I0430 21:20:17.352432       1 main.go:169] Skipping Node "" due to missing Node Data costs
> I0430 21:20:17.352584       1 main.go:169] Skipping Node "" due to missing Node Data costs

Kubernetes Version: `v1.13.4`
Cloud Provider: AWS
KubeCost Version:
```
NAME                 	REVISION	UPDATED                 	STATUS  	CHART                       	APP VERSION	NAMESPACE
kubecost             	1       	Tue Apr 30 14:10:18 2019	DEPLOYED	cost-analyzer-1.18.2        	1.0        	kubecost
```

**Comment by AjayTripathy** [comment]
Likely related to #62  . We aren't correctly getting the node a pod *was* running on.

**Comment by AjayTripathy** [comment]
Likely related to #62  . We aren't correctly getting the node a pod *was* running on.

**Comment by AjayTripathy** [comment]
#67 should partially fix this.

**Comment by dwbrown2** [comment]
#72 should effectively fix this outright. Note that there are scenarios where `Pending` pods would have missing node data. I believe this is WAI given the current design.

**Comment by AjayTripathy** [comment]
#72 is in, so this is "fixed" in that this error should be rare and meaningful (only occur when you're not scraping the emitted data from /metrics)
