### ISSUE TITLE
kubecost with custom resource of kubernetes

### ISSUE THREAD

**Issue by adi0509** [kubecost/cost-model#680]
We have a custom resource in k8s and have their metrics. we want to use kubecost to calculate cost. How can we use kubecost to calculate cost of cutom resource of kubernetes?

**Comment by dwbrown2** [comment]
@adi0509 happy to help. Can you share more about what type of custom resource you have in mind? Would this be like a custom controller? Have an example you can share?

**Comment by adi0509** [comment]
suppose I have a custom elastic search controller,  and it is exposing storage metrics per user. So I want to get cost of storage per user used to store their logs.

**Comment by dwbrown2** [comment]
@adi0509 I would need to learn more specifics about the situation, but you should be able to tag the backing domain. This is assuming you are using Amazon Elasticsearch Service. 

Have you deployed free Kubecost at this point?

**Comment by adi0509** [comment]
Yes, I have deployed open-source kubecost from the repo. Me and my team are deploying k8s with microk8s. Our professor told to us reuse one or more open-source software in our k8s project. So, we decided to use elasticsearch. But our project was bare minimum so she told to look more things, kubecost has really good GUI and with kubecost we can give really good presentation. I just want a way to add it to our project. We just need a prototype kind of thing that we can display and show we did it.

**Comment by adi0509** [comment]
From my understanding we need a controller and custom metrics, my friend is working on that part. And I am figuring out how to use kubecost. Any suggestions or is there any thing for custom resource in kubecost?

**Comment by adi0509** [comment]
To make it simple we are only managing users details in elasticsearch. So, maybe we can show storage cost of user from gui, something like they used 2gb of storage.

**Comment by dwbrown2** [comment]
This should be supported today via tagging. You san associate this external cost with a namespace, deployment, statefulset, etc. I think it would be helpful to discuss if you want to get into more specifics. Feel free to reach out to team@kubecost.com!

**Comment by michaelmdresser** [comment]
Closing this issue due to age. @adi0509 if you'd like to discuss this use-case more, please feel free to reopen or reach out to us directly via email or our Slack.
