### ISSUE TITLE
Intermittent "error":"vector cannot contain metrics with the same labelset"

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-model#720]
On some versions of Thanos > 0.15 (kubecost default), we're seeing intermittent "error":"vector cannot contain metrics with the same labelset". 

It seems likely that https://github.com/kubecost/cost-model/pull/719 will address, but more testing on thanos > 0.15 is required.

**Comment by AjayTripathy** [comment]
This appears to have been resolved by #719

**Comment by lucasvscosta96** [comment]
I'm using Thanos in 0.31.0 version
Opencost 1.109.0.

I'm seeing the same error. How fix it ?

**Comment by mattray** [comment]
@lucasvscosta96 could you open a new issue for what you're seeing? You responded to an issue that predates OpenCost.
