### ISSUE TITLE
Attach GPU count to nodes, GPU requests to pods

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-model#723]
We currently report GPU costs in the API here, but not GPU counts:
https://github.com/kubecost/cost-model/blob/develop/pkg/costmodel/cluster.go#L424
We may need to emit this as a metric if it does not exist

For pods, we are querying the GPU requests so it should be easy to attach that to the cache-- but some investigation may need to be done: @nikovacevic

**Comment by AjayTripathy** [comment]
After looking into this, there is actually a pricing bug related to this. We aren't correctly counting GPUs which is resulting in a price discrepancy for node classes with GPU counts > 1 on AWS for the public API. We need to emit the GPU counts as a prometheus metric and join them with the per-gpu costs we already emit to prometheus.

**Comment by Sean-Holcomb** [comment]
Addressed in
https://github.com/kubecost/cost-model/pull/726#pullrequestreview-610213285
