### ISSUE TITLE
Feature Request - Cost threshold notifications and alerts for labels

### ISSUE THREAD

**Issue by alysaleh-fbs** [kubecost/cost-model#737]
We are currently using Kubecost the business version, and it only supports notifications based on namespaces, however, we need an option to send alerts for resources assigned a specific label. 
This feature is very critical to our cost visibility model, and we are looking to include it in your short-term roadmap.

**Comment by dwbrown2** [comment]
Thank you, @alysaleh-fbs! 

@AjayTripathy I know this feature is underway with the alerts re-write. Can you share any updates?

**Comment by AjayTripathy** [comment]
Hi Aly, thanks for this feature request. This work has been planned-- stay tuned for an ETA!

**Comment by pierluigilenoci** [comment]
This feature is really interesting.

**Comment by dwbrown2** [comment]
@mbolt35 is this actually complete once we start running alerts through kubecost Go routines?

**Comment by dwbrown2** [comment]
Now that we've migrated alerts to Go, @mbolt35 is going to review adding this functionality!

**Comment by dwbrown2** [comment]
We've just added the ability to generate recurring reports based on any aggregation, e.g. label and deployment. 

It's available in our latest RC build -- https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.82.0-rc.0

Would love to hear your feedback on this addition if it's useful for you!

**Comment by pierluigilenoci** [comment]
@dwbrown2 is there any documentation of use of the feature?

**Comment by dwbrown2** [comment]
@pierluigilenoci here you go: https://github.com/kubecost/docs/pull/93/files

Let me know if you have questions or issues!

**Comment by michaelmdresser** [comment]
We believe this issue has been addressed with the latest work on Alerts. See https://guide.kubecost.com/hc/en-us/articles/4407601796759-Alerts-Documentation#type-budget for the official documentation.
