### ISSUE TITLE
Openshift Support

### ISSUE THREAD

**Issue by srinivma1** [kubecost/cost-model#74]
Raising the issue again in this forum, since below URL is deprecated

https://github.com/AjayTripathy/kubecost-quickstart/issues/3

**Issue:**
I was able to deploy the cost-model on Openshift, but the pod does not come up with the following error. Tried both **service** and **route** approach to connect to existing prometheus server.

F0503 09:46:27.109402 1 main.go:173] Failed to use Prometheus at http://prometheus-k8s.openshift-monitoring.svc Error: Get http://prometheus-k8s.openshift-monitoring.svc/api/v1/status/config: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

The above is a service URL, I also tried the route URL(re-encryption route) which is https and I get the following error.

https://prometheus-k8s-openshift-monitoring.infra.saasitc-gce-shared.ragsr01.cs.saas.ca.com/

Error: Certificate signed by unknown authority

I was atleast expecting the connection should work with service URL (not the route URL) but even that is not working.

**Steps to Reproduce:**

1. docker build --rm -f "Dockerfile" -t <repo>/kubecost-cost-model:<tag> .
2. Edit the pulled image in the deployment.yaml to /kubecost-cost-model:
3. Set this environment variable to the address of your prometheus server
4. kubectl create namespace cost-model
5. kubectl apply -f kubernetes/ --namespace cost-model
6. kubectl port-forward --namespace cost-model service/cost-model 9003

**Openshift Version:**
 v3.11

**Comment by srinivma1** [comment]
I was able to do a curl successfully to the prometheus server secured route using following command from other pods:

**curl -k -H  "Authorization: Bearer $(oc whoami -t)" https://prometheus-k8s-openshift-monitoring.40.71.221.144o/api/v1/status/config**

where oc whoami -t is the password for cluster admin.

Attached herewith is the response that I received.


[response.json.txt](https://github.com/kubecost/cost-model/files/3148937/response.json.txt)

**Comment by AjayTripathy** [comment]
Today, we don't support adding security tokens to your intra-cluster connections, which is probably what is causing this to fail. I've filed #77 to support this.

**Comment by AjayTripathy** [comment]
@srinivma1 we have a number of OpenShift users now and this seems to work. We're also now offering support for OpenShift users in our paid product. Are you still dealing with this issue?

**Comment by dwbrown2** [comment]
Marking as closed based on Ajay's previous comment. Please feel free to reopen if there are additional questions!
