### ISSUE TITLE
I couldnot see last 1 day cost detail.  can see cost details if 2d or more than that. why ? also i cant see any deployment pods name if i click on cost.i installed kubecost using helm chart but with my own prometheus. can you help me on this? i have attached some screenshots here.

### ISSUE THREAD

**Issue by zippyopstraining** [kubecost/cost-model#759]

**Comment by zippyopstraining** [comment]
I couldnot see last 1 day cost detail.  can see cost details if 2d or more than that. why ? also i cant see any deployment pods name if i click on $cost.i installed kubecost using helm chart but with my own prometheus. can you help me on this? i have attached some screenshots here.

![Screenshot_1](https://user-images.githubusercontent.com/77266301/113264490-a7cd7b80-92f0-11eb-9962-4baca580743c.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/77266301/113264496-a9973f00-92f0-11eb-8eab-6de57bdb109a.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/77266301/113264497-aa2fd580-92f0-11eb-9162-59ee679b9da0.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/77266301/113264530-b156e380-92f0-11eb-8202-badf2c455cd0.jpg)

**Comment by michaelmdresser** [comment]
Hi @zippyopstraining, for the moment can you try using Reports instead of Cost Allocation? That should work for you right now and let me know if it doesn't.

While you're doing that, I'll look a little more into this problem you're encountering.

**Comment by AjayTripathy** [comment]
This page has been deprecated in favor of reports.html as of 1.79.0 . Please let us know if the problem persists on the new cost-allocation page.
