### ISSUE TITLE
what is reporting model

### ISSUE THREAD

**Issue by prasenforu** [kubecost/cost-model#76]
I saw video and saw that the features also but its not talking about any reporting model.

Not sure Business or Enterprise support reporting model (excel).

Looks like its only dashboard view and slack notification ....

**Comment by dwbrown2** [comment]
Hi @prasenforu! Can you clarify a bit what you're looking to do here? Are you looking to export pricing data to excel for further calculations? If so, we should support this depending on what format you are looking for.

**Comment by prasenforu** [comment]
Yes, export data in excel format further calculation.

And another thing dashboard view authentication method.

Because we are planning to propose for our client.

For Business or Enterprises license these the questions will come.

**Comment by dwbrown2** [comment]
Our commercial product does indeed support the ability to generate reports and then export this data to excel. It allows you to export cost by namespace, service, etc over different date ranges. 

We also support different authentication approaches from basic auth to SAML integrations. Please reach out (team@kubecost.com) if you want to discuss further!

**Comment by prasenforu** [comment]
Thanks!!

We will connect you over mail.
