### ISSUE TITLE
Azure and AWS External costs are not summed correctly

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-model#764]
In early March, I discussed with Fang and Aaron about external cost discrepancies issues in Azure. 

I shared with them bug reports and Azure cost data. I'm waiting since then so I created this to get feedback.

The cluster is configured to be named "production.azure.akelius.com" but inside `cost-analyzer` it is labeled "cluster-one". All resources are tagged with the [correct name set via the chart](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L628). The software is therefore not able to add these values.

<img width="1530" alt="Screenshot 2021-04-09 at 16 41 18" src="https://user-images.githubusercontent.com/36044817/114198333-7ccbd300-9953-11eb-9232-0eb19545b852.png">

<img width="905" alt="Screenshot 2021-04-09 at 16 42 14" src="https://user-images.githubusercontent.com/36044817/114198662-dcc27980-9953-11eb-97c1-fb8f81da3021.png">

**Comment by pierluigilenoci** [comment]
@dwbrown2 could you please give feedback also for this?

**Comment by dwbrown2** [comment]
@Sean-Holcomb can you please review?

**Comment by Sean-Holcomb** [comment]
@pierluigilenoci so cluster aggregation actually occurs on `cluster_id` which can be set [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L328)

![Screen Shot 2021-04-12 at 2 39 01 PM](https://user-images.githubusercontent.com/12225425/114466106-dd018580-9b9c-11eb-95b2-a0b222abf8d1.png)

Please let me know if this solves the issue for you

**Comment by pierluigilenoci** [comment]
@Sean-Holcomb @dwbrown2 I will try this solution but it is a further workaround to be done externally in the Prometheus configuration. I am not very satisfied with this solution. 

Ref: https://github.com/kubecost/cost-analyzer-helm-chart/issues/747

**Comment by dwbrown2** [comment]
@pierluigilenoci what exactly are you not satisfied with? we need a unique key to identify clusters. do you have another solution you would like to propose?

**Comment by pierluigilenoci** [comment]
@dwbrown2 I was convinced that this topic had already been discussed but if we want to summarize the point: I don't like to force a change of third-party software configurations to make Kubecost work.

**Comment by dwbrown2** [comment]
@pierluigilenoci we need a unique key to identify our metrics by cluster. open to ideas if you have them.

**Comment by pierluigilenoci** [comment]
@Sean-Holcomb configured as requested, still not summed correctly.

<img width="1547" alt="Cost-analyzer UI" src="https://user-images.githubusercontent.com/36044817/115193429-74f6f600-a0ec-11eb-806e-304ad6358ff1.png">
<img width="1151" alt="Prometheus config map" src="https://user-images.githubusercontent.com/36044817/115193481-85a76c00-a0ec-11eb-9939-4e22cdc62762.png">
<img width="1218" alt="Full diagnostic" src="https://user-images.githubusercontent.com/36044817/115193516-91932e00-a0ec-11eb-86c6-203d3160403e.png">

**Comment by Sean-Holcomb** [comment]
@pierluigilenoci so once the have changed the cluster_id to the correct values you will also have to run an assets rebuild with `/model/etl/allocation/rebuild?window=all&commit=true` Here are my results
Before:
![Screen Shot 2021-04-19 at 9 43 52 AM](https://user-images.githubusercontent.com/12225425/115273626-a4116580-a0f4-11eb-87d5-a18ef6d5680e.png)
After:
![Screen Shot 2021-04-19 at 9 48 23 AM](https://user-images.githubusercontent.com/12225425/115273655-ac69a080-a0f4-11eb-86ca-b703cd65cb25.png)

**Comment by pierluigilenoci** [comment]
Hi @Sean-Holcomb, I called this API and I get this:
```json
{"code":200,"data":"Rebuilding Allocation ETL"}
```
Checking the pod logs I have thousands of line like this:
```
I0420 07:21:23.664550       1 log.go:32] [Warning] AllocationSet.AggregateBy: error getting share coefficienct for 'cluster-one/__idle__'
I0420 07:21:23.664570       1 log.go:32] [Warning] AllocationSet.AggregateBy: error getting share coefficienct for 'cluster-one/__idle__'
```
but at the end I get this:
```
I0420 07:23:34.683459       1 log.go:62] [Profiler] 40.250839ms: Allocation ETL: build[zDElO]: coverage [2021-01-20T00:00:00+0000, 2021-04-21T00:00:00+0000) (100.0% complete)
I0420 07:23:34.683464       1 log.go:62] [Profiler] 1m52.922457813s: Allocation ETL: build[zDElO] total elapsed time
I0420 07:23:34.683482       1 log.go:47] [Info] Allocation ETL: build complete: coverage [2021-01-20T00:00:00+0000, 2021-04-21T00:00:00+0000) (100.0% complete)
I0420 07:23:34.683500       1 log.go:47] [Info] Allocation ETL: build complete
I0420 07:25:50.262437       1 log.go:47] [Info] aggregation: cache warming defaults: 1d::::::::namespace:::default,[REDACTED],kube-node-lease,kube-public,kube-system::weighted:true:false:true
I0420 07:25:50.262469       1 log.go:47] [Info] ComputeAggregateCostModel: missed cache: 1d:1m:1.000000h:false (found true, disableCache true, noCache false)
I0420 07:25:53.210355       1 log.go:47] [Info] ComputeAggregateCostModel: setting L2 cache: 1d:1m:1.000000h:false
I0420 07:25:53.299145       1 log.go:47] [Info] ComputeAggregateCostModel: setting aggregate cache: 1d::::::::namespace:::default,[REDACTED],kube-node-lease,kube-public,kube-system::weighted:true:false:true
I0420 07:25:53.719902       1 log.go:47] [Info] caching 1d cluster costs for 11m0s
I0420 07:25:53.719925       1 log.go:47] [Info] aggregation: warm cache: 1d
I0420 07:26:24.962378       1 log.go:62] [Profiler] 199.102364ms: Asset ETL: run: completed [2021-04-20T00:00:00+0000, 2021-04-21T00:00:00+0000)
I0420 07:27:12.471406       1 log.go:47] [Info] resources: warmed cache
I0420 07:27:17.292498       1 log.go:47] [Info] Diagnostics[mhIJM]: Running diagnostics checks
I0420 07:27:17.295536       1 log.go:47] [Info] Diagnostics[mhIJM]: No errors found.
```
So I presume that everything works. But I get the same result in the interface (https://github.com/kubecost/cost-model/issues/764#issuecomment-822225379). 😢

**Comment by Sean-Holcomb** [comment]
@pierluigilenoci I can get similar results on an AKS cluster:
![Screen Shot 2021-04-21 at 2 05 55 PM](https://user-images.githubusercontent.com/12225425/115622177-5d666b80-a2ac-11eb-9fd3-85193cc48c31.png)
![Screen Shot 2021-04-21 at 2 15 55 PM](https://user-images.githubusercontent.com/12225425/115622179-5d666b80-a2ac-11eb-80cb-38a7912a89f9.png)

Can you try running an asset etl rebuild followed by an allocation rebuild and see if you get the same warning.
`/model/etl/assets/rebuild?window=all&commit=true`

**Comment by pierluigilenoci** [comment]
Asset rebuild:
```json
{"code":200,"data":"Rebuilding Asset ETL"}
```
Result:
```
I0422 07:47:53.566453       1 log.go:62] [Profiler] 22.735901ms: Asset ETL: build[zGSEt]: coverage [2021-01-22T00:00:00+0000, 2021-04-23T00:00:00+0000) (100.0% complete)
I0422 07:47:53.566468       1 log.go:62] [Profiler] 14.964029096s: Asset ETL: build[zGSEt] total elapsed time
```
Allocation rebuild:
```json
{"code":200,"data":"Rebuilding Allocation ETL"}
```
Result:
```
I0422 07:52:20.549272       1 log.go:62] [Profiler] 41.369848ms: Allocation ETL: build[VOGDx]: coverage [2021-01-22T00:00:00+0000, 2021-04-23T00:00:00+0000) (100.0% complete)
I0422 07:52:20.549279       1 log.go:62] [Profiler] 1m46.173687804s: Allocation ETL: build[VOGDx] total elapsed time
```
I did it in two clusters, same UI result, nothing changed:
<img width="1538" alt="Prod Cluster" src="https://user-images.githubusercontent.com/36044817/115678260-9c9ac800-a351-11eb-9570-02f3f665d558.png">

Report generated with this filter, maybe this can be the problem?
<img width="711" alt="Screenshot 2021-04-22 at 09 58 13" src="https://user-images.githubusercontent.com/36044817/115678344-b3411f00-a351-11eb-8add-9cd303bda1bd.png">

**Comment by pierluigilenoci** [comment]
I checked also in AWS and the situation is even worst. Some EC2 instances are not listed at all and the resources are not tagged properly.

Kubecost UI:
<img width="1532" alt="Screenshot 2021-04-22 at 10 03 25" src="https://user-images.githubusercontent.com/36044817/115680316-c0f7a400-a353-11eb-95a8-9ea1763bf4e4.png">

<img width="1539" alt="Screenshot 2021-04-22 at 10 21 06" src="https://user-images.githubusercontent.com/36044817/115681091-7b87a680-a354-11eb-8763-c8466f1d0e3d.png">

Let's take for example a volume of one instance.

In Cost-Analyzer
<img width="1536" alt="Screenshot 2021-04-22 at 10 14 05" src="https://user-images.githubusercontent.com/36044817/115680229-ad4c3d80-a353-11eb-99a8-ad8c082de7d4.png">

In AWS EC2
<img width="1307" alt="Screenshot 2021-04-22 at 10 14 25" src="https://user-images.githubusercontent.com/36044817/115680258-b3dab500-a353-11eb-9e5c-e83a52a4fd3f.png">

Configuration of Cost-Analyzer:
```yaml
kubecostProductConfigs:
  labelMappingConfigs:
    enabled: true
    team_label: "akelius_team"
    team_external_label: "akelius_team"
    department_label: "akelius_project"
    department_external_label: "akelius_project"
    product_label: "akelius_project"
    product_external_label: "akelius_project"
    environment_label: "akelius_environment"
    environment_external_label: "akelius_environment"
    cluster_external_label: "akelius_cluster"
```

Did I do something wrong? 

Note: I launched the two rebuild procedures on all clusters (both Azure and AWS).

**Comment by pierluigilenoci** [comment]
@Sean-Holcomb any other test to do? How can I proceed?

**Comment by Sean-Holcomb** [comment]
@pierluigilenoci This is still on my radar, I will try and get you some next steps today

**Comment by Sean-Holcomb** [comment]
@pierluigilenoci I can see that for AWS you have your external labels set in value.yaml and the resource itself is properly tagged, but there is actually one other thing on AWS. Can you confirm that you have finished step 3 of this [doc](http://docs.kubecost.com/aws-out-of-cluster.html)
It should look something like this
![Screen Shot 2021-04-26 at 5 18 01 PM](https://user-images.githubusercontent.com/12225425/116166744-82474e00-a6b3-11eb-9a9a-451c01c9a376.png)
You can also check the line item related to that volume in your CUR and make sure that label actually shows up in the tags.

> Some EC2 instances are not listed at all
Can you describe these missing instances a bit more, are they volumes or nodes or both, started recently or older?

**Comment by pierluigilenoci** [comment]
@Sean-Holcomb Now I have enabled all the "User-Defined Cost Allocation Tags".
I'll wait a few hours and see if things change. This could be solved. Thanks in advance!

What about Azure?

**Comment by Sean-Holcomb** [comment]
@pierluigilenoci
Could the comment here be relevant to your case?
https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L323

Could you also check that the cluster_id is correct in your prometheus config
![Screen Shot 2021-04-27 at 2 28 11 PM](https://user-images.githubusercontent.com/12225425/116315236-19201300-a765-11eb-9970-515142165f76.png)
I know you put up a picture of your prometheus.yml in an earlier post, where exactly was that image taken from?

I am also seeing the value being set in the deployment for kubecost-cost-analyzer using `helm get manifest kubecost`
```
- name: CLUSTER_ID
  value: network-test
```

**Comment by pierluigilenoci** [comment]
The `prometheus.yaml` image is a screenshot of the configMap taken from the cluster dashboard. 
If you prefer to have one take from the Prometheus UI, please be my guest. 😄 

<img width="479" alt="Screenshot 2021-04-28 at 11 34 35" src="https://user-images.githubusercontent.com/36044817/116382410-2e08af00-a816-11eb-8e80-018b1b6a13ba.png">

In my manifest I have:
```yaml
            - name: CLUSTER_ID
              value: cluster-one
```

I checked the chart and understood the matter. All your tests are based on an installation with dedicated Prometheus and not with a custom Prometheus like our case. 

This part of the chart under the microscope: 
```yaml
            {{- if and (.Values.prometheus.server.global.external_labels.cluster_id) (not .Values.prometheus.server.clusterIDConfigmap) }}
            - name: CLUSTER_ID
              value: {{ .Values.prometheus.server.global.external_labels.cluster_id }}
            {{- end }}
            {{- if .Values.prometheus.server.clusterIDConfigmap }}
            - name: CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.prometheus.server.clusterIDConfigmap }}
                  key: CLUSTER_ID
            {{- end }}
```

In this way, the `CLUSTER_ID` value is set correctly only if you install Prometheus with your chart. For those with a separate installation, it doesn't work.

I added the configuration in the chart as a workaround to see if it works but certainly, this is a bug of the chart.

**Comment by pierluigilenoci** [comment]
@AjayTripathy @Sean-Holcomb I created a ticket for that https://github.com/kubecost/cost-analyzer-helm-chart/issues/869

**Comment by Sean-Holcomb** [comment]
@pierluigilenoci Sounds like you think that this is your underlying issue here. Can we close this issue since your new ticket is more specific?

**Comment by pierluigilenoci** [comment]
@Sean-Holcomb now Azure cost are fine but AWS problem is still there. Do you prefer to continue here or I create a new issue for AWS only? I prefer to continue here.

**Azure is ok!**
<img width="1531" alt="Azure now is fine" src="https://user-images.githubusercontent.com/36044817/116434504-c02aaa80-a84a-11eb-88e0-866613a8d80b.png">

**For AWS** (just a recap):

* Configuration of Cost-Analyzer
```yaml
kubecostProductConfigs:
  labelMappingConfigs:
    enabled: true
    team_label: "akelius_team"
    team_external_label: "akelius_team"
    department_label: "akelius_project"
    department_external_label: "akelius_project"
    product_label: "akelius_project"
    product_external_label: "akelius_project"
    environment_label: "akelius_environment"
    environment_external_label: "akelius_environment"
    cluster_external_label: "akelius_cluster"
```

* CUR  Billing interface
<img width="1087" alt="Screenshot 2021-04-28 at 17 55 21" src="https://user-images.githubusercontent.com/36044817/116434825-0b44bd80-a84b-11eb-8ec3-ba1a0a693447.png">

* AWS ES console
<img width="851" alt="Screenshot 2021-04-28 at 18 00 03" src="https://user-images.githubusercontent.com/36044817/116435494-b5244a00-a84b-11eb-8f16-d90ead9eecf4.png">

I enabled the Cost Allocation Tags yesterday, this morning I redeployed the software with the correct `CLUSTER_ID` and a few minutes ago I ran the Allocation rebuild and Asset rebuild. 

This is the result of the Kubecost UI. I did it for all environments (4 different clusters). In all clusters, the Assets are all with the "No cluster" label.
<img width="1544" alt="Screenshot 2021-04-28 at 18 00 30" src="https://user-images.githubusercontent.com/36044817/116435584-cf5e2800-a84b-11eb-9a46-73794be046c5.png">
<img width="649" alt="Screenshot 2021-04-28 at 18 09 23" src="https://user-images.githubusercontent.com/36044817/116437091-5b248400-a84d-11eb-969a-6c109a964f63.png">

Any suggestions on how to move forward?

**Comment by Sean-Holcomb** [comment]
@pierluigilenoci Yeah we can just continue here. Glad to hear Azure is working now. Can you go into Athena and make sure that your CUR table has columns for your added tags like this `resource_tags_user_foo (string)` after that look at you query history for queries along the lines 
```
SELECT
	line_item_usage_account_id,
	line_item_resource_id,
	line_item_product_code,
	line_item_usage_type,
	line_item_usage_start_date,
	line_item_usage_end_date,
	line_item_blended_cost,
	resource_tags_user_foo ...
```
Lastly can you look for a couple specific line items you know are tagged and make sure the value is populating.
You can trigger more athena queries with an assets ETL rebuild `/model/etl/assets/rebuild?window=all&commit=true`

**Comment by pierluigilenoci** [comment]
Athena is properly popolated.

<img width="406" alt="Screenshot 2021-04-28 at 19 29 06" src="https://user-images.githubusercontent.com/36044817/116447614-7943b180-a858-11eb-92dc-c730aaf5a6a8.png">
<img width="1311" alt="Screenshot 2021-04-28 at 19 32 09" src="https://user-images.githubusercontent.com/36044817/116447628-7cd73880-a858-11eb-9bbf-3a196b606847.png">

Inside the query history I found this:
```sql
SELECT
			line_item_usage_account_id,
			line_item_resource_id,
			line_item_product_code,
			line_item_usage_type,
			line_item_usage_start_date,
			line_item_usage_end_date,
			line_item_blended_cost,
resource_tags_user_akelius_team,
resource_tags_user_akelius_cluster,
resource_tags_user_akelius_project,
resource_tags_user_kubernetes_io_created_for_pvc_namespace,
resource_tags_user_akelius_environment
		FROM akeliuscurathena as cost_data
		WHERE NOT (line_item_usage_end_date < CAST('2021-03-28' AS DATE) OR line_item_usage_start_date > CAST('2021-04-29' AS DATE))
		AND line_item_resource_id <> ''
```
with this result:
<img width="1695" alt="Screenshot 2021-04-28 at 19 35 42" src="https://user-images.githubusercontent.com/36044817/116448088-01c25200-a859-11eb-8756-eb6a25cf01e1.png">

I manually run this query:
```sql
SELECT
			line_item_usage_account_id,
			line_item_resource_id,
			line_item_product_code,
			line_item_usage_type,
			line_item_usage_start_date,
			line_item_usage_end_date,
			line_item_blended_cost,
resource_tags_user_kubernetes_io_created_for_pvc_namespace,
resource_tags_user_akelius_environment,
resource_tags_user_akelius_project,
resource_tags_user_akelius_cluster,
resource_tags_user_akelius_team
		FROM akeliuscurathena as cost_data
		WHERE resource_tags_user_akelius_cluster = 'production.aws.akelius.com'
		AND line_item_resource_id <> ''
```

And I get
<img width="1312" alt="Screenshot 2021-04-28 at 19 39 41" src="https://user-images.githubusercontent.com/36044817/116448601-975de180-a859-11eb-8a38-d3ab1bed406b.png">
<img width="1322" alt="Screenshot 2021-04-28 at 19 39 52" src="https://user-images.githubusercontent.com/36044817/116448609-9927a500-a859-11eb-954b-f17a01d9ca49.png">

It seems all right to me.

**Comment by Sean-Holcomb** [comment]
@pierluigilenoci Ok that is all looking good, my last question is, in Kubecost for the assets that have no cluster that you know are tagged with cluster, are there duplicates with a cluster?

**Comment by pierluigilenoci** [comment]
@Sean-Holcomb sorry but I think I don't understand the question but I try to answer anyway.

All clusters are linked to the same CUR as the master account so they collect data from all AWS accounts we have, not just those linked to K8s. So each Kubecost instance imports all the data so I find in each instance all the data of all the accounts. However, there are no duplicates within each Kubecost instance. Whether the assets are tagged or not (in AWS, in Kubecost all appear untagged).

**Comment by Sean-Holcomb** [comment]
@pierluigilenoci I was trying to determine if older data points for an asset did not have the cluster but newer ones did because it was not an exported tag/Athena column until recently. When assets are aggregated, cluster is part of the key they are aggregated on, so if older data points did not have cluster, but newer ones did I would expect to see one line item still with product id vol-01bc... and no cluster and a second one with the newer data points with product id vol-01bc... and the correct cluster. It sounds like this is not the case though.

When you look at this endpoint `/model/assets?window=6d&aggregate=&accumulate=false&filterServices=AmazonEC2` 
can you find an Asset that you know is labeled. What do you see.
![Screen Shot 2021-04-28 at 11 37 56 AM](https://user-images.githubusercontent.com/12225425/116455777-5395b880-a816-11eb-9054-20dede488efe.png)
I am specifically looking to see that the cluster is unset in the properties object and hoping to see the correct values in the labels object. If this is the case I have a good idea of what needs to be done.

**Comment by pierluigilenoci** [comment]
<img width="765" alt="Screenshot 2021-04-28 at 21 38 20" src="https://user-images.githubusercontent.com/36044817/116462996-6e921800-a86a-11eb-9949-70693e14f02e.png">
<img width="1426" alt="Screenshot 2021-04-28 at 21 39 05" src="https://user-images.githubusercontent.com/36044817/116463014-73ef6280-a86a-11eb-95bc-5b30dcca51e2.png">
<img width="1420" alt="Screenshot 2021-04-28 at 21 40 19" src="https://user-images.githubusercontent.com/36044817/116463040-7e116100-a86a-11eb-8dc2-b997f6400196.png">

I'll try to check also tomorrow and the day after tomorrow to see if something change.

**Comment by pierluigilenoci** [comment]
In Athena the tags are listed only from 9 am of yesterday.

<img width="1255" alt="Screenshot 2021-04-28 at 21 47 07" src="https://user-images.githubusercontent.com/36044817/116463717-5373d800-a86b-11eb-8dae-693f382ee552.png">

This data is not imported to date in Kubecost. Waiting 24 hours can make sense.

**Comment by Sean-Holcomb** [comment]
@pierluigilenoci You answered my question before I even asked it. Please let me know what you find tomorrow. Thank you

**Comment by pierluigilenoci** [comment]
Finally!
Assets are tagged...
<img width="1089" alt="Screenshot 2021-04-30 at 16 53 26" src="https://user-images.githubusercontent.com/36044817/116713034-ba60d080-a9d4-11eb-8c0b-45cbc017fec5.png">
... and external costs are there! 🚀 
<img width="1322" alt="Screenshot 2021-04-30 at 16 54 09" src="https://user-images.githubusercontent.com/36044817/116713039-bcc32a80-a9d4-11eb-9424-73da5c437429.png">

This issue can be closed, thanks! ❤️ 

The data is imported. Now the thing is, there are too many... there is data for all the AWS accounts in the AWS Organization. I'll open a feature request about it. 😄

**Comment by Sean-Holcomb** [comment]
@pierluigilenoci Awesome! I am glad we were able to work through these issue.

**Comment by pierluigilenoci** [comment]
Another "not-so-small" related update: https://github.com/kubecost/cost-model/issues/787 😢
