### ISSUE TITLE
Feature request: better SAML Integrations with more granularity

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-model#765]
We would like to be able to give access with more granularity within the Kubecost interface. 

For example, assuming there is a SAML group of project XXX users. We would like that in the Kubecost UI only costs related to the product equal to XXX were visible to this group. Or give visibility based on the various [labels](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L610-L626)

We would like to be able to manage these assignments via API because it is not possible to think of configuring something like this manually.

**Comment by dwbrown2** [comment]
This should now be supported in Enterprise Kubecost.

**Comment by AjayTripathy** [comment]
Auth support and SAML integrations often have a pretty hefty lift on the support side, and occasionally custom work depending on SAML provider ,so we feel we can't provide a good experience on the open source model. Closing as this is now supported on enterprise.
