### ISSUE TITLE
Add ability to add tokens to intra-app communication

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-model#77]
The app has to talk to prometheus to run. This is causing problems such as #74 where TLS is enabled and requests need to be authorized. We should support injecting auth tokens into these requests.

**Comment by dwbrown2** [comment]
Can't you just configure `server.ingress.tls` in the Prometheus helm chart to accomplish this?

**Comment by AjayTripathy** [comment]
Yes-- let's close this and add an issue on the helm chart to add a sample of how this is done in comments. 

Added https://github.com/kubecost/cost-analyzer-helm-chart/issues/62
