### ISSUE TITLE
[FR] Add support to custom cluster_id label

### ISSUE THREAD

**Issue by ltagliamonte-dd** [kubecost/cost-model#772]
In some complex environments where all metrics already carries a "cluster label"  that isn't `cluster_id` would be nice to have the option to be able to specify the label key to use instead of `cluster_id`.

Currently `cluster_id` is a string sparse all around the code, would be nice to be able to specify it via env var.
If the community thinks that a valid option I will be happy to contribute.

**Comment by dwbrown2** [comment]
@ltagliamonte-dd we've discussed with a number of users and we would definitely be supportive if you're interested in collaborating on this!

although this might be need to be a multi-part PR because I know this value is used in many places. but even if we just begin the process of templating it in several places then it should help with framing the solution.

**Comment by ltagliamonte-dd** [comment]
Hello @dwbrown2 thank you for the feedback, to use the cost model in my env i went ahed with some changes.. you can see the diff [here](https://github.com/kubecost/cost-model/compare/develop...ltagliamonte-dd:cluster_id_label?expand=1)
The approach isn’t the best, definitely needs cleanup but i'd love to hear from you.

**Comment by dwbrown2** [comment]
Amazing! I think @nikovacevic or @michaelmdresser could be best to take a look... would either of you be able to early next week?

**Comment by nikovacevic** [comment]
@dwbrown2 I'll do a quick review today.

@ltagliamonte-dd thank you for offering your work as a contribution!

**Comment by nikovacevic** [comment]
I think this proposal looks very reasonable. My initial feedback is:
- we'd have to make changes to the non-open-source product as well, following on from this (not an issue, just some extra work)
- we might want to talk about the naming of the environment variable
- we'll want to do some full testing of all the queries to make sure that they are correct, but they look right from a first read-through

**Comment by ltagliamonte-dd** [comment]
@nikovacevic please let me know where to go from here.

**Comment by nikovacevic** [comment]
@ltagliamonte-dd we will let you know soon. Thank you!

**Comment by ltagliamonte-dd** [comment]
Hello, any updates on this?

**Comment by nikovacevic** [comment]
Hi @ltagliamonte-dd. Yes, we discussed it this morning and have decided to move forward with your proposal. Do you mind opening a PR? We'll prioritize reviewing it and making the other necessary changes on our end this week or next.

**Comment by ltagliamonte-dd** [comment]
@nikovacevic i opened the PR, please fee free to fork it, atm i don't know if i can work on this since my priorities have changed.

**Comment by nikovacevic** [comment]
Thank you @ltagliamonte-dd we will take it from here!

**Comment by AjayTripathy** [comment]
This is done and in production!
