### ISSUE TITLE
How is the cost of the pod calculated?

### ISSUE THREAD

**Issue by KevinKingKong** [kubecost/cost-model#79]
I read the source code of the cost-model and only saw the calculation logic of the node cost. I understand that users should prefer to see the cost of a single Pod or Single Container.

`
router.GET("/costDataModel", a.CostDataModel) 
router.GET("/costDataModelRange", a.CostDataModelRange)
`
The above code only returns the pricing of the node and the resource usage of the container.

Is the calculation logic for pod and container costs implemented externally?

**Comment by dwbrown2** [comment]
@KevinKingKong is the first question/answer helpful here? 
https://github.com/kubecost/cost-model#questions

The functions in [costmodel.go](https://github.com/kubecost/cost-model/blob/master/costmodel/costmodel.go) do a cost calculation by container and then you can aggregate from here. 

Let me know if this doesn't answer or if you have other questions.

**Comment by dwbrown2** [comment]
@KevinKingKong let me know if I can provide more detail here!

**Comment by dwbrown2** [comment]
Going to mark as closed for now, but please feel free to reopen any time if you want to discuss further!
