### ISSUE TITLE
Discrepancy in the Saving panels 

### ISSUE THREAD

**Issue by pierluigilenoci** [kubecost/cost-model#793]
Following the documentation, we have configured the various namespaces with the [Availability Tiers](https://github.com/kubecost/docs/blob/master/availability-tiers.md). 

I expected the suggestions proposed by the "Saving - Request Sizing Recommendations" page to respect the configured tier. 

<img width="857" alt="Screenshot 2021-05-07 at 12 11 24" src="https://user-images.githubusercontent.com/36044817/117435885-a0704200-af2e-11eb-8c58-0fe54bfcef5f.png">
<img width="1565" alt="Screenshot 2021-05-07 at 12 12 09" src="https://user-images.githubusercontent.com/36044817/117435894-a36b3280-af2e-11eb-844f-f68a6a6b22c5.png">

In my opinion, the result of the API without any options should filter according to the configurated tier.

**Comment by dwbrown2** [comment]
Dedicated namespace page, e.g. <your-kubecost-url>/namespace.html?name=kubecost

**Comment by pierluigilenoci** [comment]
Really interesting. I tried to understand what is the REST call that builds this is but I couldn't figure it out. Can you help me?

<img width="535" alt="Screenshot 2021-05-12 at 15 45 33" src="https://user-images.githubusercontent.com/36044817/117985565-1adb0080-b339-11eb-9988-273882f8b522.png">

**Comment by dwbrown2** [comment]
Can you share a bit more about the specific information that would be most helpful?

**Comment by pierluigilenoci** [comment]
The information I would like to have is simply the list of pods with current and recommended memory / cpu by namespace. Obtained with one or more rest calls (preferably one)

**Comment by pierluigilenoci** [comment]
This page also has a discrepancy in values with the dedicated namespace page mentioned by @dwbrown2.

Let's take for example two pods ([kube-slack](https://github.com/wongnai/kube-slack) and [kubernetes-dashboard](https://github.com/kubernetes/dashboard)), "Saving - Request Sizing Recommendations" page with the correct tier selected in the drop-down list, 7 days timespan:

<img width="1553" alt="Screenshot 2021-05-17 at 16 58 08" src="https://user-images.githubusercontent.com/36044817/118510455-455dfc80-b731-11eb-8749-26bbf1e40f35.png">
<img width="1210" alt="Screenshot 2021-05-17 at 16 58 17" src="https://user-images.githubusercontent.com/36044817/118510486-4b53dd80-b731-11eb-8c38-0b7c0bae51a0.png">

These are the results:  

# Kube-Slack

<img width="538" alt="Screenshot 2021-05-17 at 16 25 36" src="https://user-images.githubusercontent.com/36044817/118509110-11cea280-b730-11eb-8579-91976f16bc2f.png">

<img width="1263" alt="Screenshot 2021-05-17 at 16 58 40" src="https://user-images.githubusercontent.com/36044817/118510575-5e66ad80-b731-11eb-9228-50add0acd282.png">

# Dashboard

<img width="540" alt="Screenshot 2021-05-17 at 16 27 10" src="https://user-images.githubusercontent.com/36044817/118509766-a33e1480-b730-11eb-8309-c9afd22739fa.png">

<img width="1268" alt="Screenshot 2021-05-17 at 16 58 50" src="https://user-images.githubusercontent.com/36044817/118510616-69b9d900-b731-11eb-9b50-699c7193fa7d.png">

What am I doing wrong?

**Comment by pierluigilenoci** [comment]
@dwbrown2 any feedback?

**Comment by pierluigilenoci** [comment]
@dwbrown2 two months have passed, is there any news?

**Comment by dwbrown2** [comment]
Planned for this week, thanks.

**Comment by pierluigilenoci** [comment]
@dwbrown2 any news about this?

**Comment by dwbrown2** [comment]
This should be resolved in 1.84. @nikovacevic would you be able to confirm?

**Comment by nikovacevic** [comment]
That's correct.

**Comment by dwbrown2** [comment]
Thanks! Marking as closed, but please reopen if there are questions.
