### ISSUE TITLE
Add storage costs to data model

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-model#80]
The cost model currently has PV size, storageclass, etc. I propose we also add cost per Gb hour of storage. 

On __GCP__ this cost is a function of _region_, _storageClass_, and _isRegional_ (i.e. replication across two AZs in a region). The GCP billing API has top level entries for `ssd` and `pdstandard` storageClasses. 

My option is that supporting isRegional=true is P2 for this initial implementation. To support this type properly, we will need to look at the underlying storageClass and it's replication-type. More info here: https://cloud.google.com/solutions/using-kubernetes-engine-to-deploy-apps-with-regional-persistent-disks.

I propose we have also have a fallback price (e.g. SSD and PDStandard) in default.json in case these metrics aren't found in billing data.

**Comment by AjayTripathy** [comment]
#81 does this for currently existing storage classes on GCP

**Comment by AjayTripathy** [comment]
Merged for GCP, though we still need the isRegional test-- still need to do for AWS.
