### ISSUE TITLE
Annotations for owner/team cost allocation seem to be ignored

### ISSUE THREAD

**Issue by danlester** [kubecost/cost-model#803]
Hello!

I have installed version 1.80.0 via Helm chart. The [documentation](http://docs.kubecost.com/cost-allocation.html) seems to suggest that owner/team etc cost allocations can be made either through labels or annotations.

However, annotations seem to be ignored. Labels work fine.

Is it possible to use annotations for this purpose? This could be preferable, not least because it gives a wider character set range, but also because some deployment tools can only set annotations.

Thank you very much.

**Comment by kbrwn** [comment]
hi @danlester, thanks for reporting this issue. Let's try to confirm through debugging if this is a configuration issue or bug. Could you send more info such as the values.yaml file or helm command used to launch kubecost to support@kubecost.com?

**Comment by danlester** [comment]
OK thank you, I've sent an email.

To be clear though, it's entirely possible you don't support annotations - some of your GitHub issues etc suggest not any more.

**Comment by dwbrown2** [comment]
@danlester we do support annotations in cost allocation. But these actually need to be enabled. They are disabled by default because for some teams they can generate a lot of new Prometheus metrics.

**Comment by AjayTripathy** [comment]
Hi @danlester , you can turn these on with, for example,

--set kubecostMetrics.emitPodAnnotations=true
--set kubecostMetrics.emitNamespaceAnnotations=true

**Comment by danlester** [comment]
Thank you for letting me know - definitely one for the docs! By the way, some of the pages in your docs only seem to appear via the right Google search, and don't seem to be linked internally.

**Comment by dwbrown2** [comment]
Great suggestion, @danlester. We have [this annotations resource](https://github.com/kubecost/docs/blob/ef803156421396b0db30a655d1240244a9346931/annotations.md) but we'll link from cost allocation page.

We're also going to be investigating other docs solutions soon to provide easier discoverability.
