### ISSUE TITLE
"Assumed use discount"  should be renamed "Sustained use" discount

### ISSUE THREAD

**Issue by kbrwn** [kubecost/cost-model#818]
We should be matching terminology used by GCP: https://cloud.google.com/compute/docs/sustained-use-discounts

<img width="495" alt="assumed use discount" src="https://user-images.githubusercontent.com/4100493/119904432-38929300-beff-11eb-999d-9532cc662091.png">

gz#330

**Comment by dwbrown2** [comment]
+1, I think we should update title & subtitle

**Comment by AjayTripathy** [comment]
I think we should actually just remove this. This is actually 3 numbers  (30% on n1, 20% on n2, 0% on e2) and is no longer controlled by user input. Users should instead use "negotiated discount" to supply flat discounts on the cluster.

**Comment by dwbrown2** [comment]
That approach doesn't seem right... you're assuming that each user receives
the full sustained use discount, which is not always true. Why not support
an estimated % of possible discount realized?

Webb
Kubecost, Co-founder

ᐧ

**Comment by AjayTripathy** [comment]
Ok-- how abou "Estimated Sustained Use Discount?"

**Comment by dwbrown2** [comment]
I like that idea! 

And this value would get scaled by instance type? For example, would never be applied to e2?

**Comment by AjayTripathy** [comment]
Right now a fixed 0% gets applied to e2 and a fixed 20% gets applied to n2... so it's "scaled" to e2 but not to n2.

I think the proposal makes sense but let's not blow up the scope here.

**Comment by AjayTripathy** [comment]
"Estimated Sustained Use Discount (GCP Only)" is the name here.
