### ISSUE TITLE
Is this free or not? It's not clear

### ISSUE THREAD

**Issue by alexmnyc** [kubecost/cost-model#838]
When going to get the helm chart there is a clause about pricing. Please clarify if installing this supposedly OSS product requires paying for it or not. The installation seems to require a token 
```
helm install kubecost kubecost/cost-analyzer \
    --namespace kubecost \
    --set kubecostToken=...
```

gz#443

**Comment by dwbrown2** [comment]
@alexmnyc this project is both free and open source. 

Kubecost itself is "open-core" and you can find all of our free install paths available here: http://docs.kubecost.com/install. You can optionally upgrade over to a paid plan if you like the community release and want more features, but it's definitely not required!

Let me know if you feel we can share more of update our documentation to be more helpful.

**Comment by alexmnyc** [comment]
So can I use it on multiple clusters at work without any support plans? Or do I have to pay a fee. Typically OSS projects are free and companies make money by providing enterprise features and/or support plans. Before i try to pitch the product at work I need to understanding the cost model

**Comment by kbrwn** [comment]
Hi @alexmnyc , the code you see in this repo is free and open source and can be installed via kubernetes manifest with no limitations. The [helm chart](https://github.com/kubecost/cost-analyzer-helm-chart/) installs kubecost community edition, which many individual users will be able to use for free and is based around the open core product in this repository. Check https://www.kubecost.com/pricing for details on the features that come with our community, business and enterprise editions.

**Comment by alexmnyc** [comment]
Ok. So I can install the product as a manifest myself without limitations on as many clusters as I need but usage of the helm chart you provide is subject to the commercial licensing beyond one free cluster. Is that correct?

**Comment by kbrwn** [comment]
@alexmnyc yes that is correct.

**Comment by alexmnyc** [comment]
Thank you for clarifying it

**Comment by valentinpetrov-trading** [comment]
is this still the case , i am looking for free solution as kubecost have cpu limitation over which we need license

**Comment by kwombach12** [comment]
@valentinpetrov-trading yes - OpenCost will ALWAYS be a free, open-sourced project. In fact, OpenCost was recently promoted to "Incubation" by the CNCF: https://www.opencost.io/blog/cncf-incubation

**Comment by valentinpetrov-trading** [comment]
Awesome!!

i was curious to ask for another issue i am facing, when i run opencost through helm chart in eks and prometheus shards are scraping the cluster, i point the opencost to connect to a central prometheus, and i start getting enriched metrics for lets say container_cpu_allocation but for some reason the node and instance label are both  as IP:PORT which i cannot use for mapping, 

 when i disconnected the prometheus i saw the queries in the error log in the opencost pod, seems there is some relabelling that is happening but i am not completely sure why this happens. 

I tried to enforce relable configuration in the helm chart to not modify the node label to be in style ip-10-15-12... etc but it did not work, each time i hit opencost:9003/metrics i see duplicated metrics with different node and instance labels. I would be extremely grateful if you could hint me what might be the reason for this situation. 

P.S:  i tried the kubecost addon from the eks addons and it seemed that provides correct values for instance and node labels, AWS mentions its slightly different version of kubecost and i was also wondering if the licensing limits apply for cpu per cluster?

**Comment by kwombach12** [comment]
@valentinpetrov-trading I'm not the best person to help you debug this issue - would suggest you create a new GH issue for this so a maintainer can assist. The EKS-add on version of Kubecost does not have any cpu limits. You can read more about this in our 2.0 packaging blog post: https://blog.kubecost.com/blog/kubecost-2.0-packaging/
