### ISSUE TITLE
Gpu metrics don't go away after node is deleted

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-model#84]
It looks like the model keeps emitting 0 for `node_gpu_hourly_cost` on the /metrics endpoint even after the node has been deleted. This appears low priority because it doesn't have an impact on actual metrics, it only creates empty metrics when we shouldn't.

**Comment by dwbrown2** [comment]
@AjayTripathy I believe you just pushed a fix?

**Comment by AjayTripathy** [comment]
Yes, this has been fixed.
