### ISSUE TITLE
Default shared tenancy costs to false and provide setting to turn on

### ISSUE THREAD

**Issue by nikovacevic** [kubecost/cost-model#854]
We've had several reports of inexplicable behavior from our own developers (not to mention our users, who will surely have the same question) with regard to the appearance of substantial shared costs when no shared namespaces, labels, or overhead are set. After some investigation, we found that they are coming from the relatively new "shared tenancy cost" feature, which defaults to "true" and does offers explanation in neither the UI nor the API responses.

As one of the reviewers, I take some responsibility for approving this design; furthermore, I believe it speaks to how pernicious it is that even a reviewer of the feature can be caught off-guard by the strangeness of the results.

I propose we default this flag to "false" and provide a setting in the UI that enables the feature by sending requests to the API with `sharedTenancyCosts=true` so that the requests is always explicit.

gz#488

**Comment by nikovacevic** [comment]
A workaround in the meantime to is to pass `sharedTenancyCosts=false` with Allocation API calls.

**Comment by AjayTripathy** [comment]
We did this in part to address the question "Why do my k8s costs differ from my total cloud costs? I just want to match them to my bill"-- or at least to reduce any gaps there. It seems logical to break those out into a separate column and allocate them as they should be allocated. I _think_ that any questions are just as a result of people familiar to kubecost coming to expect _only_ k8s costs on the allocation page.

**Comment by nikovacevic** [comment]
That's fair, and it's good context for the discussion. With that context, we have several questions to answer:
- What percentage of users want this behavior? Right now, 100% of users will get it 100% of the time, which I suspect differs from the rate of users asking for their k8s allocation costs to match their total cloud costs, especially with idle allocation off.
- Even if we default this setting to "true," should we do so through the UI so that the API request is explicit? Without it being explicit, you end up with shared costs and no discernible way to turn them off. 
- Regardless of defaults, how can we communicate this better? Do we need a separate column? I suspect we'd be fine using the "shared costs" column, as long as the action to share the costs is made explicit, but I'm open to adding a new column as well.

**Comment by Sean-Holcomb** [comment]
I think adding a column is overkill, since it is a feature that can be turned off. It would increase the visual complexity of the page and expand the allocation schema again. I think adding a control with explanation, which includes having it in the api call from the FE, makes the most sense and is the most flexible.

**Comment by nikovacevic** [comment]
Agree with @Sean-Holcomb, personally. I'd even advocate for such a control to be placed with the rest of the shared costs controls in the Settings page, so that we don't even need to add anything to the Allocation page controls. Open to other ideas there.

**Comment by michaelmdresser** [comment]
> A workaround in the meantime to is to pass sharedTenancyCosts=false with Allocation API calls.

Wherever this lands, we should at least add the `shareTenancyCosts` flag to the Allocation API instructions: https://github.com/kubecost/docs/blob/master/allocation.md#querying

**Comment by Sean-Holcomb** [comment]
@michaelmdresser that one is my bad, I had the updates but didn't push them [104](https://github.com/kubecost/docs/pull/104)

**Comment by nikovacevic** [comment]
Thanks, @Sean-Holcomb, that's a huge improvement.

**Comment by nikovacevic** [comment]
Improved in https://github.com/kubecost/cost-model/pull/864
