### ISSUE TITLE
kubecost UI display nothing

### ISSUE THREAD

**Issue by kitianFresh** [kubecost/cost-model#862]
Hi Team, any one can help me?  i write an provider for qcloud, and i test my cost model api is ok, but the ui always display nothing.

when debug chrome, i found there are some apis not found, it is strange

![image](https://user-images.githubusercontent.com/8846958/124612606-0c2a4900-dea5-11eb-965c-a234bc0cece1.png)

my cost model service is ok, and i can request the api such as allNodePricing
![image](https://user-images.githubusercontent.com/8846958/124614204-97580e80-dea6-11eb-9747-2a9b3649e484.png)

following is prometheus cost data
![image](https://user-images.githubusercontent.com/8846958/124614061-755e8c00-dea6-11eb-92e1-7c92a64f048c.png)

gz#509

**Comment by AjayTripathy** [comment]
Hi @kitianFresh happy to help. Any chance you could go through some of the troubleshooting steps here about loading the app and let us know what you find? https://github.com/kubecost/docs/blob/master/troubleshoot-install.md#issue-unable-to-load-app

**Comment by kitianFresh** [comment]
> Hi @kitianFresh happy to help. Any chance you could go through some of the troubleshooting steps here about loading the app and let us know what you find? https://github.com/kubecost/docs/blob/master/troubleshoot-install.md#issue-unable-to-load-app

I replace  {% raw %}{{ $serviceName }}.{{ .Release.Namespace }}{% endraw %}  with localhost in the cost-analyzer-frontend-config-map-template.yaml
![image](https://user-images.githubusercontent.com/8846958/124697039-b8f1de00-df18-11eb-94c4-4997f4846715.png)

and following is the real configmap after i installed kubecost
![image](https://user-images.githubusercontent.com/8846958/124697241-0a9a6880-df19-11eb-9677-5cbdea5a0e10.png)

**Comment by AjayTripathy** [comment]
It shouldn't, are you able to try port-forwarding instead of visiting via your ingress/loadbalancer?

**Comment by kitianFresh** [comment]
> It shouldn't, are you able to try port-forwarding instead of visiting via your ingress/loadbalancer?

Yes, i use the load balancer in cloud before. but i also use port-forwarding in my local mac machine to test your method, but it does not work.

i found the image build by your team has some api  which is not found in open source version in cost-model.   these api will affect the UI?  and what the cost-model branch and tag you team use, i use the develop branch

![image](https://user-images.githubusercontent.com/8846958/124699340-361f5200-df1d-11eb-807a-e64a782e246c.png)

**Comment by AjayTripathy** [comment]
AH-- that makes sense, yes we use our open-core as a library on top of our community edition which adds things like key management. 

To test changes to the open core-- can you try following these instructions to build/test/deploy? https://github.com/kubecost/cost-model/blob/develop/CONTRIBUTING.md#building

**Comment by kitianFresh** [comment]
cost-model is ok, and  test all passed

![image](https://user-images.githubusercontent.com/8846958/124704970-86031680-df27-11eb-817c-8ff6394f3d7b.png)

**Comment by AjayTripathy** [comment]
Awesome! Looking forward to the PR!

**Comment by kitianFresh** [comment]
But i can not run the entire product when deploy the new version cost-model.  none of the app's UI will load;  When i use your cost-model, it is ok.  I can not find the reason because  server is not open sourced, i do not know any request is blocked?

Is there any constraints  when you only build new cost-model?  Because your version has key management so developer built cost-model can not use directly?

**Comment by AjayTripathy** [comment]
That's correct-- some of the APIs are not open sourced so won't be visible, and some require the key. We also change a few of our routes, which I believe is causing no pages to render. We can take it as a goal to make at least /allocations.html render, which has the open core frontend and shouldn't be too hard to add.

**Comment by AjayTripathy** [comment]
For now-- this appears to be working as it looks like data is rendering in the open-source.

**Comment by kitianFresh** [comment]
> That's correct-- some of the APIs are not open sourced so won't be visible, and some require the key. We also change a few of our routes, which I believe is causing no pages to render. We can take it as a goal to make at least /allocations.html render, which has the open core frontend and shouldn't be too hard to add.

Thanks, if so, i can issue an pr first to add the cloud provider support.

**Comment by AjayTripathy** [comment]
That would be great! Happy to look at the PR when it's ready-- let me know if anything else is blocking you!

**Comment by AjayTripathy** [comment]
Hi @kitianFresh anything I can help you with here?

**Comment by kbrwn** [comment]
@kitianFresh Please email support@kubecost.com if you still need help with this issue.
