### ISSUE TITLE
Cost model can fail if prometheus-server isn't available yet

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-model#87]
When you deploy both pods together, the `cost-model` pod becomes available first and then errors after the timeout below.

```
main.go:294] Failed to use Prometheus at http://kubecost-prometheus-server.kubecost2.svc.cluster.local Error: Get http://kubecost-prometheus-server.kubecost2.svc.cluster.local/api/v1/status/config: dial tcp 10.15.250.213:80: i/o timeout
```

**Comment by AjayTripathy** [comment]
It's left to the user / k8s deployment to handle this, for example the cost-analyzer makes use of an initcontainer to handle this more gracefully: https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L40
