### ISSUE TITLE
AWS > Compute costs missing

### ISSUE THREAD

**Issue by andronux** [kubecost/cost-model#873]
Hello,

my kubecost instance isn't showing compute (CPU/RAM) costs

![image](https://user-images.githubusercontent.com/31890696/126539790-8cc05dd1-434d-4859-b00a-e763358c5bb4.png)

Am I missing something?

gz#585

**Comment by kbrwn** [comment]
Hello, it is possible you are missing metrics in prometheus that provide data on compute resources such as cpu/memory. Please create a [bug report](https://github.com/kubecost/docs/blob/master/bug-report.md) and email it to support@kubecost.com to get more help.

**Comment by andronux** [comment]
Hi @kbrwn , that's right I was missing metrics. I followed the documentation related to a custom prometheus instance and everything is ok.

Thank you!

![image](https://user-images.githubusercontent.com/31890696/126775975-464a0da4-ce72-4f87-a9d3-0a9206295699.png)
