### ISSUE TITLE
Suggest using query_range rather than subquery where possible, to improve caching

### ISSUE THREAD

**Issue by bboreham** [kubecost/cost-model#874]
[Hi! Not using your software myself, but I work on a hosted Prometheus where some of our customers use it]

If the Prometheus, Cortex Thanos, or similar source is using a front-end cache, that will be able to cache parts of a `query_range` request and hence be much more efficient as the range moves forward in time. These components do not currently cache parts of a subquery.

Queries like this one: https://github.com/kubecost/cost-model/blob/7727ea2fc6cd814525e4104725145247276b649c/pkg/costmodel/cluster.go#L141
can be straighforwardly converted from a subquery to a range-query.

Many other queries in your project are not so straighforward, but that one is actually the most expensive from our side.

For information:
https://cortexmetrics.io/docs/architecture/#query-frontend
https://thanos.io/tip/components/query-frontend.md/

gz#597

**Comment by AjayTripathy** [comment]
Hi @bboreham thank you for this feedback! Very excited by any potential promql query optimization :)

cc @mbolt35 and @nikovacevic 

We agree that the "active minutes" sets of queries are the most expensive, and highly prioritize feedback on optimizing it. We actually migrated this _off_ of query_range at some point in the past-- we've had major problems with thanos returning unexpected results and performing poorly on query_range, though we started as early as thanos 0.8 (when the query frontend did not exist). 

Additionally, as of v1.82+, the majority of our queries should only be querying in 1hr intervals, progressively, that get pulled into our own caching layer. Previously this resolution was daily-- my understanding is we'd have more benefit from the cache if we were building larger, progressive intervals.

I think the code to rewrite this is straightforward  We run our own scale testing against thanos, but any opportunity to collaborate and get test builds out that could confirm an optimization on your end would be great!

**Comment by AjayTripathy** [comment]
Hi @bboreham -- upon further examination, it appears that the reason we migrated and the unexpected results were that thanos was arbitrarily setting the resolution/step size when using query_range. Since we want to know with a high degree of accuracy (or at least a well understood error bound) when a pod came up and started running, we use a subquery with an enforced resolution [1h:5m] for example. Given this plus the fact that we rarely query non-overlapping ranges, if we pin resolution we're wondering if this will have the accuracy/speedups that caching via query_range would give us.

Any additional thoughts there? Would love to learn more about what you're seeing on your end. The paradigm we have here works pretty well for thanos-store at scales of roughly 2CPU/25GB per 250k pods monitored, which is what some of our users that use our bundled Thanos are at and what our own testing shows, though we're always keen to improve this.

**Comment by bboreham** [comment]
Changing the step size would be a bug. 
Cortex frontend cache does not do that. 
It does quantise start/end time to the step size, which shouldn’t make any difference at the ranges you work at. 

> we rarely query overlapping ranges

I’m seeing queries for 24h every 5 min, sometimes every 1 min.

**Comment by AjayTripathy** [comment]
Thanks for that context. I'm not sure about Cortex, but that behavior was definitely observed by us in some versions of Thanos.

 Is it possible for you to reach out to the user and ask what version of Kubecost is being run? Or put us in touch directly?  While our cache build times are configurable, as of 1.83+ we should be making the "active minutes" styles of queries only run over 1h ranges. You can send that info to me in our (slack channel)[https://join.slack.com/t/kubecost/shared_invite/enQtNTA2MjQ1NDUyODE5LWFjYzIzNWE4MDkzMmUyZGU4NjkwMzMyMjIyM2E0NGNmYjExZjBiNjk1YzY5ZDI0ZTNhZDg4NjlkMGRkYzFlZTU] or at ajay@kubecost.com

**Comment by AjayTripathy** [comment]
Also-- do you happen to know the offset of those 24h queries? During our ETL "build" process, we build 1 day at a time going back 30-60d, in a way that should not overlap. Ongoing builds for the cache prior to 1.82 were building 24h incrementally every 10 minutes, but we've reduced this to 1h incrementally every 10 minutes in later versions.

**Comment by ethirolle** [comment]
The user in question is using Kubecost v1.83.2.

I have asked the customer to reach out to you directly, and to leverage this existing issue.

Thanks!

**Comment by AjayTripathy** [comment]
Thank you @ethirolle ! We are in touch and examining their configurations. We would not expect minutely/five minutely queries against the backing prometheus and are investigating.

**Comment by AjayTripathy** [comment]
After taking a look at the user's infra + query log, we were seeing 10k+ persistent volumes, meaning this group_right was likely the most expensive. I've created https://github.com/kubecost/cost-model/pull/891 to remove the group_right-- it adds no additional queries so I suspect this will have improvements.

**Comment by kirbsauce** [comment]
Hi @bboreham , @ethirolle ,

The modifications outlined by @AjayTripathy are in last night's release of 1.86.0.  Feedback welcome!

**Comment by ethirolle** [comment]
On our hosted Prometheus, after customer implemented your fix, we saw a definite improvement:

>we no longer see `count(pv_hourly_cost) by (cluster, persistentvolume)` (or other queries) for long time ranges (like `[1440m:1m]`, as we saw earlier in this ticket). The longest we are seeing is `[60m:1m]`, which runs pretty quickly (about 5 seconds).

Thanks for your help with this!

**Comment by kirbsauce** [comment]
Thanks for the quick response, @ethirolle !  I'll close this issue out for now.
