### ISSUE TITLE
Configurable queries

### ISSUE THREAD

**Issue by zelin-l** [kubecost/cost-model#887]
Hello! Would it be possible to configure queries to match the labels that are in existing prom setups? 

For example: 
In this query
https://github.com/kubecost/cost-model/blob/08174a7d5c071297adb68931af9a7feac851a258/pkg/costmodel/allocation.go#L24 

If the existing prom setup uses container as the label but the query uses container_name, is it possible to configure that query to use a different label? (i.e. a separate configuration file containing all the queries that we could use to customize to existing setups)

Thanks!

gz#650

**Comment by kbrwn** [comment]
hi @zelin-l While I am not sure if there are plans to make these configurable we do plan to update kubecost to make use of the default cadvisor labels rather than the `pod_name`, `container_name` labels that are used right now which require a relabel/rewrite rule.

**Comment by dwbrown2** [comment]
Confirming Kyle's message! We actually have a PR for testing now -- https://github.com/kubecost/cost-model/pull/881

**Comment by zelin-l** [comment]
Thanks!

**Comment by zelin-l** [comment]
Hello! I have related question to the above:

Would it be possible to change the cluster_id label to "cluster"?
https://github.com/kubecost/cost-model/blob/068510c25953fc176d85c0ac756f31579f78a67d/pkg/env/costmodelenv.go#L23

**Comment by dwbrown2** [comment]
@zelin-l that's fully configurable in our multi-cluster deployment! Do you have an enterprise key currently to access?

**Comment by zelin-l** [comment]
Thanks for the update! I do not have an enterprise key at the moment but I will reach out if needed

**Comment by dwbrown2** [comment]
Sounds good, please feel free to reopen this issue if you have any questions!
