### ISSUE TITLE
Prevent submission of queries with duration of 0

### ISSUE THREAD

**Issue by nikovacevic** [kubecost/cost-model#888]
Sometimes, the cost-model will submit queries to Prometheus or Thanos with `0m` for a duration. We should understand why this is happening (hypothesis: rounding down to 0m from some number of seconds) and prevent it from happening by either (1) submitting queries in seconds, or (2) not submitting such a query.

Example:
```
sum_over_time((avg(kubecost_cluster_management_cost) by (cluster_id))[0m:1m] offset 180m) * 0.016667
```

gz#651

**Comment by AjayTripathy** [comment]
To clarify-- there is no expected impact here, other than these queries fail and occasionally produce errors in logs.

**Comment by michaelmdresser** [comment]
This specific query is addressed in https://github.com/kubecost/kubecost-cost-model/pull/612. It is unclear if other queries cause this error log.

**Comment by zorrobyte** [comment]
@michaelmdresser  I have a customer who upgraded to 1.95 and was getting the duration error:
2190

I understand it's just noise via Ajay's notes

The customer downgraded, I let them know I'd update the issue and told them not to worry about the log item

**Comment by michaelmdresser** [comment]
I'd like to address noisy logs if possible. Do you know what the exact error log was?
