### ISSUE TITLE
Dockerfile points to missing cloud/gcp.json

### ISSUE THREAD

**Issue by mda590** [kubecost/cost-model#90]
The Dockerfile provided for testing (and presumably used to build the app image pushed to Dockerhub) points to [`cloud/gcp.json`](https://github.com/kubecost/cost-model/blob/master/Dockerfile#L36) which doesn't exist.

**Comment by dwbrown2** [comment]
Good catch! I believe @AjayTripathy ended up using `default.json` instead. Assigning to him to confirm.

**Comment by AjayTripathy** [comment]
Looks like I neglected to add it to the file tree. It's added now.
