### ISSUE TITLE
PV hourly cost are using the default value instead of AWS terms

### ISSUE THREAD

**Issue by isra17** [kubecost/cost-model#928]
Here's the response I get from calling `/model/costDataModel`:

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/1420974/132768636-e0823926-a7da-494c-8588-0ee7760d2238.png">

If you look at the `hourlyCost`, the given value is `0.00005479452`, however the AWS json file https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/us-east-1/index.json shows:

```
      "HY3BZPP2B6K8MSJF" : {
        "HY3BZPP2B6K8MSJF.JRTCKXETXF" : {
          "offerTermCode" : "JRTCKXETXF",
          "sku" : "HY3BZPP2B6K8MSJF",
          "effectiveDate" : "2021-09-01T00:00:00Z",
          "priceDimensions" : {
            "HY3BZPP2B6K8MSJF.JRTCKXETXF.6YS6EN2CT7" : {
              "rateCode" : "HY3BZPP2B6K8MSJF.JRTCKXETXF.6YS6EN2CT7",
              "description" : "$0.10 per GB-month of General Purpose SSD (gp2) provisioned storage - US East (Northern Virginia)",
              "beginRange" : "0",
              "endRange" : "Inf",
              "unit" : "GB-Mo",
              "pricePerUnit" : {
                "USD" : "0.1000000000"
              },
              "appliesTo" : [ ]
            }
          },
          "termAttributes" : { }
        }
      },
```

Where `0.1 / 730 == 0.00013698630136986303`. Looking at my `cost-model` pod, the logs shows the AWS config was downloaded and parsed. Is there anything missing?

gz#786

**Comment by kbrwn** [comment]
@isra17 Which version of kubecost are you running? Have you integrated with the AWS[ cost and usage report](https://github.com/kubecost/docs/blob/main/aws-cloud-integrations.md)? If you fetch a [bug report](https://github.com/kubecost/docs/blob/main/bug-report.md) that may tell us more.

**Comment by isra17** [comment]
I found the bug and a simple fix. See the PR linked above!
