### ISSUE TITLE
Attribute costs for jobs running from kfp/tfx ml pipelines

### ISSUE THREAD

**Issue by etsyamitra** [kubecost/cost-model#933]
## Problem
Both kubeflow pipeline and tfx has been very prominent, but there is no way to attribute cost incurred by them. 
Each component of the pipeline spins up a resource (could be a vm, gpu, ai platform train jobs or basic traffic)
<img width="621" alt="Screen Shot 2021-09-10 at 10 38 39 AM" src="https://user-images.githubusercontent.com/75339656/132894942-98424310-e1fc-46a6-8134-413cbe3f52f4.png">

## Proposal
It would be great to have some way to visualize the cost incurred by them, i.e. aggregate over the entire pipeline id and then slice and dice on components basis.
Just getting the approximate cost for the pipeline would be a great first step towards this.

Please link to any resources/issues/docs that you might have been looking into related around this topic.

gz#791

**Comment by kbrwn** [comment]
@etsyamitra 

> Each component of the pipeline spins up a resource (could be a vm, gpu, ai platform train jobs or basic traffic)

Is it possible to label(k8s) / tag(cloud) all these resources as they are spun up? Then you can create an allocation or asset filter based on the common label/tag shared among the resources to attribute cost to the entire pipeline.

**Comment by AjayTripathy** [comment]
I think @kbrwn 's idea of tagging/labeling these as they spin up plus our GPU allocation strategy described here: https://github.com/kubecost/docs/pull/128/files should work for this.

**Comment by etsyamitra** [comment]
Thanks will go over the docs, the trick would be being able to propagate labels from pipeline level through components to the resources/vm's level. Please feel free to share any recommendations or anything in the roadmap to make it easier.

**Comment by kirbsauce** [comment]
hi @etsyamitra , curious if you've had a chance to go over the docs and, if so, we're you able to make any progress based on those and Kyle's idea?

**Comment by AjayTripathy** [comment]
Hi @etsyamitra what components specifically does kubeflow create? It should be possible to label the constituent pods created by the kubeflow pipeline right?

**Comment by AjayTripathy** [comment]
Hey @etsyamitra just wanted to circle back after our in-depth chat on this-- you can do this via grouping with cloud tags then view those groupings on kubecost Assets page. More planned here soon!

**Comment by kbrwn** [comment]
@etsyamitra Let us know if you still need any help with this issue.

**Comment by etsyamitra** [comment]
Thanks for circling back Kyle, we can close this issue.
