### ISSUE TITLE
Messed up labels for metric kube_persistentvolumeclaim_info

### ISSUE THREAD

**Issue by artemlive** [kubecost/cost-model#939]
Hello, I have a strange labeling issue with _kube_persistentvolumeclaim_info_ metric.
Labels "storageclass" and "volumename" are messed up. 

Here is the example result from kubecost job:
`kube_persistentvolumeclaim_info{instance="10.249.241.208:9003",job="kubecost",namespace="api-develop",persistentvolumeclaim="redis-ha-data-rfr-upgrade-mechanism-api-develop-php-fpm-redis-2",storageclass="pvc-5ea7b685-4aa4-4b4b-b477-da7296956362",volumename="standard"}`

I am using Kubernetes v1.18.20-gke.901 with the default configuration installed via helm chart. 
Cost-model version is "1.86.1". 

gz#805

**Comment by kbrwn** [comment]
@artemlive thanks for the PR. Will work on getting it reviewed shortly.
