### ISSUE TITLE
Oddly high root disk sizes

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-model#964]
k8s version: v1.21.2-eks-55daa9d
node type: t3.medium

This is likely a node-exporter issue, local nodes are pretty high:
![Image from iOS (2)](https://user-images.githubusercontent.com/453512/137801521-b97866c5-0287-4adc-b81f-9d6ef088a19b.png)

Some sort of crazy number in the exabyte range is showing up. We should
1. Drop very high local storage sizes from our analysis
2. Trace this issue in cadvisor.

**Comment by dwbrown2** [comment]
cc @kirbsauce as this will be part of next release.

**Comment by kirbsauce** [comment]
I believe it went out in 1.88.3.

**Comment by dwbrown2** [comment]
@AjayTripathy can you confirm and update?

**Comment by AjayTripathy** [comment]
Yes, this is available in 1.87.3. Closing!
