### ISSUE TITLE
Support AWS OOC costs via CUR CSV residing in S3 bucket

### ISSUE THREAD

**Issue by kirbsauce** [kubecost/cost-model#978]
To negate the need for Athena/Glue, provide the ability to process the CUR in CSV format via access to an S3 bucket. 

cc @kbrwn

**Comment by dwbrown2** [comment]
This should be fairly quick, but can we confirm/verify the set of cols we're expecting from early users? This may not be an issue on AWS, but it was a good amount of work on Azure.

**Comment by kirbsauce** [comment]
Request out to obtain cols.  Will update here when they land.

**Comment by srpomeroy** [comment]
This is supported as of [v1.90.0](https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.90.0)
