### ISSUE TITLE
Where does the BaseCPUCost value came from?

### ISSUE THREAD

**Issue by ingcsmoreno** [kubecost/cost-model#98]
I'd love to use this project on our Cluster, but in order to get that approval I've to able to explain each and every number shown in here. 

What I haven't been able to find is how is the **BaseCPUCost** from *aws.json* calculated in first place? Where did you get the value _0.031611_ from?

**Comment by dwbrown2** [comment]
Hi @ingcsmoreno, BaseCPUCost is used as described in "How do you determine RAM/CPU costs for a node when this data isn’t provided by a cloud provider?" in our [Q&A](https://github.com/kubecost/cost-model#questions). 

This default price is calculated on the average marginal cost of a CPU based on analysis when we first launched this product. The value is fully configurable. Let me know if I can provide more info or clarify. Also, we would be interested to hear if your team has or prefers a different approach!

**Comment by ingcsmoreno** [comment]
Hi @dwbrown2, I've been reading the source code for a while now (awesome work BTW), and I think I got how it is used, but I couldn't find any where why it got that value assigned.

Now that you mentioned that you based that value on previous analysis, I'd like to ask you if you could share more info about that. I'm currently working with a 20 nodes OpenShift cluster and more than 800 pods running in it, so I've been working on different approaches to try to understand how to calculate the cost per container, and yours look very promising, but I need to be able to understand every number, and if possible, calculate them from our current cluster as well.

So, could it be possible for you to tell me what kind of analysis did you previously run to determine the BaseCostCPU value, I'll be glad to try it our myself and share the results.

**Comment by dwbrown2** [comment]
Carlos, my apologies for the delay. We're now actively revisiting this methodology for potential improvements. We should have an update here soon. Feel free to reach out to team@kubecost.com if you want be involved in these discussions or if you want to talk directly.

**Comment by dwbrown2** [comment]
Carlos and I discussed offline some. We implemented this new methodology last month. Please feel free to reopen this issue to continue the discussion!
