### ISSUE TITLE
Kubecost's Cost Allocation page shows only kubecost's costs

### ISSUE THREAD

**Issue by hyj-github** [kubecost/cost-model#988]
I added Kubecost to my own Prometheus, and the query cost assignment was found to show kubecost costs only. Can anyone offer a reason and a solution?Details are as follows.
![kubecost异常](https://user-images.githubusercontent.com/54680729/141760467-0921beb2-cba7-49df-b46d-069c37156b27.PNG)
The state of the Prometheus:
![状态异常](https://user-images.githubusercontent.com/54680729/141760735-6597c1d4-8d7e-4c06-bbc2-3456f2fa79d2.PNG)

kubecost version: v1.73
prometheus version: v2.18.2
EKS Version: v1.18.20-eks-8c579e

gz#1037

**Comment by kbrwn** [comment]
@hyj-github It looks like you are missing metrics that would be needed when using custom prometheus. First, I suggest you upgrade to [v1.88.0](https://github.com/kubecost/cost-analyzer-helm-chart/releases/tag/v1.88.0) as v1.73 is a much older release and then review the [custom prometheus documentation](https://guide.kubecost.com/hc/en-us/articles/4407595941015-Custom-Prometheus). If you are able to ship with the bundled prometheus that would likely make deployment and maintenance of kubecost much easier. 

For further help please email support@kubecost.com or join our [slack community](https://kubecost.slack.com).

**Comment by kbrwn** [comment]
@hyj-github Customer support for custom prometheus is not available for free/community edition of kubecost. I suggest you revert back to the bundled prometheus if you are unable to debug your custom prometheus deployment. If you are a business/enterprise user please email support@kubecost.com for further assistance with custom prom.

**Comment by hyj-github** [comment]
> @hyj-github Customer support for custom prometheus is not available for free/community edition of kubecost. I suggest you revert back to the bundled prometheus if you are unable to debug your custom prometheus deployment. If you are a business/enterprise user please email [support@kubecost.com](mailto:support@kubecost.com) for further assistance with custom prom.

Is this why the cost display is abnormal, showing only the cost of Kubecost?

**Comment by dwbrown2** [comment]
Take a look at the diagnostic page in your Kubecost deployment to learn more. 

This looks like a potential `honor_labels` issue if you only see one namespace...

**Comment by kbrwn** [comment]
@hyj-github Please join [kubecost.slack.com](https://kubecost.slack.com) to get more help! You can join the #support channel or dm me.

**Comment by hyj-github** [comment]
> @hyj-github Please join [kubecost.slack.com](https://kubecost.slack.com) to get more help! You can join the #support channel or dm me.

How to register kubecost.slack.com account, need invitation？
![捕获](https://user-images.githubusercontent.com/54680729/145070258-0d6f0880-ce20-47c0-94e3-d6bd018f8b6f.PNG)

**Comment by kbrwn** [comment]
@hyj-github You don't need an invitation to join the kubecost slack. You do need a slack account to join. You can create a slack account if you don't have one already by clicking "Don’t have an account yet? Create an account" in the top right corner of the screen.

**Comment by kbrwn** [comment]
Oh I guess you have to use this special link: https://join.slack.com/t/kubecost/shared_invite/enQtNTA2MjQ1NDUyODE5LWFjYzIzNWE4MDkz[…]kwMzMyMjIyM2E0NGNmYjExZjBiNjk1YzY5ZDI0ZTNhZDg4NjlkMGRkYzFlZTU
