### ISSUE TITLE
Rate Card API fails for users of Azure Gov Cloud

### ISSUE THREAD

**Issue by Sean-Holcomb** [kubecost/cost-model#990]
# Issue
User on Azure gov cloud is unable to access Rate Card api and due to use of public cloud endpoint receiving error
```
Failed to download pricing data: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/{REDACTED}/providers/Microsoft.Commerce/RateCard?%24filter=OfferDurableId+eq+%27MS-AZR-0003p%27+and+Currency+eq+%27USD%27+and+Locale+eq+%27en-US%27+and+RegionInfo+eq+%27US%27&api-version=2015-06-01-preview: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"AADSTS900382: Confidential Client is not supported in Cross Cloud request.\r\nTrace ID: {REDACTED}\r\nCorrelation ID: {REDACTED}\r\nTimestamp: 2021-11-04 16:30:19Z","error_codes":[900382],"timestamp":"2021-11-04 16:30:19Z","trace_id":"{REDACTED}","correlation_id":"{REDACTED}"}
```
# Resolution
Add optional cloud variable to Rate Card configuration to allow the specification of users cloud (PublicCloud, USGovernmentCloud,  ChinaCloud or GermanCloud) which defaults to public cloud. This can be applied here to resolve the issue. https://github.com/kubecost/cost-model/blob/c5c9ad147ee016dd6a35f461d007f4eb41d9f433/pkg/cloud/azureprovider.go#L764 <br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/995'>Zendesk ticket #995</a>)<br>gz#995</i>

**Comment by kirbsauce** [comment]
thanks @Sean-Holcomb !

**Comment by Sean-Holcomb** [comment]
https://github.com/kubecost/cost-model/pull/994 has been merged to open source, which attempts to detect the correct cloud api to use based on region name, there is no additional configuration required.

**Comment by michaelmdresser** [comment]
@Sean-Holcomb can we close this issue?

**Comment by kbrwn** [comment]
https://github.com/kubecost/cost-model/blob/422435faddfe6a3b5adae66bb918ea8987500d67/pkg/cloud/azureprovider.go#L774-L781
authorizer = a   means authorizer won't ever be nil so the function to trigger gov cloud selection never occurs

**Comment by dwbrown2** [comment]
@Sean-Holcomb still work needed on this one?

**Comment by Sean-Holcomb** [comment]
I would like to hear back from the user before we close

**Comment by AjayTripathy** [comment]
Just a note that I do not think this will make v1.91.0 and we expect it in nightly/1.92.0

**Comment by kirbsauce** [comment]
Thanks for the confirmation @AjayTripathy , that's my understanding.
