### ISSUE TITLE
Minutes Running Inaccuracy for Uncontrolled Pods with Same Name/Namespace

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-model#991]
Because of the way start/end times are calculated and because of the way we key on pods, when accumulating pods over some windows, the minutes running calculation may be inaccurate.

Pod A                        

X-------------X       X-------------X
12                    5        7                     10

Currently the start/end will be listed as 12-10 and 600 minutes running, because an uncontrolled pod with the same name will have the same key whereas this should either be listed as two different line items, Pod A1 12-5 300 minutes running and Pod A2 7-10 180 minutes running.

Note because costs are cumulative, the total cost in the cost-model should not be affected.
<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1050'>Zendesk ticket #1050</a>)<br>gz#1050</i>

**Comment by michaelmdresser** [comment]
Reformatting for clarity.

Namespace `N1`  
Uncontrolled Pod `A`  
```
Pod running the first time      Pod running the second time
X-------------X                 X-------------X
12           17                 19           22

Time ------>
```

As Ajay noted, cost will be reported accurately because we consider average resource usage/request over an entire window.

The likely best approach to disambiguating between any Kubernetes object with similar properties (e.g. namespace, pod name) is to use [Kubernetes UIDs](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids). We will have to confirm if UIDs are emitted as labels on the various metrics we care about. If not, this may be a tricky problem to tackle.

**Comment by dwbrown2** [comment]
This seems to me like it would rarely happen in a way that would materially impact time running calculations. Are there certain scenarios where this would be more common?

**Comment by Suchitpandya1** [comment]
> This seems to me like it would rarely happen in a way that would materially impact time running calculations. Are there certain scenarios where this would be more common?

We reported this issue and are still experiencing it. This has been a happening often on our platform. We show platform users a recently created container/Jupyterhub notebook details and decent number of users create/start the exact same Notebooks/Containers/Pods.

**Comment by AjayTripathy** [comment]
Yep, sorry for not clarifying the reporter @Suchitpandya1 . We're tracking this closely and expect to tackle this in Q1 of the new year.

**Comment by mbolt35** [comment]
@michaelmdresser Looked into the pod UID label on metrics. The KSM v1.9.8 does _NOT_ include a `uid` label on the emitted pod metrics. Our replicated KSM metrics _DO_ include a `uid` label on the emitted pod metrics (foresight I guess), and KSM v2+ pod metrics also include the `uid` label. 

It does seem like the users who are turning off the replicated metrics we emit are primarily KSM v2+ users. However, users turning off our KSM replication in favor of running their own KSM v1.9.8 (or less) will present problems for us when attempting to uniquely identify pods.

**Comment by mbolt35** [comment]
> This seems to me like it would rarely happen in a way that would materially impact time running calculations. Are there certain scenarios where this would be more common?

The most basic example of where this would be a problem is any StatefulSet in kubernetes. Since StatefulSets implement an ordered naming convention, you end up with pod names that collide (potentially many times).

**Comment by mbolt35** [comment]
It occurred to me that all kubernetes resources have the `creationTimestamp` and I followed that up with a search for metrics that may contain this timestamp. [Latest KSM](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md) has the two metrics: `kube_pod_start_time` and `kube_pod_completion_time` which leverage the timestamps on the kubernetes objects themselves. Using these would introduce a bit more of a logistical challenge (required whitelisting, not retroactive, etc...) similar to UIDs, but I see two important key features that would come from these:
1) Our ability to pinpoint the exact times pods start and end (versus the scrape times on metrics) 
2) Our ability to separate distinct pod lifecycles without having to uniquely identify them (although I still think unique identification is important) 

Thoughts?

**Comment by dwbrown2** [comment]
> It occurred to me that all kubernetes resources have the `creationTimestamp` and I followed that up with a search for metrics that may contain this timestamp. [Latest KSM](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md) has the two metrics: `kube_pod_start_time` and `kube_pod_completion_time` which leverage the timestamps on the kubernetes objects themselves. Using these would introduce a bit more of a logistical challenge (required whitelisting, not retroactive, etc...) similar to UIDs, but I see two important key features that would come from these:
> 
> 1. Our ability to pinpoint the exact times pods start and end (versus the scrape times on metrics)
> 2. Our ability to separate distinct pod lifecycles without having to uniquely identify them (although I still think unique identification is important)
> 
> Thoughts?

@nikovacevic couldn't those potentially simplify things greatly? guessing those metrics might have their own nuances though...

**Comment by AjayTripathy** [comment]
We can already note that two pod lifecycles are distinct, but I believe @kaelanspatel mentioned he was having trouble keying on things like timestamps since they varied from collector to collector/metric to metric.

The decision I think makes the most sense is to get minutes running accurate by uniquely identifying pods, then to normalize our usage and request metrics based on runtime.

**Comment by mbolt35** [comment]
@AjayTripathy How do you note that two pod lifecycles are distinct with a single metric and pod name? If one pod goes down and comes up in a single scrape, how can you determine that one pod ended and the other started?

**Comment by AjayTripathy** [comment]
Scrape intervals are pretty small, so I suspect it's ok to estimate there?

**Comment by Adam-Stack-PM** [comment]
@kaelanspatel Can we close this out? My understanding is that https://github.com/kubecost/cost-model/pull/1131 fixed it.

**Comment by kaelanspatel** [comment]
Yes, should be fine to close it.

**Comment by kirbsauce** [comment]
Hi @Suchitpandya1.  This issue has been addressed in 1.93.  Looking forward to your feedback when you have a chance to upgrade!

**Comment by AjayTripathy** [comment]
A Flag is needed to turn this on right @kaelanspatel ? Where is that documented/can we attach that doc to this bug?

**Comment by kaelanspatel** [comment]
That's correct, this bug was solved by [adding a flag](https://github.com/kubecost/cost-analyzer-helm-chart/pull/1327) `.Values.kubecostProductConfigs.ingestPodUID` that toggles appending pod UID from KSM metrics to the podname field in Allocations, so that pods with the same name can be uniquely identified.

**Comment by kirbsauce** [comment]
@Suchitpandya1 , sorry for any confusion.  As @kaelanspatel mentioned above, you'll need to set the `.Values.kubecostProductConfigs.ingestPodUID` flag.  Looking forward to your feedback!
